### ISSUE TITLE
Web Chat instructions/samples/etc. should default to using websocket instead of polling GET

### ISSUE THREAD

**Issue by dandriscoll** [Microsoft/BotFramework-WebChat#1101]
Anyone customizing Web Chat should, by default, use websockets. It's faster and lighter weight.

**Comment by dandriscoll** [comment]
May also extend to DirectLineJs

**Comment by compulim** [comment]
On [`DirectLineJS/directLine.ts:317`](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L317), it say: if the `webSocket` flag is not set and the browser support WebSocket, it will do WebSocket.

And I looked at [`WebChat/Chat.tsx`](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Chat.tsx#L193), we didn't default it to off.

So I guess people intentionally switch Web Socket off because we are lacking of automatic protocol detection.

Two approaches:
- We add automatic protocol detection, so people are less likely to switch off Web Socket
- We add a new Server-Sent Event protocol, so we are still on push-based and it should works fine with old proxy
   - Edge doesn't work with SSE, it's under consideration, we still have WS

![image](https://user-images.githubusercontent.com/1622400/44547850-32798300-a6d1-11e8-830a-076b84d0353d.png)

![image](https://user-images.githubusercontent.com/1622400/44547936-7b313c00-a6d1-11e8-9675-8075a3d65030.png)

**Comment by compulim** [comment]
Opened two tracking issues:

- [Implement automatic protocol detection](https://github.com/Microsoft/BotFramework-DirectLineJS/issues/88)
- [Consider to implement Server-Sent Events](https://github.com/Microsoft/BotFramework-DirectLineJS/issues/89)
