### ISSUE TITLE
New Speech Recognizer

### ISSUE THREAD

**Issue by DanielTizon** [Microsoft/BotFramework-WebChat#1137]
Hi,

Currently, I am using Webchat with Bing Speech Recognizer, and I use this script in the webchat:

```
  var speechOptions = {
            speechRecognizer: new CognitiveServices.SpeechRecognizer({
                subscriptionKey: 'key',
                locale: "es-ES"
            }),
            speechSynthesizer: new CognitiveServices.SpeechSynthesizer(
                {
                    subscriptionKey: 'key',
                    gender: CognitiveServices.SynthesisGender.Female,
                    voiceName: 'Microsoft Server Speech Text to Speech Voice (es-ES, HelenaRUS)'
                }
            )
        }
```

But this speech recognizer is doing a bad "speech to text" with some spanish phrases, so 
I would like to use the new Microsoft Speech Service (with the hope of a better performance):

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/

But when I change the subscription key of SpeechRecognizer for the new one of the Speech Service created in Azure, I get the following errors:

HTTP Authentication failed; no valid credentials available
ConnectionEstablishErrorEvent
RecognitionEndedEvent

I guess that I still can't use the new speech service in webchat or I need to change something in code, right?

**Comment by compulim** [comment]
@DanielTizon I think this is the [related bug](https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/issues/85) on `microsoft-browser-speech-sdk` which Web Chat depends on.

And there is a [PR](https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/pull/82) to get the customizable endpoint.

Since Web Chat is depending on `microsoft-browser-speech-sdk`, we need them to get the fix in, so Web Chat will works with the new Speech Service.

Can you ping them over their repository? I think this is a bug on their side. I will track it accordingly.
