### ISSUE TITLE
Issues with redux when importing Chat in existing react App

### ISSUE THREAD

**Issue by ThomasMaes** [Microsoft/BotFramework-WebChat#1146]
Hi,

I am trying to include the webchat in an existing (pretty big) react application.
The control renders and the bot sends it's welcome message, but it is also throwing a message in the browser.

Uncaught TypeError: action$.ofType(...).map is not a function
    at updateSelectedActivityEpic (Store.js:388)
    at combineEpics.js:26
    at Array.map (<anonymous>)
    at combineEpics.js:25
    at MapSubscriber.project (createEpicMiddleware.js:52)
    at MapSubscriber._next (map.js:35)
    at MapSubscriber.Subscriber.next (Subscriber.js:54)
    at Subject.next (Subject.js:47)
    at createEpicMiddleware.js:62
    at applyMiddleware.js:41

This seems to be related to redux-observable something i am not using in the parent react app. 
At first I thought i was missing some files but all redux files seem to be loaded in the browser.

I am using webpack build my bundle which includes the webchat control.
Is there a setting I am missing?

I Include the webchat control like this:

import * as BotChat from 'botframework-webchat'

<BotChat.Chat
                      adaptiveCardsHostConfig={{
                        "supportsInteractivity": true,
                        "strongSeparation": {
                            "spacing": 10,
                            "lineThickness": 1,
                            "lineColor": "#EEEEEE"
                        },
                        "fontFamily": "Segoe UI",
                        "fontSizes": {
                            "small": 12,
                            "normal": 14,
                            "medium": 17,
                            "large": 21,
                            "extraLarge": 26
                        },
                        "fontWeights": {
                            "lighter": 200,
                            "normal": 400,
                            "bolder": 600
                        },
                        "colors": {
                            "dark": {
                                "normal": "#333333",
                                "subtle": "#EE333333"
                            },
                            "light": {
                                "normal": "#FFFFFF",
                                "subtle": "#88FFFFFF"
                            },
                            "accent": {
                                "normal": "#2E89FC",
                                "subtle": "#882E89FC"
                            },
                            "attention": {
                                "normal": "#5D60B3",
                                "subtle": "#DD5D60B3"
                            },
                            "good": {
                                "normal": "#00a000",
                                "subtle": "#DD00a000"
                            },
                            "warning": {
                                "normal": "#c00000",
                                "subtle": "#DDc00000"
                            }
                        },
                        "imageSizes": {
                            "small": 40,
                            "medium": 80,
                            "large": 160
                        },
                        "actions": {
                            "maxActions": 5,
                            "separation": {
                                "spacing": 10
                            },
                            "buttonSpacing": 20,
                            "stretch": false,
                            "showCard": {
                                "actionMode": "inlineEdgeToEdge",
                                "inlineCardSpacing": 16,
                                "backgroundColor": "#08000000",
                                "padding": {
                                    "top": 16,
                                    "right": 16,
                                    "bottom": 16,
                                    "left": 16
                                }
                            },
                            "actionsOrientation": "horizontal",
                            "actionAlignment": "left"
                        },
                        "adaptiveCard": {
                            "backgroundColor": "#fafafa",
                            "padding": {
                                "left": 10,
                                "top": 10,
                                "right": 10,
                                "bottom": 10
                            }
                        },
                        "container": {
                            "separation": {
                                "spacing": 10
                            },
                            "normal": {},
                            "emphasis": {
                                "backgroundColor": "#cccccc",
                                "borderColor": "#aaaaaa",
                                "borderThickness": {
                                    "top": 1,
                                    "right": 1,
                                    "bottom": 1,
                                    "left": 1
                                },
                                "padding": {
                                    "top": 10,
                                    "right": 10,
                                    "bottom": 10,
                                    "left": 10
                                }
                            }
                        },
                        "textBlock": {
                            "color": "dark",
                            "separations": {
                                "small": {
                                    "spacing": 10
                                },
                                "normal": {
                                    "spacing": 10
                                },
                                "medium": {
                                    "spacing": 10
                                },
                                "large": {
                                    "spacing": 10
                                },
                                "extraLarge": {
                                    "spacing": 10
                                }
                            }
                        },
                        "image": {
                            "size": "medium",
                            "separation": {
                                "spacing": 10
                            }
                        },
                        "imageSet": {
                            "imageSize": "medium",
                            "separation": {
                                "spacing": 10
                            }
                        },
                        "factSet": {
                            "separation": {
                                "spacing": 10
                            },
                            "title": {
                                "color": "dark",
                                "size": "normal",
                                "isSubtle": false,
                                "weight": "bolder"
                            },
                            "value": {
                                "color": "dark",
                                "size": "normal",
                                "isSubtle": false,
                                "weight": "normal"
                            },
                            "spacing": 10
                        },
                        "input": {
                            "separation": {
                                "spacing": 10
                            }
                        },
                        "columnSet": {
                            "separation": {
                                "spacing": 10
                            }
                        },
                        "column": {
                            "separation": {
                                "spacing": 10
                            }
                        }
                    }}
                      bot={{
                        id: 'sibe-sibel-dev-bot',
                        name: 'Sibel'
                      }}
                      directLine={{
                        secret: 'My Secret here'
                      }}
                      user={{ id: this.props.user.loginName.toString(), name: this.props.user.loginName.toString() }}
                      chatTitle="Ask Sibel"
                      sendTyping={true}
                      locale="nl"
                    />

**Comment by compulim** [comment]
Can you check if `rxjs` is correctly loaded and usable in your project? `.map` things is from `rxjs`, via `redux-observable`.

**Comment by ThomasMaes** [comment]
![image](https://user-images.githubusercontent.com/29087723/45383851-a2ae6100-b60c-11e8-86d0-bd325874c574.png)

Everything seems to be in the webpack yes. Is there something i must configure or something?

**Comment by compulim** [comment]
Sorry I can't debug into your bigger project, but I will try my best to guide you to debug on your side.

From what I look at here, `action$.ofType(...).map` is not a function. And you got `rxjs` installed.

I would try put a breakpoint near the line and see if I can create a new rxjs/Observable and do the `ofType` and `map`. I am suspecting if there is a version conflict over here.

TBH, the rxjs version used by Web Chat is pretty dated, that might causing the issue.

**Comment by ThomasMaes** [comment]
Hi, Thank you for helping me. But I have to apologize here, I am not familiar with rxjs at all.
I tried to create a new rxjs/Observable, but don't really now the syntax or the object that I need to create.
I looked it up and saw I need to do something like Observable.create, but i do not seem to have that function.

![image](https://user-images.githubusercontent.com/29087723/45470258-60307580-b72d-11e8-8b05-8eac02cfe68b.png)

I also deleted every reference to redux, rxjs and observable from my node_modules folder and packages.config to make sure I have no version conflicts. The parent react app definetly does not have any reference to any of these packages now. unfortunately the error stays the same.

**Comment by compulim** [comment]
Can you try if the following code works?

```
Observable.of(123).filter(x => x > 100).map(x => x * 10).subscribe({ next: (v: number) => console.log(v) });
```

This should log `1230`.

**Comment by ThomasMaes** [comment]
Hmm,

This is failing as well. I have now installed exactly the same versions of rxjs, redux and observable.

![image](https://user-images.githubusercontent.com/29087723/45512506-277db400-b7a0-11e8-8cbe-2b497fce1779.png)

**Comment by compulim** [comment]
So I think this prove it is unrelated to Web Chat but more on the bundling side, same as what we believe.

One liner for Observable: you can think of observable as an event stream. You subscribe to its event. And apart from events, the stream can also say "I am done, no more events", or "I got error and closing now".

The question is, why `Observable.of()` is not returning an object that contains `filter` or `ofType`. `Observable.of()` is creating a stream with predefined objects/events. `filter` or `ofType` is an operator that filter out certain events, so the result is another stream just having that specific type of event.

So, give you a broader sense of what is going on:
1. `filter`, `flatMap`, `ofType`, `map`, are all Observable operators
2. These operators can be tree-shaken by Webpack, that means, if we don't use it, the final bundle won't have it
3. Also, if we don't `import` them, they don't exist too

The question is, are they imported? And are they imported but tree-shaken off? Are they imported but cannot be used because of different versions?

Observable is becoming a standard too, so there will be `window.Observable`. Do you polyfilled it and is RxJS doesn't like your polyfill so it don't add operators?

**Comment by compulim** [comment]
Looks weird to me that you need to import manually.

- Store.js is calling `.delay()` on `action$`
- I believe `action$` is something from `redux-observable`, it is a stream of Redux actions exposed as Observable

The question is, why the import statement at [`Store.ts` line 538](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Store.ts#L538) is not prototyping `.delay()` for `Observable` created by `redux-observable`?

**Comment by ThomasMaes** [comment]
Has to be something with the webpack and the polyfill filters maybe?
This is uncharted teritory for me unfortunately. I have added delay to the import and now it is complaining about filter.

Store.js:405 Uncaught TypeError: action$.ofType(...).map(...).filter is not a function
    at sendTypingEpic (Store.js:405)
    at combineEpics.js:26

**Comment by ThomasMaes** [comment]
Hmmm this is going to be a lot of trial and error this way. I must be missing something.

filter added. Throttletime now.
Uncaught TypeError: action$.ofType(...).map(...).filter(...).throttleTime is not a function
    at sendTypingEpic (Store.js:406)
    at combineEpics.js:26

**Comment by ThomasMaes** [comment]
Allright it works. It actually works. Now to find out if there is a better way, because it just bloated my bundle with about 3mb worth of files.. 

Thank you for your help anyways. :)

**Comment by compulim** [comment]
Good to know.

Yea, `rxjs` is huge and we are considering moving away from it:
1. Web Chat v4 will be free of `rxjs`, we will use `redux-saga` for business logic
2. Direct Line JS will move to `zen-observable` and only use minimal set defined in [ES Observable](https://github.com/tc39/proposal-observable)
   - When ES Observable arrive, or when it is in `core-js`/`babel-runtime`, we will remove `zen-observable`

**Comment by alexknipfer** [comment]
@ThomasMaes I’m running into the same issue of map not being a function, did you happen to find a better solution than manually importing them?

**Comment by ThomasMaes** [comment]
No sorry not at the moment, I am planning to integrate the new version of the webchat control in the future. This should also solve this issue as they are no longer using the packages that i needed to add as import.

**Comment by compulim** [comment]
@ThomasMaes do let me know if you run into any issues. If you don't know how to do any customizations, let me know, I might actually write you a sample for it and host it live here.

**Comment by compulim** [comment]
After some investigations, now I understand what is going on.

Dependency graph:

- Web Chat use `redux-observable@0.13.0` and `rxjs@5`
- `redux-observable` requires `rxjs@5.0.0-beta.10` as peer dependency
- `create-react-app` somehow requires `inquirer`, which requires `rxjs@6`

So in your `node_modules` folder, it looks like:

- `/inquirer`
- `/rxjs@6`
- `/redux-observable@0.13.0`
- `/botframework-webchat/node_modules/rxjs@5`

When Web Chat talk to `redux-observable`, `redux-observable` is looking for `rxjs`. It want `@5.0.0-beta.10`, but it accidentally picked up `rxjs@6`.

The reason is because `redux-observable` is requiring a beta version (`@5.0.0-beta.10`) which does not follow the semver rule. So NPM think it can pickup whatever version is available on the system. Web Chat do provide `rxjs@5`, but `redux-observable` is not picking it up because they say they are okay to skip semver.

And since `redux-observable` is peer-depending on a package that is not semver-ed, it is actually picking up whatever version you have in your box, i.e. `rxjs@6`.

## Timeline

So, let me run thru the timeline.

### Bad

`create-react-app` will create the following `node_modules` structure:

- `/rxjs@6`

Then `npm install botframework-webchat@0.15.0` on top of it will do:

- `/rxjs@6`
- `/redux-observable@0.13.0`
- `/botframework-webchat/node_modules/rxjs@5`

### Good

If `redux-observable` is correctly depending on `rxjs@5` instead of `rxjs@5.0.0-beta.10`, it would looks like this. `create-react-app` will create the following structure:

- `/rxjs@6`

Then `npm install botframework-webchat@0.15.0` on top of it will either do:

- `/rxjs@5`
- `/inquirer/rxjs@6`
- `/redux-observable@0.13.0`
- `/botframework-webchat@0.15.0`

Or it will do (both cases are good):

- `/rxjs@6`
- `/botframework-webchat@0.15.0`
- `/botframework-webchat@0.15.0/redux-observable@0.13.0`
- `/botframework-webchat@0.15.0/rxjs@5`

This will be the correct structure because `redux-observable` can now reach a `rxjs@5`.

But unfortunately, `redux-observable` is picking up a non-semver `rxjs`. The behavior become undeterministic. It could pickup `rxjs@5` or `rxjs@6` depends on your install order.

## Workaround

We need to make sure `rxjs@6` is not imported by `redux-observable`.

One thing I tried is:

- `npm install rxjs@5`

Then in my code, I wrote, `import { Observable } from 'rxjs';`. But I am just importing it there but not calling it.

Then, `redux-observable` will pick up the correct version of `rxjs` because `rxjs@6` is being moved under `inquirer`.

**Comment by rodrigorodriguez** [comment]
Thank you.
After updating https://github.com/pragmatismo-io/BotServer/tree/azure-arm-automation/packages/default.gbui with the Workaround(rxjs@5), the error now is the one described here: https://github.com/Microsoft/BotFramework-WebChat/issues/970.
I'm still available for screen sharing.

**Comment by compulim** [comment]
Sorry I can't do screen sharing for now. Need to read some guidelines if I am allowed to do so. You know, looking at your intellectual property (source code) without reading our support guidelines is a bit worry to me.

I still love to help over GitHub, so everything is transparent.

Looking at it now.

**Comment by rodrigorodriguez** [comment]
It's not IP, it's AGPL-3.0.

**Comment by compulim** [comment]
I should learn how to run/build your stuff. And maybe I could do a brownbag to our team to demo your stuff. We love customers.

(I am in a meeting, multiple back-to-back, response may be slower.)
