### ISSUE TITLE
Speech not working on preview webchat

### ISSUE THREAD

**Issue by darrenj** [Microsoft/BotFramework-WebChat#1177]
I'm trying to use the latest preview webchat and enable speech. The documentations seems to indicate that the default bundle has cognitiveServices contained within it however this doesn't appear to work so I had to add the CognitiveServices.js package in (latest - doesn't seem to be available on preview).

Here is the code I'm using and testing using Edge. No errors are shown in developer tools.

```
   <div id="webchat"></div>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/CognitiveServices.js"></script>
    <script src="https://cdn.botframework.com/botframework-webchat/preview/botchat.js"></script>
    <script>

        const speechOptions = {

            speechRecognizer: new CognitiveServices.SpeechRecognizer({ subscriptionKey: 'MYKEY' }),
            speechSynthesizer: new CognitiveServices.SpeechSynthesizer({
                gender: CognitiveServices.SynthesisGender.Female,
                subscriptionKey: 'MYKEY',
                voiceName: 'Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)'
            })
        };

        window.WebChat.renderWebChat({
            directLine: window.WebChat.createDirectLine({
                secret: '@ViewData["DirectLineSecret"]',
                user: { id: '@ViewData["UserId"]' },
                speechOptions: speechOptions,
                resize: 'detect',
                botAvatarInitials: 'AS',
                userAvatarInitials: 'US',                
            })
        }, document.getElementById('webchat'));
    </script>
```

**Comment by Toemsel** [comment]
Same issue here. Trying with de-DE, de-AT or even en-US.

**Comment by compulim** [comment]
Web Chat preview changed how it consume Cognitive Services. In short, instead of using custom `SpeechModule.ts`, we are simplifying the architecture by consuming a standard Web Speech ponyfill.

I am working on this sample now, hopefully it will be in soon.

**Comment by compulim** [comment]
#1190 this is the sample I am working on for this issue.

I broke down some components, reasons/details inside the PR.

**Comment by compulim** [comment]
Fixed in #1190.

You can find the sample at [`speech-cognitive-services-bing-speech`](https://github.com/Microsoft/BotFramework-WebChat/blob/preview/samples/speech-cognitive-services-bing-speech/index.html).

In this sample, we fetch the speech token in HTML. This is not secure and is for demonstration purpose. You should fetch the token on the server (to keep your subscription key secure).

So, in short, you only need to modify your code by adding [line 70](https://github.com/Microsoft/BotFramework-WebChat/blob/preview/samples/speech-cognitive-services-bing-speech/index.html#L70).

Web Chat will call `fetchToken` every time it need a token, so please cache it on your code. In the future version, Web Chat can call `fetchToken` only if it is needed (e.g. got 401/403 from the service, or look inside the JWT). But until then, we recommend you to cache the token.

> This [article](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/how-to/how-to-authentication?tabs=Powershell#get-an-authorization-token) say the speech token will expire every 10 minutes.

**Comment by glbeast63** [comment]
Would there be any difference, if I were wanting to use this with react? I get the error "TypeError: webSpeechPonyfillFactory is not a function"

thanks

**Comment by compulim** [comment]
This is the same for React route. `renderWebChat()` is more-or-less a wrapper for `ReactDOM.render()`.

I have added an example in [this PR](https://github.com/Microsoft/BotFramework-WebChat/pull/1200). You can find it [here](https://github.com/Microsoft/BotFramework-WebChat/blob/preview/samples/speech-cognitive-services-bing-speech-react/index.html).

**Comment by glbeast63** [comment]
Thanks for the quick response! I noticed that in your example, you did not use renderWebChat(). I guess I am not quite sure how to use it?
