### ISSUE TITLE
How to enable Speech in BotFramework inside Android WebView

### ISSUE THREAD

**Issue by debnathSD** [Microsoft/BotFramework-WebChat#1185]
Hi, 

I am loading a bot URL inside an android application WebView. I have recently added speak feature in my bot, I have tried and tested in Native Browser - it works perfectly.

But when I am trying to use the same feature in a WebView, the Microphone icon itself is not coming and nothing is spoken by the bot.

P.S., I am using **.BrowserSpeechRecognizer()** and **.BrowserSpeechSynthesizer()**

**Comment by compulim** [comment]
`WebView` may have limited supported on speech because they are not a full browser. Unfortunately, [CanIUse.com](https://caniuse.com) don't list `WebView`, so it's difficult to tell which OS version support what APIs.

For WebRTC support, can you try if WebRTC is working properly in WebView? If yes, Cognitive Services will probably work in `WebView`.

For Web Speech API support, can you visit https://compulim.github.io/react-dictate-button/ and see if it works in WebView?

**Comment by debnathSD** [comment]
Hi @compulim , I was tracking this [chromium bug thread](https://bugs.chromium.org/p/chromium/issues/detail?id=487255) which says that Support for Web Speech API in Android WebView is not present till date.

I will try some alternatives and update the thread if I get it working!

Thanks!!

**Comment by raviKsah** [comment]
@debnathSD  do you have any update to enable speech-text in an android web view through botframework V4 webchat?

**Comment by pwilliams2020** [comment]
Any updates on text to speech in web view
