### ISSUE TITLE
Enable speech on webchat with Azure AD botauth dialog 

### ISSUE THREAD

**Issue by jaiswati** [Microsoft/BotFramework-WebChat#1208]
Hi 

We have enabled speech as per  the instructions as given in this repository. (using C# Azure Bot, and then adding reference to webchat.html that enables speech)
To authernticate users to perform graph operations (like sending emails), We have configured the BotAuth dialogs in this C# bot
For the first time user is authenticated and email is sent with his id
but for the second time & second user, Directline api still refers to old token &  posts the old message(that was posted to first user)..
How to reset the directline cache for each user
Also posted this question here
https://stackoverflow.com/questions/52781825/enable-speech-on-webchat-with-botauth-dialog

**Comment by halfer** [comment]
The begging in the title is just as unwelcome here, @jaiswati. I suggest you remove it, given that you are addressing volunteers.

While projects on GitHub operate their own rules, the following article is still a recommended read for you: it demonstrates that when volunteers offer a service, very few people think it is reasonable to let people barge to the front of the queue. Please read: [Under what circumstances may I add “urgent” or other similar phrases to my question, in order to obtain faster answers?](//meta.stackoverflow.com/q/326569).

**Comment by jaiswati** [comment]
Done..Will keep this in mind.. thank you

**Comment by halfer** [comment]
@jaiswati: the title here is still asking to queue-jump. Please remove `[Please reply asap,it is urgent]`.
