### ISSUE TITLE
Communication between two bots (Direct Line)

### ISSUE THREAD

**Issue by riddick4u** [Microsoft/BotFramework-WebChat#1258]
Hi Team,

We have a use case where we have initialized two web chat bots with direct line channel. 

Now we are trying to achieve the following:

1.. Display Bot B message to Bot A directly, Bot B messages we are receiving in JS event. Need to send these message to Bot A web chat window.
2.  For certain condition prevent the user message to post server side. We want to handle this with Web Chat code only. 

Please provide any inputs or pointers on how we can achieve this with customization of web chat code or is there any way to achieve this without customization of code.

**Comment by compulim** [comment]
1. Do you mean: inside a browser tab, it is connected to two bots. But the result from two bots are aggregated in the same UI?
2. What do you mean by "post server side"?

Can you give an example how it would work?

**Comment by riddick4u** [comment]
@compulim 
 Thanks for your reply.

for your question #1, yes we initialized two chatbots in one page. Bot A and Bot B, Bot B chat window will hide and if user type in Bot A for certain condition we are sending the message to Bot B. Bot B reply messages we are receiving in the CallBack function of JS with activity object. 

With this we are trying to do the following:

1. Bot B reply messages to be passed to Bot A chat message window directly. 

 function messageCallback(activity) {

// activity object of Bot B messages which need to be passed and rendered to Bot A chat window.
}

2.  When user types in Bot A for certain condition we are sending the message to Bot B, however, the same message is posting to our Bot Service API which we do not want to post as we only pass the messages to Bot B. Please see the code base for more clarity.

botConnection.activity$
                  .subscribe(function (activity) {
                      if ("CertainCondition") {
                          // to pass the messages of Bot A to Bot B
                         window.WebChat.postMessage("") ; this function is using for post Bot A message to Bot B
                      }
                  });

**Comment by compulim** [comment]
You can write a new `DirectLineJS` class, namely, `DirectLineJSRouter`. And the new class route to two underlying `DirectLineJS` object.

Since `DirectLineJS` only expose a handful of events (observables) and functions, it is definitely possible to rewrite it in a short period of time. The new `DirectLineJSRouter` will do the routing (your step 2) and activity aggregation (your step 1) internally so Web Chat is transparent to it.

I think it will take 1 week to write a prototype, another 2-3 weeks to make it production-grade. The solution is robust and reliable, and not hacky. The difficult parts (i.e. risks) in this solution is handling network partition (only one of them is connected), resume of conversation, and token renewal.

What do you think?

**Comment by riddick4u** [comment]
@compulim 

Thanks for your reply.

My understanding is as follows based on your comments:

1. DirectLineJSRouter will be responsible for both direct line channels communication.
2.  For Bot B we already have some callback methods where we receiving some events, so I believe we can consume those events in  DirectLineJSRouter methods?

According to the production grade and prototype timeline, it seems there is a lot of work involved. So my question is that any workaround other than the solution mentioned by you for injecting the Bot B messages in Bot A window which is a higher priority as compared to step 2. I have tried to update the virtual dom element like this(See below code), but it seems this is not working as expected and not rendering other messages like Hero card etc.

 // Called when the bot sent a message.
        function messageCallback(activity) {

            if (activity.from.id == "xxx" && !executeFinSupportBotFlow) {
                var el = '<div class="wc-message-wrapper list" data-activity-id="' + 10222 + '"><div class="wc-message wc-message-from-bot"><div class="wc-message-content"><svg class="wc-message-callout"><path class="point-left" d="m0,6 l6 6 v-12 z"></path><path class="point-right" d="m6,6 l-6 6 v-12 z"></path></svg><div><span class="format-plain"><span>' + activity.text + '<br></span></span></div></div></div><div class="wc-message wc-message-from-bot"><span>'+activity.from.id+'</span></div></div>';
                var textGroup = document.querySelector('.wc-message-group-content')
                textGroup.innerHTML = el + textGroup.innerHTML;
            }
            console.log("messageCallback:" + JSON.stringify(activity));
        }

Please let me know if there is any reliable and not hacky solution for this.  If you think the solution which you provided me is the one then please let me know if you can help me or provide any pointers to build this prototype. Also, how can we consume DirectLineJSRouter along with botchat.js on our web page?

**Comment by compulim** [comment]
You can't touch the DOM because it is maintained by React, it will just get reverted from time to time.

How about:
- Aggregation: use `store.dispatch({ type: 'DIRECT_LINE/INCOMING_ACTIVITY', payload: { activity } })`
- Routing outgoing activity: use Redux middleware to intercept actions of type `DIRECT_LINE/POST_ACTIVITY`, and then manually route it to bot B

But in this approach, it is more prone to bugs because the lack of isolation layers. You are paying smaller upfront (saving 1-2 weeks), but greater chores from time to time (probably > 2 weeks).

**Comment by riddick82** [comment]
@compulim

I have tried your suggested approach but could not make it work properly and sometimes it is giving me the error.

So I have decided DirectLineJSRouter approach as you mentioned earlier. Can you please help me into this for the pointer for start or to work on this POC, so that I can achieve the desired output.

Thanks for all your help.

**Comment by riddick82** [comment]
@compulim 
Can you please help me into this for the pointer for start or to work on this POC related to DirectLineJSRouter solution, so that I can achieve the desired output.

Appreciate your help.

**Comment by cwhitten** [comment]
We don't support client side Bot to Bot interactions at this time. Your mileage may vary when attempting this type of interaction.
