### ISSUE TITLE
Directline Issue: Botchat is not defined: v3

### ISSUE THREAD

**Issue by abhishekkant** [Microsoft/BotFramework-WebChat#1281]
Since today, all my bots are coming out empty. All the styling elements are also missing. 

In the browser console, I can see the error:  Botchat is not defined. This error happens on the line where the BotChat is initialized: 
`const botConnection = new BotChat.DirectLine({})`

My bot is developed in .NET v3, hosted in Azure and using Directline.

When testing from the Azure "Test in Webchat" or if embedding <iframe>, the bot is working fine.

**Comment by compulim** [comment]
When we deploy the new Web Chat v4 few hours ago, we deployed to https://cdn.botframework.com/botframework-webchat/latest/, it include 4 files, `botchat.js`, `botchat-es5.js`, `botchat-minimal.js`, and `stats.html`.

For sites that use Web Chat via CDN, if they are configured to use `/latest/botchat*.js`, they will be using new v4 bits.

Since Web Chat v4 use a new API `window.WebChat.renderWebChat()` and it is a breaking change. JavaScript code that use the older `BotChat.App()` API will not work in v4.

We rolled back the v4 deployment to CDN about an hour ago (around 00:15 PST). The issue is now mitigated.

If you prefer to use Web Chat v3, you don't need to update any code on your site, please continue to use `/latest/botchat*.js`. We will not remove this CDN bundle. And we currently do not have a plan to automatically migrate sites from Web Chat v3 to v4. One main reason is Web Chat v4 is not using CSS stylesheet for stying.

In Web Chat v4, Instead of using the bundle name `botchat*.js`, We are changing the bundle name to `webchat*.js`, so it will not conflict with Web Chat v3. If you want to use Web Chat v4, please refer to [this sample](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/full-bundle) to get started. Note, the sample is currently pointing to `botchat*.js`, it will be updated shortly.

The new Web Chat v4 CDN bundle with updated bundle name (`webchat*.js`) will be deployed again tomorrow, roughly 8-16 hours later.

Sorry for any inconveniences caused.

**Comment by abhishekkant** [comment]
Thanks for sorting it out.

**Comment by shuninghuang** [comment]
I am confused.

> if they are configured to use /latest/botchat*.js, they will be using new v4 bits
> If you prefer to use Web Chat v3, you don't need to update any code on your site, please continue to use /latest/botchat*.js.

 I should not use /latest/botchat*.js if I prefer to use v3, is that right?
