### ISSUE TITLE
Speak audio is interupted when second message arrives

### ISSUE THREAD

**Issue by williamw2** [Microsoft/BotFramework-WebChat#1320]
When a bot sends multiple messages with a Speak value the client will no longer finishing playing the text-to-speech audio before starting the second message. Instead the first message is cut off when the second arrives.
Using master/webchat.js with Bing Text to Speech service. Happens in Chrome and Edge.
Previous versions of webchat would finishing playing the first message before starting the second.

**Comment by compulim** [comment]
Working on it while we are baking the new W3C adapter for Unified Speech SDK (which support Custom Speech). Bing Speech will be deprecated by Cognitive Services team in 2019 October.

Expect a drop, private or public, in mid-December for the new SDK. Few reasons we might not able to go public: not enough testing on Web Chat, Cognitive Services did not ship their SDK in NPM by this date.

We are not sure if this bug is inside the existing adapter or not. We will figure it out while developing the new adapter. In case if it is not, we will have it fixed in Web Chat, expect sooner than 12/15.

**Comment by compulim** [comment]
Will be fixed in #1442.

The main culprit: the adapter does not set `speaking` property to `true`/`false`. Fixed the adapter code and bumped the version in this PR will get it fixed.
