### ISSUE TITLE
Markdown render texts in single paragraph into two lines

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#1429]
Type `echo "Same line.\nSame line. \n2nd line.\n\r3rd line."` in MockBot. It shows:

![image](https://user-images.githubusercontent.com/1622400/49403216-fce92a80-f700-11e8-9905-cd169985fb22.png)

Instead, both "Same line." should lies on the same line. When trying out with CommonMark and Markdown-It without Web Chat, the result is correct.

![image](https://user-images.githubusercontent.com/1622400/49403233-0d99a080-f701-11e8-837b-592d3eb8b099.png)

But in Web Chat, it renders like:

![image](https://user-images.githubusercontent.com/1622400/49403263-230eca80-f701-11e8-820b-d62b0d9fbe72.png)

**Comment by tdurnford** [comment]
Changing the Markdown-it `breaks` option from true to false in [renderMarkDown](https://github.com/microsoft/BotFramework-WebChat/blob/e7d93f402fa261d26500e4681a2ef5a92740c339/packages/bundle/src/renderMarkdown.js#L48) resolves the issue, but you need to add two spaces before a newline character if you want a break line tag on the second line. In the example above, it looks like there is only one space before the newline character, but I'm not exactly sure since Web Chat is trimming the extra white space when it displays the activity. If you, @compulim, can clarify what the expected behavior should be, I would appreciate it. 

`echo "Same line.\nSame line.  \n2nd line.\n\r3rd line."`

![image](https://user-images.githubusercontent.com/17039790/57731616-eb149780-764f-11e9-9cf2-6b64f8b6ddba.png)
