### ISSUE TITLE
Put the tittle

### ISSUE THREAD

**Issue by Sagarpaudel8** [Microsoft/BotFramework-WebChat#1452]
how can i add the title in the top, like it has chat when i use the iframe and when i put the web chat control and type the message there is no scroll line,instead the web page keeps extending when i type more messages.

**Comment by compulim** [comment]
You will need to explicitly set a height for Web Chat component, otherwise, it will increase its height as more activities came in.

For page title, please add a `<div>` before Web Chat. The reason why we moved page title out of Web Chat is because title bar branding varies from apps to apps (logo, links, close button, minimize button, etc). To make it easier to brand, we moved the title bar out of Web Chat, so the user can build the title bar the way they want it.
