### ISSUE TITLE
Web Chat unusable in Edge due to botchat.js errors

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/BotFramework-WebChat#1485]
Trying to embed the webchat iframe (per usage instructions on Azure Bot Service channel page) and, only in Edge, I'm getting

![image](https://user-images.githubusercontent.com/20270743/49835991-eae93680-fd55-11e8-8aae-e3be0497faa8.png)

which prohibits the "send" button from activating so I'm unable to chat at all with my bot. If I load the same page in a Chromium-based browser, webchat works as expected.

**Comment by corinagum** [comment]
This is a known issue in v3. The v3 workaround is to make sure the bot does not hide Web Chat on load, or use the visibility tag to hide the content while loading.
You can also upgrade to v4, which would mean not using the Azure Bot Service embed, and instead hosting Web Chat. You can take a look at our [samples](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples) to learn more about migration and hosting.

**Comment by brandonh-msft** [comment]
I'm not sure I follow. This is a v4 bot, and I used the Azure Bot Service's `Channels` area to get the embed code... this should work as v4 is GA, no?

**Comment by corinagum** [comment]
@brandonh-msft Sorry for the confusion - there are two 'v3's and 'v4's when referring to bots creating with the Bot Framework SDK and using Web Chat.

It sounds like you are using a v4 version of BotFramework SDK on Azure Bot Service, meaning your code is using the latest SDK version released at Ignite this year. At the same time, there was a release of v4 of Web Chat. However, the embed code provided on ABS is still using the v3 version of Web Chat, meaning that your bot uses v4 of Bot Framework, but v3 of Web Chat. 

Updating Web Chat within Azure Bot Service (so that the embed code is using v4 of Web Chat) is very high on our priority list, and we should have a better idea of when that update will be this week or next.

In the meantime, feel free to peruse our samples for guidance on how to use Web Chat without the embed code. Essentially you'll need to use the latest CDN, and our full-bundle sample is a great starting place for hosting your own Web Chat. I'm also happy to help with specific questions if needed.

**Comment by ovishesh** [comment]
> Updating Web Chat within Azure Bot Service (so that the embed code is using v4 of Web Chat) is very high on our priority list, and we should have a better idea of when that update will be this week or next.

@corinagum - is there an issue that is tracking this bug?

**Comment by corinagum** [comment]
@ovishesh There is not. I will update this thread if/when that changes. :)

**Comment by corinagum** [comment]
@ovishesh My apologies! We are tracking this issue on https://github.com/Microsoft/BotFramework-WebChat/issues/1086.
