### ISSUE TITLE
Webchat not rendering in ie browser

### ISSUE THREAD

**Issue by hemachowdary** [Microsoft/BotFramework-WebChat#1489]
Hi, 
I have a developed a bot using botbuilder sdk4 and nodejs. I am using directline channel for integrating bot with my web application. Bot is rendering and working as expected in chrome but not in IE. After tweaking so many posts i noticed that to make it work in IE browser webchat-es5.js  has to be used. I nowhere find the link to that js file. can anyone help on this.  My Client is more keen on rendering the bot in IE. Adding my code for reference. 

```
<!DOCTYPE html>
<html>
  <body>
    <div id="webchat"></div>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    <script>
      window.WebChat.renderWebChat({
        directLine: window.WebChat.createDirectLine({ token: 'YOUR_BOT_SECRET' }),
        userID: 'YOUR_USER_ID'
      }, document.getElementById('webchat'));
    </script>
  </body>
</html>
```

**Comment by compulim** [comment]
You will need to use the ES5 bundle, instead of full bundle. I.e. change from `webchat.js` to `webchat-es5.js`.

We offer 3 favors. ES5 is the bundle for IE11.

|                                                                                                                      | Minimal | Full | Full with ES5 polyfills |
| -------------------------------------------------------------------------------------------------------------------- | ------- | ---- | ----------------------- |
| [DirectLineJS](https://npmjs.com/package/botframework-directlinejs)                                                  | Yes     | Yes  | Yes                     |
| [Web Speech API from browser](https://azure.microsoft.com/en-us/services/cognitive-services/speech/)                 | Yes     | Yes  | Yes                     |
| [Adaptive Cards](https://adaptivecards.io/)                                                                          |         | Yes  | Yes                     |
| [Cognitive Services Bing Speech](https://azure.microsoft.com/en-us/services/cognitive-services/speech/)              |         | Yes  | Yes                     |
| [Cognitive Services Speech Services](https://azure.microsoft.com/en-us/services/cognitive-services/speech-services/) |         | Yes  | Yes                     |
| [Markdown-It](https://npmjs.com/package/markdown-it/)                                                                |         | Yes  | Yes                     |
| [`sanitize-html`](https://npmjs.com/package/sanitize-html)                                                           |         | Yes  | Yes                     |
| ES5 Polyfills (for IE11)                                                                                             |         |      | Yes                     |

**Comment by hemachowdary** [comment]
@compulim  can you please share the cdn link to **webchat-es5.js** that i have to use instead of  **webchat.js** inorder to make it work in IE browser

**Comment by compulim** [comment]
The link for latest ES5 bundle is https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js.

Please note that this link is targeting "latest" version, which will change from time to time (currently `4.2.0`). If you relies on Web Chat API for customization, I would suggest you to lock down on a specific version of Web Chat on production, and use "latest" for development.

Currently, we are on `4.2.0`. The link to ES5 bundle of `4.2.0` is https://cdn.botframework.com/botframework-webchat/4.2.0/webchat-es5.js.

**Comment by hemachowdary** [comment]
thanks for that @compulim . It is working now and I am referring to 4.1.0 version. https://cdn.botframework.com/botframework-webchat/4.1.0/webchat-es5.js.
