### ISSUE TITLE
Specify language for Cognitive Services Speech Services

### ISSUE THREAD

**Issue by tao1** [Microsoft/BotFramework-WebChat#1529]
Hello,

Cognitive Services Speech Services sample does not show how to explicitly specify language. It seems it uses preferred language of browser.
For example if you open https://bbox.ai web page in Firefox with french preferred language.
It leads to failing request to https://westeurope.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=fr&format=detailed
Notice language parameter is fr instead of fr-FR.
To workaround this problem, I change my browser preferred language to fr-fr, but notice french firefox users will have fr preferred language instead of fr-fr by default.

To conclude, it would be nice to specify language to `createCognitiveServicesSpeechServicesPonyfillFactory()` function.
And it would be great if speech.microsoft.com accepts language parameter in 2 letter format.

Thanks for your great WebChat component ! Kind regards

Laurent.

**Comment by compulim** [comment]
@tao1 we are aware of Web Chat not sending the language identifier (either fr or fr-FR) to Cognitive Services. And the Speech Services component just pick up the language of the browser.

For example, in an English (`en-US`) browser, we visit a page with Web Chat set to French (`fr-FR`). When we call Speech Services, since we didn't pass `fr-FR`, we are calling the service using `en-US`.

Could you do me a favor to check if this is the root cause in your case?

Thanks!

**Comment by gabog** [comment]
I agree with the request, in most localized sites, the user preferences take preference over the browser settings, the language should be independent of that. I am working with a customer that needs this and this is blocking us from upgrading to the latest webchat so we can use Azure Speech Services. Bing speech is discontinued and we can't move forward until we have parity with the previous webchat.

**Comment by compulim** [comment]
https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/Composer.js#L168

```
this.createWebSpeechPonyfill = memoize((webSpeechPonyfillFactory, referenceGrammarID) => webSpeechPonyfillFactory && webSpeechPonyfillFactory({ referenceGrammarID }));
```

to

```
this.createWebSpeechPonyfill = memoize((language, webSpeechPonyfillFactory, referenceGrammarID) => {
  if (webSpeechPonyfillFactory) {
    const webSpeechPonyfill = webSpeechPonyfillFactory({ referenceGrammarID }));

    webSpeechPonyfill.language = language;

    return webSpeechPonyfill;
  }
```

**Comment by corinagum** [comment]
1. Web Chat needs to pass language to Web Speech API
1. Include link in comments of #1823 supported languages for Cognitive Speech

**Comment by compulim** [comment]
- Verify if speech recognition is working for non-English locale on an English browser
   - Use `ja-JP` and click microphone button, see if it can recognize your voice in Japanese or not
- Just language prop alone is not sufficient for text-to-speech in other languages, we need to add a new prop. This is because voice can be male/female and preferences
   - `<ReactWebChat>` and `<Composer>` should take up a new prop named `onSelectVoice((voices: SpeechSynthesisVoice[]) => voice: SpeechSynthesisVoice)`
      - To make it better, `onSelectVoice((voices: SpeechSynthesisVoice[], activity: Activity) => voice: SpeechSynthesisVoice)`
   - Let me know when this is done, then we continue to work on the mechanism to select the voice

**Comment by tdurnford** [comment]
Currently, it looks like you can specify the speech-to-text voice by passing in locale as a prop to Web Chat. The [selectVoice](https://github.com/Microsoft/BotFramework-WebChat/blob/8c8e2cccc572b11f3585682205dde0166d87e4d7/packages/component/src/Activity/Speak.js#L22) method will find the correct voice based on the language preference and use that voice to speak the message from the bot.

```js
window.WebChat.renderWebChat({
    directLine: window.WebChat.createDirectLine({ token }),
    webSpeechPonyfillFactory,
    locale: 'fr-FR',
    store
}, document.getElementById('webchat'));
```

Note, you can also select the voice from the bot by setting the locale property in the activity being sent to Web Chat. 

```js
await context.sendActivity({ 
    text: 'Hello World', 
    locale: 'fr-FR'', 
    channelData: { 
        speak: 'hello world' 
    }
});
```
