### ISSUE TITLE
Web Chat UI customization

### ISSUE THREAD

**Issue by deva96** [Microsoft/BotFramework-WebChat#1551]
Hi,
I want some features I am listing it out please help me out
1. I want user to choose font size and family by his/her convenient,
    How to add buttons in the top of the chat header 
2. When user is typing in web chat he should get some suggestions as google searching
3.Clear chat option - chat should be restarted

I need some suggestions
Currently i am using web chat v4

**Comment by corinagum** [comment]
Hey @deva96, have you checked out our samples? We have a lot of great examples that can get you started on customization.
1.  [11.customization-redux-actions](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/11.customization-redux-actions)
1.  [12.customization-minimizable-web-chat](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/12.customization-minimizable-web-chat)
1. I don't believe we have a comparable sample for this one. @compulim, do you have input?
1. [Clearing Web Chat](https://github.com/Microsoft/BotFramework-WebChat/issues/1505)

Please note that your requests are of the "How do I..." variety. If you need help with your project, [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework) is a great place to get peer input.

**Comment by compulim** [comment]
### Point 1

I think we missed a style options to customize font today. We can do it via style sets today.

@corinagum do you think we should add a sample for this? While we are coding the sample, we will add the "style options to customize fonts" into production code.

### Point 2

We omitted the chat title in Web Chat v4 (compare to v3) because:

1. It is one of the most popular customization
2. It can be easily done in HTML by appending HTML code just before Web Chat DOM element
3. It is more intuitive to do it in plain HTML than "customizing" in Web Chat, feel over-engineered if we do it that way

In this way, the user can customize the title as much as they want, for example, adding buttons to the chat title easily.

### Point 3

We want to add an "auto-complete box" sample and that would help this scenario (data feed from auto-complete box could be from Google.)

**Comment by corinagum** [comment]
@compulim 

Point 1: Sounds good. I've filed an issue here: https://github.com/Microsoft/BotFramework-WebChat/issues/1553

Point 3 can be tracked [here](https://github.com/Microsoft/BotFramework-WebChat/issues/476)
