### ISSUE TITLE
Customizing Carousel card(Adaptive card) in webchat v4 version

### ISSUE THREAD

**Issue by SushanthMandarthi** [Microsoft/BotFramework-WebChat#1592]
Hi,

I can see some of the divs created inbetween any components(for ex. between buttons there will be some spacing) which i need to eliminate as project requirements.
**Also i wanted to know whether we can customize the divs and its inline styles which are formed in "node modules" (ex. in carousel(adaptive) cards, divs without class names).**
Whether there is any way to append dynamic class names for the divs formed in "node modules".
It will be very helpful if anyone could help with these issues soon.

**Comment by compulim** [comment]
Today, Adaptive Cards are using inline style and the customizability is not great.

There are few options:
- AC@1.1.2 provide some class names so you can style thru it
   - We bumped to AC@1.1.2 in our latest dev build (#1558), not in production yet
   - The class names are pretty primitive so you might not able to do a lot of styling over there
- Render your own card
   - Instead of sending Adaptive Cards, you can send a custom attachment and you write a new renderer for it
   - Pro: you will have lots of freedom to style, and the card is also interactive
   - Sample here, https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/10.customization-card-components/index.html

**Comment by SATACHAKRA** [comment]
The link u gave doesn't exist
