### ISSUE TITLE
Hero card styling

### ISSUE THREAD

**Issue by erkkil** [Microsoft/BotFramework-WebChat#1594]
Hi,

I would like to customize herocard styling including button styles. 
How this can be done using stylesets?

**Comment by compulim** [comment]
Today, we convert hero card into Adaptive Cards and render it thru Adaptive Cards. So in order to style, you will need to style it thru Adaptive Cards host config.

Unfortunately, the styling is pretty limited today. We have a work item #1259 to render all rich cards (hero card, thumbnail cards, etc) using HTML instead of Adaptive Cards.

So when that work item is done, you will have more styling and customization options.

In the mean time, if styling has high importance, you can consider render the hero card by yourself. It is supported and you can find sample here, https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/10.customization-card-components/index.html.

**Comment by erkkil** [comment]
Ok I will use the option to render hero card by myself.
Thanks
