### ISSUE TITLE
Localization not working for prompt with 2 items on web chat

### ISSUE THREAD

**Issue by bertique** [Microsoft/BotFramework-WebChat#162]
[Moving from [Microsoft/BotBuilder](https://github.com/Microsoft/BotBuilder/issues/1634)]

I'm writing a bot using the Node sdk with a web widget front end.

For prompts with two choices, the web client doesn't properly display the options. It works for items with more options

code:
builder.Prompts.choice(session, "Do you like pizza?", ["Yes, thank you","No, I hate it"]);

web widget:
Do you like pizza? (1. Yes, thank youlist_or2. No, I hate it)

It looks like it's not pulling the localized string for 'or'

**Comment by dandriscoll** [comment]
Are you using the preview version of the web chat control?

Localization is not done in the channel, so that part of the bug may be better handled in BotBuilder.

**Comment by bertique** [comment]
I believe it's the regular version of the web chat control.

Okay, I will re-open the bug there. It's weird that it works in the emulator, but not in the web chat control

**Comment by dandriscoll** [comment]
The regular (old) version of the chat control will render choice prompts down to text, but the "list_or" part is entirely Botbuilder.

The preview (new) version of the chat control renders it as buttons, like the emulator*. The issue isn't present here because the text isn't used.
*fun fact, the emulator _is_ the chat control.

**Comment by bertique** [comment]
That's even better. How can I get the preview version?

**Comment by bertique** [comment]
Never mind, I found it. Thanks much!
