### ISSUE TITLE
pollingInterval and conversationId update in createDirectline.js

### ISSUE THREAD

**Issue by sanoorvishwa** [Microsoft/BotFramework-WebChat#1652]
@compulim We have requirement to update the directline polling interval when the bot is minimized and maximized. Could you please update the createDirectline.js interface for the same? Any reason why these are omitted in the initial release though the directline supports it?

Thanks,
Vishwa

**Comment by neetu-das** [comment]
I think fix for #1613 has added 'conversationId' in createDirectline.js interface. Similarly pollingInterval can also be added

**Comment by compulim** [comment]
> @neetu-das thanks for the reference. You have keen eyes. 👀 

@sanoorvishwa Because we try to whitelist stuff in, instead of blacklist stuff out. 😉

And also, today, what we can pass to DLJS is also quite arbitrary IMO. We need to revisit reconnecting story in DirectLineJS to make sure it work as expected (what I heard from people is that it is not quite working.)

Please feel free to file a PR for this fix (`pollingInterval`). I can help you work on CHANGELOG.md and other chores. 😉

**Comment by sanoorvishwa** [comment]
Thank @neetu-das and @compulim . Both pollingInterval and conversationId are now available in createDirectline.js constructor.

Thanks and closing this issue.
