### ISSUE TITLE
Oauth signin card - 400 Error on getsessionId 

### ISSUE THREAD

**Issue by JasmeetVirdi** [Microsoft/BotFramework-WebChat#1656]
I am using Oauth Signin card ,which is render in webchat channel using iframe.
When i click on signin button i get 400(bad request) error as follows:
![image](https://user-images.githubusercontent.com/13176977/51901708-522e7900-23de-11e9-9112-38b0087e07ca.png)

The detailed message is
```
{
 "error": {
   "code": "BadArgument",
   "message": "Missing token or secret"
 }
}
```
I am using AAD1 sample code from github.
I am not sure what is causing this?Probably some issue in the code?
it is working fine through local

**Comment by corinagum** [comment]
Hi @JasmeetVirdi, what sample are you using? Is this a Bot Framework provided sample?

**Comment by JasmeetVirdi** [comment]
Hello @corinagum i am using the sample code provided at below github link:
 https://github.com/Microsoft/BotBuilder-V3/tree/master/CSharp/Samples/AadV1Bot

**Comment by stevkan** [comment]
Hi @JasmeetVirdi, can you verify for me that you are using the iframe option presented in the Channels => Web Chat control? I ask as both the Test in Web Chat and iframe version of Web Chat do not support the OAuth card. If trying to display, you would see this:

![image](https://user-images.githubusercontent.com/18403946/52096789-082fc980-257d-11e9-9bde-2c1c34ac8ec0.png)

As for the getsessionid error you are receiving, this is tied to the need to set the bot's host page as a trusted origin. Until recently, this wasn't supported via iframe webchat. Additionally, as mentioned in [this](https://blog.botframework.com/2018/09/01/using-webchat-with-azure-bot-services-authentication/) blog under Step 4,

> Using an IFRAME is not a supported way of driving the authentication flow using OAuthCards because you cannot set a trusted origin and you cannot set user ids.

However, trusted origin can now be set under the Direct Line channel control for your bot. That being said, using the iframe option is going to limit you in the long run as there are a number of other features that have been introduced into the web chat ecosystem (via CDN or NPM libraries) that are not supported via iframe. Iframe will likely remain behind due to breaking changes that would be introduced to customers who currently rely on iframe as it currently exists.

Therefore, my strong suggestion is you navigate away from using the iframe option and instead use the CDN or NPM option to embed your chatbot into a web page.

Hope of help!

**Comment by JasmeetVirdi** [comment]
Hi @stevkan ,i am using IE v11 as my browser. I tried using CDN webchat but ended up with some js errors and the Oauth card dint work for IE.
So i went ahead with the solution provided by @compulim in issue #1106 according to which it should have worked and it did i.e. Oauth card is visible (Perhaps the solution is deprecated)
![image](https://user-images.githubusercontent.com/13176977/52106775-ecc6cc00-2619-11e9-98a3-91b81f1de68c.png)
The error on getsessionId is the blocking step.I will try as per your suggestion for trusted origin and use of CDN.
Bt it is to be noted that using CDN results in IE errors.So browser limitation is there.
That being said,I agree with you that CDN or NPM is better anyways and should be used.

**Comment by corinagum** [comment]
@JasmeetVirdi please share the errors you are receiving on IE and we can take a look at them. If there are User-Agent alerts that you are recieving, this is a known issue that should be resolved in master bits as soon as possible, and released with 4.3 to latest.

**Comment by JasmeetVirdi** [comment]
The errors on console are below
![image](https://user-images.githubusercontent.com/13176977/52198748-e179d780-2889-11e9-9c42-e7366984bfa4.png)

I used to below code:
<!DOCTYPE html>
<html>
  <body>
    <div id="webchat" role="main"></div>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-minimal.js"></script>
    <script>
      window.WebChat.renderWebChat({
        directLine: window.WebChat.createDirectLine({ token: 'YOUR_BOT_SECRET' }),
        userID: 'YOUR_USER_ID'
      }, document.getElementById('webchat'));
    </script>
  </body>
</html>

where YOUR_BOT_SECRET'  = web secret key from azure portal

**Comment by corinagum** [comment]
@JasmeetVirdi [Promises are not natively supported in IE11](https://caniuse.com/#search=Promise), so you will need to use the es5 ponyfill in order to support Web Chat on IE11 via the CDN. From your last comment it looks like you are using the minimal cdn. Please use the [es5 sample](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/01.b.getting-started-es5-bundle) as reference. :)
