### ISSUE TITLE
Modification of hero card using HTML

### ISSUE THREAD

**Issue by vinayak99999** [Microsoft/BotFramework-WebChat#1687]
I have added HTML code and custom CSS for the same inside text element of hero card see below code for reference. I have added buttons also. So the issue is how do I trigger button to certain intent or dialog using onclick function.(what I have done below is not right...I want to know if its possible).
Sorry I cannot paste code as it directly renders HTML instead of code.
Is it possible to? Any help or suggestion will be appreciated. Thank you.
![image](https://user-images.githubusercontent.com/42091886/52161827-41894600-26f1-11e9-918e-2f22c6eb193e.png)

This is the current output

![image](https://user-images.githubusercontent.com/42091886/52161871-d724d580-26f1-11e9-86a1-5ff58a34eff3.png)

**Comment by stevengum** [comment]
@vinayak99999 if you use triple-back ticks and js it should render properly, e.g:

> \```js
> bot.dialog('...');
> \```

and the formatting in use: 

```js
bot.dialog('...');
```

**Comment by corinagum** [comment]
Hi @vinayak99999 Please take a look at the [rich card attachment docs](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-rich-cards?view=azure-bot-service-3.0) for an example of how Hero Cards can be implemented. 

Because you are rendering your own buttons in your example, these buttons are not hooked up to Web Chat to perform any action. If you want to continue using Hero Cards, I recommend taking a look at the link above and seeing how you can attach buttons to the card with CardActions.

If styling the card is very important for your implementation, I recommend creating your own card, rather than using Hero Cards. The sample [10.a.customization-card-components](https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/10.a.customization-card-components/) shows you how you can build your own components, which will give you the flexibility to style it as needed. Please note that this sample is built for **v4 of Web Chat**. It looks like you are using v3 of the Bot Framework SDK, but regardless of whether your bot is on v3 or v4 of the SDK, you are able to use v4 of Web Chat without problems. 

Hope that helps!
