### ISSUE TITLE
Scroll Issue on Firefox

### ISSUE THREAD

**Issue by dalvirsaini** [Microsoft/BotFramework-WebChat#1697]
I am facing scroll issue on Firefox and mobile. here i shared screen shot of chrome and Firefox. for chrome its fine but for Firefox its not working.

Here is example of Chrome. here scroll is working: 
![image](https://user-images.githubusercontent.com/5260369/52269428-0b9fc800-2964-11e9-9c83-985767e99839.png)

Here is Example of Firefox where scroll not working
![image](https://user-images.githubusercontent.com/5260369/52269615-941e6880-2964-11e9-9bb5-7c7e4f615ef5.png)

Thanks

**Comment by corinagum** [comment]
Hi @dalvirsaini, looking at your screencaps, it looks like the issue you are reporting is the lack of scrollbar in the second one. Is this correct? I tested our Mock Bot on Firefox (v65) just now and didn't see the same issue. 

I have a few questions, if anyone who is repro-ing this issue could add their information that would be great.

1. It looks like this is v4 of Web Chat, is that correct? Are you using the CDN or NPM package?
1. What version of Firefox are you using? 
1. Is your bot share-able to the public where I can take a quick look?
1. Does the scrollbar never appear? Or disappear after a particular action?
1. It doesn't look like you've added any styling modifications to the scrollbar, is this correct?
1. Does this issue occur when you test out Mock Bot? Please use this link to test: https://microsoft.github.io/BotFramework-WebChat/06.a.cognitive-services-bing-speech-js/

**Comment by keshavnagpal** [comment]
Hi @corinagum , I was facing a similar scrolling issue. where when i try to scroll up, it is not letting me and automatically scrolling at the bottom of the chat.
This keeps occurring on touch screen laptops/pc
when i move the same window to a non-touch monitor it works fine.
Please inform me when this is fixed.
Thanks

**Comment by corinagum** [comment]
@compulim I don't have a touch screen laptop, could you investigate this?

**Comment by nicholasamiller** [comment]
I am also seeing this issue, with Chrome, with MockBot, using this:

 https://microsoft.github.io/BotFramework-WebChat/06.a.cognitive-services-bing-speech-js/

See vid:

https://1drv.ms/u/s!AqLTBxPBk_dXhux7ksIgD45D6LDu-g

Not touch screen.

I am also seeing the issue in my customised WebChat.

Is there some dependency I should revert to avoid this?

**Comment by keshavnagpal** [comment]
Thanks @nicholasamiller  for posting the video
I'm seeing exactly same issue.

**Comment by corinagum** [comment]
@nicholasamiller Thank you very much! Let me look into this and get back to you guys.

**Comment by compulim** [comment]
Looking into this too. The bug looks very legit. But I am struggling trying to repro.

Trying combination of a few things:
- Hi-DPI on/off
- Zoom ratio 100% vs 150%
- Firefox
- Mouse dragging scroll handler

Will be great if someone can give me some tips.

**Comment by compulim** [comment]
I kind of understand the problem.

Technically speaking:

- "scroll to bottom" means, "if I am sticky, and I am not at the bottom, scroll to bottom"
- "I am no longer sticky" means,
   - "scroll event emitted due to user gesture, and the `scrollTop` value is no longer at bottom"
- "I become sticky" means,
   - "scroll event emitted, `scrollTop` value changed to the bottom value"

We prefer this behavior because we allow the content to be expanded, without using any hints from HTML DOM. We tried alternative approach in 4.2, which we explicitly tell the scrollable panel we have expanded, but the UX doesn't go well (sometimes Web Chat don't scroll to bottom).

When the user scroll to top, the following things will happen:

1. `scrollTop` set to `0`
2. Fire `scroll` event

For every 150ms, we check if we are at the bottom. If no and we are sticky, we will scroll to bottom.

But in Firefox, the check is being inserted between 1 and 2. That means, the check will see "I am not at the bottom, but I am still sticky, I need to scroll to bottom." Thus, we are seeing this behavior.

**Comment by nicholasamiller** [comment]
Also in Chrome - see my vid.

**Comment by compulim** [comment]
Need some community help here because I cannot reliably repro on my box (repro chance = 1-in-50). I don't know if my fix really works or not.

@dalvirsaini @keshavnagpal  @nicholasamiller could you guys help me by trying out the following pages?

- https://webchattest.blob.core.windows.net/scroll-test/index.html should have the fix
- https://webchattest.blob.core.windows.net/scroll-test/repro.html should _not_ have the fix (control experiment)

Many thanks!

**Comment by keshavnagpal** [comment]
@compulim 
I tried your solution it seems to work on my machine
and i was able to reproduce the issue several times in the same machine on repro.html

I went ahead and copied your webchat.js file and used in my solution, it fixed the issue 
(although when trying to scroll while new messages are coming it's not as smooth)

I need to use webchat-es5.js
Can you try the same fix in webchat-es5 as well?

Thanks
