### ISSUE TITLE
Where are the parameters for renderWebChat and createDirectLine

### ISSUE THREAD

**Issue by gabog** [Microsoft/BotFramework-WebChat#1721]
I am hosting webchat using javascript, where can I find documentation on the parameters for "createDirectLine" and "renderWebChat" so I know what can pass? 

Are the methods and parameters supported by the WebChat object documented somewhere? (I am also interested in createCognitiveServicesSpeechServicesPonyfillFactory.

**Comment by corinagum** [comment]
Hi @gabog, unfortunately we don't have documentation with these kind of details at the moment. This question has been discussed over at #1654. We're keeping that one open for now since we're still having discussions about how to address documentation with the team. 

Right now you can look at the [`createDirectLine.js`](https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/bundle/src/createDirectLine.js) and [`Composer.js`](https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/Composer.js#L378). Hope that helps!

**Comment by gabog** [comment]
Thanks. Having a page documenting the parameters and other constants would be great.
