### ISSUE TITLE
Opening message

### ISSUE THREAD

**Issue by digitallawyer** [Microsoft/BotFramework-WebChat#173]
In the old webchat, a message would be displayed saying "Say hi if you would like to chat".

Once upgraded to the newer version of webchat, this message no longer displays. How does one now set an opening message to be displayed to the user?

**Comment by preshi** [comment]
The message you were referring to is actually a static message present in old webchat component.I hope your question is to "How you can get it in the new web chat?".To achieve the same in new webchat. You need to modify the .tsx/ts files of the webchat control.If my analysis is not wrong you can add the <div></div>(after line 138) in the Chat.tsx file compile it (as in here https://github.com/Microsoft/BotFramework-WebChat#how-do-i-customize-it).Run it,

**Comment by digitallawyer** [comment]
Thanks @preshi! My question is indeed "How do I display the opening message in the new web chat?"

I'm currently rendering the webchat using the iframe method, without further customization. I'll dig further to see if any customization is possible there, but I assume that may not be the case. Thank you for the pointer!

**Comment by billba** [comment]
Feedback from most developers was that they preferred to have their bots give their own custom, localized welcome message rather a generic hard-coded message from WebChat. Since WebChat is often just one of many supported channels, and other channels do not present a hard-coded welcome message, it made sense to remove it entirely.

For samples on adding a welcome message in your bot, examine "Get Members of a Conversation" in [BotBuilder Samples](https://github.com/Microsoft/BotBuilder-Samples).
