### ISSUE TITLE
"Error: Conversation ended" when switching to another component from webchat/bot

### ISSUE THREAD

**Issue by r-meh** [Microsoft/BotFramework-WebChat#1737]
We are migrating our bot from v3 to v4 and encountered an issue where if I move from bot component to any other component in our angular app, below uncaught error is thrown by bot framework:

    ERROR Error: Uncaught (in promise): Error: conversation ended
    Error: conversation ended
        at Object.<anonymous> (webchat-es5.js:67)
        at n (webchat-es5.js:1)
        at Object.<anonymous> (webchat-es5.js:67)
        at n (webchat-es5.js:1)
        at Object.<anonymous> (webchat-es5.js:29)
        at n (webchat-es5.js:1)
        at Object.<anonymous> (webchat-es5.js:67)
        at n (webchat-es5.js:1)
        at Object.<anonymous> (webchat-es5.js:67)
        at n (webchat-es5.js:1)
 
We are currently using "https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js". This issue seems to have been fixed in master branch of webchat. I am not sure what PR has fixed it but would like to know when the master is expected to be deployed to latest production. Is there any place where I can track it? Thanks.

**Comment by corinagum** [comment]
Hi @r-meh, glad the fix is available to you on `/master/` bits. Unfortunately we don't have a feed for announcing our releases yet. We have issue #1399 for tracking ideas on how to communicate releases with our customers. Please feel free to add ideas or your +1 over there. :)
Our 4.3 release should be publicly available early March. Please check back then!
