### ISSUE TITLE
New directline js update tries to render non message type activities

### ISSUE THREAD

**Issue by Dongata** [Microsoft/BotFramework-WebChat#1793]
Hello everyone, im having this message when i send a custom message type to our backend (passing thru directline)

![image](https://user-images.githubusercontent.com/7729931/53910864-b1158c80-4033-11e9-82c8-ffc36aa20b58.png)

## Steps to reproduce
1. Have a cdn base webchat
2. Use DirectLine to send a custom activity 
Result: Error appears and then the message from backend bot
Expected Result: Nothing but the response from the backend bot should render

## Code
```typescript
    var dl = (<any>window).WebChat.createDirectLine({ secret: 'MySecret c:' });

    (<any>window).WebChat.renderWebChat({
      directLine: dl,
      userID: this.userProvider.getUserId(),
      resize: 'detect'
    }, (<any>document).getElementById('bot'));

    dl.postActivity({
      from: {
        id: this.userProvider.getUserId(),
        name: this.userProvider.getUsername()
      },
      name: 'requestWelcomeDialog',
      type: 'requestWelcomeDialog',
      value: ''
    }).subscribe(function (id) {
      console.log('"trigger requestWelcomeDialog" sent');
    });
```

**Comment by compulim** [comment]
@Dongata sorry, but this is expected behavior.

For custom activities, we always recommend using activity type of `event` with a custom `name` and `value` property. This guarantee the behavior to works consistently across multiple channels.

You can find a list of activity types that are officially supported in this article, https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-activities?view=azure-bot-service-4.0.

For activities with unsupported type, like `requestWelcomeDialog` in your case, from what I heard from the channel team, the channel is not guaranteed to deliver them to its client (Direct Line and Web Chat).

To disable the warning prompt, you can follow [the sample here](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/09.customization-reaction-buttons/):

- Pass an additional `activityMiddleware` to Web Chat
- If `card.activity.type` is `requestWelcomeDialog`, return `false`
   - Else, pass it to the next middleware by `return next(card);`
