### ISSUE TITLE
 Text to Speech integrated with LUIS BOT does not voice out/playback in Safari browser on iOS/iPhone devices

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#1829]
Customer is facing problems using Speech API on a LUIS BOT where, Text to Speech/voice out/playback is not working in Safari browser on iOS devices, though it works on both Android and Windows clients. 
Here is a sample URL for testing which I have hosted.

Related to #995

**Comment by compulim** [comment]
Need more investigations.

- Go to https://compulim.github.io/web-speech-cognitive-services/ and try if text-to-speech is working on iOS or not.
   - If it is not, find out the issue in that repository
   - If yes, it could be related to "playing audio without an user interaction"
      - Prime the audio playback engine when the user click microphone button on Web Chat

**Comment by compulim** [comment]
The exception thrown at this line.

![image](https://user-images.githubusercontent.com/1622400/58120939-1c92e300-7bbb-11e9-9b06-5cd8291562b1.png)

![image](https://user-images.githubusercontent.com/1622400/58120911-0ab14000-7bbb-11e9-83c9-df4a952f36d1.png)

**Comment by compulim** [comment]
The core bug of this issue is because we asked the speech synthesizer to cancel if it cannot start within a second. The kill-and-retry logic was used to workaround a Chrome bug and it no longer repro today.

Since we are using Cognitive Services, it could take more than a second to download and start playing the MP3. Thus, it is not very reliable today.
