### ISSUE TITLE
Cognitive Speech Services sample throws a runtime error in Chrome 

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#1848]
I was unable to reproduce this issue in Edge or Firefox

Reproductions steps:
1. Navigate to [06.c.cognitive-services-speech-services-js](https://microsoft.github.io/BotFramework-WebChat/06.c.cognitive-services-speech-services-js/) in Chrome version 73.0.3683.86
1. Open console
1. Press microphone button and say 'Help'
1. Notice console errors regarding AudioNode, pasted below

![image](https://user-images.githubusercontent.com/14900841/55040412-71641400-4fe5-11e9-9953-5b288dea0786.png)

We are still investigating the cause of this bug. Please feel free to add a +1 and the details of your experience to this issue.

Notes:
- Does not repro with [speech web-browser sample](http://localhost:5000/samples/06.d.speech-web-browser/index.html).

**Comment by xiaolangxyz** [comment]
In my case, it is the error as the image below
![error](https://user-images.githubusercontent.com/40823365/55058470-61b10200-50af-11e9-80b1-a863cc01bce2.png)

**Comment by compulim** [comment]
@xiaolangxyz looks like your problem is related to #1823.

**Comment by compulim** [comment]
On the other hand, https://webchat-playground.azurewebsites.net/ works.

**Comment by compulim** [comment]
Maybe Chrome updated the error message.

![image](https://user-images.githubusercontent.com/1622400/58054997-3d066300-7b11-11e9-847f-a0adcbeb47a3.png)

```
Connecting nodes after the context has been closed is not useful.
```

**Comment by corinagum** [comment]
@compulim are we reassigning this one to you?

**Comment by compulim** [comment]
Took this now.

**Comment by compulim** [comment]
Today, we have a workaround for this particular Chrome bug:

1. Speak an utterance
2. Cancel in the midway
3. Speak another utterance

Expected: speaking is falsy, then turn to truthy, then receive "start" event, and audio is played
Actual: speaking is falsy, then turn to truthy (which is wrong), but receive no "start" event, and no audio is played

Our workaround is, if we did not receive "start" event within a second, we will cancel and restart, up to 2 times.

Since this workaround applies to both Chrome and non-Chrome (Cognitive Services), thus, if Cognitive Services took more than 1 second to fetch/decode the audio, we would think it is bugged and we restart it. Leading to some long text to fail synthesizing.

I tested Chrome 74 and Edge "Anaheim" 76 and seems this bug no longer repro. Will try move browsers and remove this workaround. And next time, we shouldn't applies a workaround too broad, we should limit the workaround by building a new polyfill instead.

I am using the HTML below, then repetitively click "Speak" and "Cancel" button.

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Speech</title>
  </head>
  <body>
    <button class="speak">Speak</button>
    <button class="cancel">Cancel</button>
    <p class="pending">Pending: <span class="value"></span></p>
    <p class="speaking">Speaking: <span class="value"></span></p>
    <script>
      document.querySelector('button.speak').addEventListener('click', () => {
        speechSynthesis.speak(new SpeechSynthesisUtterance('A quick brown fox jumped over the lazy dogs.'));
      });

      document.querySelector('button.cancel').addEventListener('click', () => {
        speechSynthesis.cancel();
      });

      setInterval(() => {
        document.querySelector('.pending > .value').innerHTML = speechSynthesis.pending + '';
        document.querySelector('.speaking > .value').innerHTML = speechSynthesis.speaking + '';
      }, 100);
    </script>
  </body>
</html>
```

**Comment by compulim** [comment]
In order to verify the fix:
1. Ask the bot to synthesize a very long text that took > 1s to download the MP3 file from Cognitive Services
2. Verify F12 that we don't see the "audio node is disconnected" error nomatter how long the text is

**Comment by corinagum** [comment]
Fix is verified in #2035. It will be officially released for 4.5 in July. If you need this fix immediately, please cherry-pick the above PR into a locally hosted version of Web Chat.

**Comment by alokraj68** [comment]
Hi, I am still getting this same issue in chrome 77.

Also, after this, the speech recognizer is not starting.

I am manually canceling the voice since I need to stop it once user presses a button, after that this issue is happening.

Is it a known bug?

**Comment by corinagum** [comment]
@alokraj68 Thank you for bringing this to our attention. I am going to file another issue since this appears to be a slightly different bug.  https://github.com/microsoft/BotFramework-WebChat/issues/2469
