### ISSUE TITLE
TypeError: webSpeechPonyfillFactory is not a function     at Composer.<anonymous> (Composer.js:168)

### ISSUE THREAD

**Issue by guptarajesh001** [Microsoft/BotFramework-WebChat#1854]
I am getting issue "react-dom-16-bundle_068bea613f5fe1903fe9fe89256cf26c.js:1 TypeError: webSpeechPonyfillFactory is not a function
    at Composer.<anonymous> (Composer.js:168)
    at Composer.result [as createWebSpeechPonyfill] (index.js:31)"

on implementation of speech in below React code, 

this.webSpeechPonyfillFactory = createCognitiveServicesSpeechServicesPonyfillFactory( { region: 'west us', subscripwesteuropetionKey: '6320c24xxxx', }, );

    const divStyle = {
      width: '100%',
      border: '2px solid pink'
    };
        return (
        <ReactWebChat  webSpeechPonyfillFactory= { this.webSpeechPonyfillFactory }
        className={ `${ className || '' } web-chat` }  styleOptions={wesstyleOptions}  userID={this.props.email} username= {this.props.userName} directLine={this.directLine} botAvatarInitials={'Bot'} botAvatarImage='https://docs.microsoft.com/en-us/azure/bot-service/v4sdk/media/logo_bot.svg?view=azure-bot-service-4.0'
          userAvatarInitials={this.props.email} userAvatarImage={this.props.photoUrl} resize="detect" locale="en-US"
        />
    );

**Comment by corinagum** [comment]
Hey @guptarajesh001, do you by chance intend `const webSpeechPonyFillFactory` instead of `this.webSpeechPonyFillFactory`? If you take a look at our [Cognitive Services Speech Services](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/06.c.cognitive-services-speech-services-js) sample, you need to declare the variable. (You'll also want to throw `await` in front of `createCognitiveServicesSpeechServicesPonyfillFactory` too.)
