### ISSUE TITLE
Customize Web Chat with Reaction Buttons does not work

### ISSUE THREAD

**Issue by Souvik04** [Microsoft/BotFramework-WebChat#1856]
Hi,

I am trying to get this sample. I have setup in my local and followed the steps mentioned here: https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/09.customization-reaction-buttons/ to set it up and run. I get below error in my localhost in Chrome browser.

![image](https://user-images.githubusercontent.com/17876015/55308121-5840e480-5477-11e9-9fbc-3206ad06709a.png)

Same error with the demo link: https://microsoft.github.io/BotFramework-WebChat/09.customization-reaction-buttons/

Error message in Edge is as below.

![image](https://user-images.githubusercontent.com/17876015/55308271-d4d3c300-5477-11e9-90d3-e85a4cd622d6.png)

Any help with this please?

**Comment by Souvik04** [comment]
@corinagum Thanks for your prompt action. I wanted to know if the fix would also be available for the ES-5 version: https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/01.b.getting-started-es5-bundle as well. An equivalent ES-5 standard sample would be great.

**Comment by corinagum** [comment]
@Souvik04, this looks like an issue unrelated to Web Chat. `Unable to connect` indicates incorrect credentials.
Since many of our samples require modern browsers, we don't support the customization in our samples on IE 11. You are welcome to use our samples as a place to start, but the implementation would need to be done by your team. This includes importing the relevant polyfills and working around the limitations of IE (for example, the browser does not support lambda functions)
