### ISSUE TITLE
ConversationUpdate is not being triggered on iframe

### ISSUE THREAD

**Issue by mahomedalid** [Microsoft/BotFramework-WebChat#1885]
The   Azure Bot Registration section displays an iframe embed code as a suggested way to solve an integrated webchat on your site, but seems ConversationUpdate is not being triggered because it doesn't inject the user id by default. 

I see there is a similar issue (#752) but the fact that the iframe is the "recommended way" (at least from the azure portal perspective) make me think that we can improve the experience, maybe suggesting a snippet of code using webchat.

**Comment by corinagum** [comment]
Hi @mahomedalid, we do have a major update coming to the Azure Bot Service side of Web Chat, which can be tracked over at: https://github.com/Microsoft/BotFramework-WebChat/issues/1086.
If you don't mind, I'm going to move your comment over there for discussion since @compulim is heading these changes. He's better equipped to answer these questions, and by tracking there we can make sure the proper documentation is created. :) Please feel free to add to the discussion over there!
