### ISSUE TITLE
update not come on azure when deploy

### ISSUE THREAD

**Issue by Tamoormughal** [Microsoft/BotFramework-WebChat#1906]
hey every one i am working on the bot frame v4 version when i some changes on my code and deploy on azure web deploy the changes of css and controller not implement on alive side project but working on emulator

**Comment by Tamoormughal** [comment]
hey every one  i am working on the bot frame v4 version when i some changes on my code and deploy on azure web deploy the changes of css and controller not implement on alive side project but working on emulator

**Comment by corinagum** [comment]
@Tamoormughal, Is this issue related to Web Chat? If so, please provide any console errors, screen caps, and reproduction steps to help us figure out your problem. 

You can also check out your Channels blade to see if there are any issues described there.

If this issue is related to Azure Bot Services, you can contact them through Azure portal support.

**Comment by yadvdinesh** [comment]
Even I have faced the same issue. In order to resolve it, I need to restart the app service on Azure

**Comment by corinagum** [comment]
Closing this issue. @Tamoormughal if you think this is a Web Chat issue, please add more information as stated above and I will reopen.

**Comment by Tamoormughal** [comment]
Yes issue resolved issue on the side of endpoint .endpoint must same as
your deploymnt url
