### ISSUE TITLE
bot C# v4 not working on internet explore  

### ISSUE THREAD

**Issue by Tamoormughal** [Microsoft/BotFramework-WebChat#1907]
bot is not open internet explore

**Comment by corinagum** [comment]
Please take a look at getting Web Chat [es5 polyfill sample](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/01.b.getting-started-es5-bundle) to make your bot compatible with Internet Explorer. 
Otherwise if you have a console error, screencaps, or further details that might help us with your issue please add those and repro-steps and I will reopen this issue.
