### ISSUE TITLE
Text from String Variable Extends Past Edge of Adaptive Card in botchat-es5.js

### ISSUE THREAD

**Issue by torynfarr** [Microsoft/BotFramework-WebChat#1955]
We're using the https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js version of the web chat control in-order to prevent a plethora of Adaptive Card rendering issues in IE11 on the web site on which our chat bot is present.

We just recently added a feature to our bot where a question is sent to a QnA Maker knowledge base. If a result is found, we display that answer in an Adaptive Text Block in an Adaptive Card which we generate in our code. 

We're using the AdaptiveCards library from Microsoft, version 1.1.2 to do that.

Everything displays properly in Edge and Chrome:

![Edge ES5 Rendered Correctly](https://user-images.githubusercontent.com/36836551/57090904-895a4200-6ccd-11e9-9c95-8097605ee519.png)

But in IE11 (same site with the ES5 web chat control) the text is extending beyond the bounds of the adaptive card:

![IE11 ES5 Rendered Incorrectly](https://user-images.githubusercontent.com/36836551/57090941-a4c54d00-6ccd-11e9-83ec-7ae1d56c455c.png)

I have a feeling this is a web chat control issue rather than an Adaptive Card issue (since it works correctly in Edge and Chrome). So... I'm posting this issue here.

**Comment by corinagum** [comment]
Hi @torynfarr, since you're using v3 of Web Chat, unfortunately the support our team will be able to provide is limited. V3 is in sunset right now, and unless there are security issues reported in v3, our focus is going into v4. 

My first suggestion, if you are able, would be to bump to v4. Please take a look at our [README](https://github.com/Microsoft/BotFramework-WebChat#migrating-from-v3-to-v4-of-web-chat) for reasoning and tips on how to do so. By doing so you would have the benefit of using the latest features of Web Chat and Adaptive Cards, which has also continued to publish improvements over the past several months. :)

If you are unable to make the bump, I would recommend verifying that there are no errors that might indicate what and where the problem is coming from.
