### ISSUE TITLE
[IC3] Request: RTL support and localization for Hebrew, Urdu, and Arabic (+ info on localization contributions)

### ISSUE THREAD

**Issue by Tamoormughal** [microsoft/BotFramework-WebChat#1976]
> VSTS #1663019

[edited by @corinagum)

Feature request: RTL support for languages like Hebrew, Urdu, and Arabic, as well as localization support for Hindi and the previously listed languages.
----

[Question]
is it possible speech to text of google is implement in bot frame work V4 like hindi and urdu and arabic?

**Comment by corinagum** [comment]
Hi @Tamoormughal, are you asking about adding localizations to V4 in Hindi, Urdu, and Arabic? (Please correct me if I am wrong), but I believe two of these languages would need RTL support, as well as the addition of the localized strings. 
We have a PR already in existence, provided by the community, for which the review has been put on hold due to lack of bandwidth. https://github.com/microsoft/BotFramework-WebChat/pull/1548 If you have the time, it would be great if you could take a look at this PR and provide some feedback. 

I am leaving this question as tracking for the RTL feature. If there are other Web Chat users interested in this feature, please leave your +1 comment here. :)

I believe Hindu does not need RTL support. If this is the case, providing localization will be a much simpler process. We welcome Pull Requests that add or modify the language files in ____. Please take a look at https://github.com/microsoft/BotFramework-WebChat/issues/1966 if you would like to look into the basics of creating a PR related to localization. You would be adding a new file to the `BotFramework-WebChat/packages/component/src/Localization/` directory.

**Comment by corinagum** [comment]
This also needs to involve discussion with Adaptive Cards :)

**Comment by corinagum** [comment]
We have 2 stale PRs related to Localization that haven't been completed yet due to scheduling problems. Those links are:
https://github.com/microsoft/BotFramework-WebChat/pull/2369
https://github.com/microsoft/BotFramework-WebChat/pull/1548

**Both contributions are very much appreciated!** The dev team will implement these *with original credit* as one PR in the near future.

I am closing both above PRs, but any contributors are welcome to add to discussion here. For customers looking for these languages/RTL support, please chime in below.

**Comment by geea-develop** [comment]
@corinagum let me know if you need any assistance. we continuously merging the master to our fork but this takes time all because RTL is not natively supported. I don't think we are very far from it. Although adaptive cards will need some adjustments since they are not natively supported either.

**Comment by corinagum** [comment]
@geea-develop I don't have a timeline for working on RTL support, but I hope that once I do I can consult with you! Thanks again for your contributions, and I apologize that this has taken a long time.

**Comment by geea-develop** [comment]
@corinagum hi, I see it has been added to todo for R8. let me know if you need me to assist as I don't see a pull request or work in process that has started. 
thanks.

**Comment by corinagum** [comment]
Thanks, will do!

**Comment by corinagum** [comment]
@geea-develop for now, would you be able to provide your latest `he-IL.js` file? :)

**Comment by geea-develop** [comment]
https://gist.github.com/geea-develop/938f1a44267fb17164b41b7ecd2cfece

**Comment by Tamoormughal** [comment]
through js file of direct line we can handle RTL and LRT
