### ISSUE TITLE
WebChat is not displayed correctly for mobiles

### ISSUE THREAD

**Issue by reyesrico** [Microsoft/BotFramework-WebChat#198]
I tried to use WebChat for the IOS and Android devices and all the front-end appears small (it looks that it is rendering the Desktop version). 

![webchat](https://cloud.githubusercontent.com/assets/10733155/20900547/73391148-bae3-11e6-9a7f-d36a9373d2f8.PNG)

**Comment by danmarshall** [comment]
cc @kevkor 

Knowing the height of the scrollable portion is going to be challenging on mobile devices. When the user is focused on the keyboard, we do not truly know how tall their keyboard is in relationship to the device window. 

Also, this bug might actually be directed at the BotFramework, no the control itself, since the device zooming is specified by the hosting HTML.
