### ISSUE TITLE
Add WebChat version to UserAgent

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotFramework-WebChat#1985]
## Feature Request

It would be useful for diagnostics and analytics to know the WebChat version that is sending messages.

[Enhancement]

**Comment by compulim** [comment]
Great idea.

The `window.WebChat.createDirectLine` function in the bundle should put/append Web Chat version as bot agent. There is an option called `botAgent`.

@EricDahlvang few questions:

- What do you think about the format of the bot agent? E.g. `WebChat/4.4.1`?
- How about the user want to append their own? Should we always append `WebChat/4.4.1` to what the user provided?
- Web Chat has different loading mechanisms, should we list them out?
   - Bundle: full bundle (include Adaptive Cards), minimal bundle (no Markdown)
   - Channel: CDN, NPM, embed (currently, it is difficult to get this)

@corinagum it's modifying the bundle, not difficult because it is more-or-less similar to how `createStyleSet` work. And you know we have 3 versions in `meta` tag, use the one from bundle.

**Comment by EricDahlvang** [comment]
The adaptive cards version can be determined based on the WebChat build version.  But, as much information as we can provide regarding customer enabled features and loading mechanisms seems good.
