### ISSUE TITLE
ChannelData or UserId are not propagated to Bot Framework on Conversation Update events

### ISSUE THREAD

**Issue by MarekLani** [microsoft/BotFramework-WebChat#1992]
## Version
master

## Describe the bug
```
window.ReactDOM.render(
          <ReactWebChat directLine={directLine} store={store} userID="UserName" />,
        document.getElementById('webchat')
);
```
Bot Framework backend receives activity with property From.Id set to conversationId instead of UserName. Also when trying to alter channel data, this is propagated only on postactivity events.

## To Reproduce
Use code sample above and catch conversation update events on the backend side. UserId equals to conversation Id instead of value set for userId on web chat element.

## Expected behavior
Propagate channelData and UserId also for conversation update

[Bug]

**Comment by corinagum** [comment]
@MarekLani, sorry for the late reply, this fell off my radar. 
ConversationUpdate is not an activity sent from the bot or user, which is why the fromId is showing as the conversation ID. This by design from the Bot Framework protocol. Our general recommendation is to not use conversationUpdate to retrieve user-related information. Instead, please check out our sample 15.d which shows sending an activity through the client.

**Comment by MarekLani** [comment]
@corinagum Thank you for the explanation.
