### ISSUE TITLE
InputHint not respected by WebChat in speech scenarios

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-WebChat#2022]
InputHint not respected by WebChat in speech scenarios

## Screenshots
![image](https://user-images.githubusercontent.com/33519520/58164278-6ba14c80-7c7d-11e9-906a-ebfaa432fc12.png)

![image](https://user-images.githubusercontent.com/33519520/58164365-98edfa80-7c7d-11e9-9e2a-f5f0902caf59.png)
## Version
CDN: latest/webchat.js

## Describe the bug
The InputHint on a return activity indicates whether the microphone should be opened to take additional input. ExpectingInput should result in the microphone being opened but it's seemingly ignored.

## To Reproduce
- Open webchat with Bot
- Ask a question using speech that will trigger a response with InputHint set.

## Expected behavior
- Microphone to be opened automatically when `ExpectingInput` set on InputHint.

[Bug]

**Comment by compulim** [comment]
@corinagum could you look at this one?

There are 3 options for input hints: `ExpectingInput`, `AcceptingInput` (default), `IgnoringInput`.

The spec can be found at, https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0. The "Default values for input hint" section is complicated and Web Chat currently do not expect SDK automatically set the `InputHint` correctly. For example, what if the 2nd last activity has `ExpectingInput` while the last one is `IgnoringInput`? I think we should `IgnoringInput`.

Few things to check:

- I don't think we have logic for `ExpectingInput`, please add.
- We have logic for `IgnoringInput`, can you check if it work properly?
- Please check if there are activities mixed with `ExpectingInput` and `IgnoringInput`, we should honor the last one in chronologically order.

I looked at v3, `ExpectingInput` will turn on microphone (although it may fail due to browser block).
