### ISSUE TITLE
Text-To-Speech is working well on Edge browser, however, it's having issue in Chrome Browser

### ISSUE THREAD

**Issue by guptarajesh001** [microsoft/BotFramework-WebChat#2029]
[Edit by corinagum]
Multiple things to investigate here:
1. Text-to-Speech not working on Chrome
1. SPFx Extensions are new for the Web Chat team and we haven't confirmed if the two techs are supported.

Since [Mock Bot](https://microsoft.github.io/BotFramework-WebChat/06.c.cognitive-services-speech-services-js/) text-to-speech is working as expected (try command: 'card review'), I believe we need to investigate if there's any interference when creating an SPFx Extension when adding in Web Chat.

(See below for original message)
---

Kindly reopen this bug, as per your suggestion, we have updated comments and remove unnecessary code to make it more understandable.

We have created Chat BOT SPFx Extension using react framework, speech-to-text and text-to-speech of chat bot is working well on the Edge browser, however, on
Chrome Browser Version 74.0.3729.169, only speech to text is working, but can't here anything from Chat BOT, if we are activating its speaker.                                       

Versions of tools/plugins:
botframework-webchat: "4.4.1"
react-native version - "0.59.8"
nodeJS - "v10.15.3"
types/sharepoint: "2016".1.2"
typescript: "3.3.4000"
es : 6

Here is the code:
```
import * as React from "react";
import { DirectLine } from "botframework-directlinejs";
import {
  createStore,
  createStyleSet,
  createCognitiveServicesSpeechServicesPonyfillFactory,
  createDirectLine
} from "botframework-webchat";
import ReactWebChat from "botframework-webchat";

export default class BotContainer extends React.Component<IBotProps, {}> {
  
#Fetching token for Bot and Speech
  public async componentDidMount() {
     #create the directLine for Bot
      this.directLine = createDirectLine({
        token: this.props.chatBotDialogProps.BotSecret,
        webSpeechPonyfillFactory: createCognitiveServicesSpeechServicesPonyfillFactory(
          {
            region: this.props.chatBotDialogProps.TokenRegion,
            token: this.BotSecretToken
            )
          }
        )
      });
    }

   #Authorization token for speech
    const authorizationToken = await fetch(
      "https://westus.api.cognitive.microsoft.com/sts/v1.0/issueToken",
      { method: "POST", headers: SpeechHeaders }
    ).then(r => r.text());

    const region = "westus";

    #Getting webSpeechPonyfillFactory detail
    this.webSpeechPonyfillFactory = await createCognitiveServicesSpeechServicesPonyfillFactory(
      { region: region || "westus", authorizationToken: authorizationToken }
    );
   
    );
   }

  
    return (
      <div>
        <div className="minimizable-web-chat">
           
                  <ReactWebChat
                    userID={this.props.email}
                    username={this.props.userName}
                    directLine={this.directLine}
                    styleOptions={styleOptions}
                    resize="detect"
                    locale={localeLang}
                    store={this.store}
                    webSpeechPonyfillFactory={this.webSpeechPonyfillFactory}
                  />
              
      
        </div>
      </div>

**Comment by corinagum** [comment]
Please retain the template provided when providing a new bug.
Once you answer the questions below, someone on the team can try and help you.

### [GitHub issues](https://github.com/Microsoft/botframework-webchat/issues) should be used for bugs and feature requests. See the Support section to get support related to Bot Framework and Web Chat.

## Screenshots
- If applicable, add screenshots to help explain your problem. 
- Be sure to remove or obscure personally identifiable information from your code and screenshots 

## Version
- What version of Web Chat are you using? Are you using the CDN? NPM package? Or embedding Web Chat to your site via `<iframe>`? 
- The fastest way to find your Web Chat version is by checking the meta tag on your deployed site. 

## Describe the bug
- Give a clear and concise description of what the bug is. 
- Please be sure to add screenshots of the console errors in your browser, if there are any 

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
- Give a clear and concise description of what you expect to happen when following the reproduction steps above. 

## Additional context
- Add any other context about the problem here.

[Bug]

**Comment by corinagum** [comment]
@guptarajesh001, please modify this issue by copy-pasting and using the template provided for bug reports. Once you have done so, please feel free to leave a comment and I can reopen this issue. 
I have pasted the template below for your convenience. 

### [GitHub issues](https://github.com/Microsoft/botframework-webchat/issues) should be used for bugs and feature requests. See the Support section to get support related to Bot Framework and Web Chat.

## Screenshots
- If applicable, add screenshots to help explain your problem. 
- Be sure to remove or obscure personally identifiable information from your code and screenshots 

## Version
- What version of Web Chat are you using? Are you using the CDN? NPM package? Or embedding Web Chat to your site via `<iframe>`? 
- The fastest way to find your Web Chat version is by checking the meta tag on your deployed site. 

## Describe the bug
- Give a clear and concise description of what the bug is. 
- Please be sure to add screenshots of the console errors in your browser, if there are any 

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
- Give a clear and concise description of what you expect to happen when following the reproduction steps above. 

## Additional context
- Add any other context about the problem here.

[Bug]

**Comment by saurav2107** [comment]
@corinagum Why was this issue closed, I was hoping to get a resolution in the same thread, as I am also facing the same issue, i.e. STT is working fine with new cognitive speech service but TTS is only working on MS Edge and no other browser, and on Edge we don't have any way to stop whats being spoken.
 I understand Speech Service is in preview and Bing Speech is not compatible with WebChat v4, but is there any backup plan for the transaction?

**Comment by corinagum** [comment]
I'll be happy to re-open this once someone fills out the bug filing template that will provide the baseline information our team needs.

**Comment by corinagum** [comment]
To quote from #2033:

> Regarding SPFX support, we currently have no documentation verifying whether or not Web Chat and SPFX are compatible. I just started discussions with the team about verifying SPFX compatibility with Web Chat and hopefully creating a blog post of information. @v-kydela is the man to track.

**Comment by compulim** [comment]
Working on this, trying to repro it in SharePoint.

**Comment by compulim** [comment]
Same issue on Stack Overflow, https://stackoverflow.com/questions/57325439/how-to-fix-microphone-accessing-being-blocked-in-an-iframe-which-only-affects-go.

**Comment by compulim** [comment]
My investigations is as follow.

## Why it work in Edge by not Chrome?

- Chrome implemented a new feature called [Feature Policy](https://developers.google.com/web/updates/2018/06/feature-policy)
   - This feature, block microphone access by default, unless the hosting HTML unblock it by appending an attribute to it, like `<iframe allow="microphone *">`
- Edge, didn't implement Feature Policy yet, thus, it is not blocked by default

When `getUserMedia` failed in Chrome, the error will be shown in the console like this:

![image](https://user-images.githubusercontent.com/1622400/62498786-4a88cc00-b795-11e9-909c-6d3dcf3dca97.png)

## How to workaround it?

On the embed HTML code, it should read, `<iframe src="..." allow="microphone *">`.

Developer cannot add it using F12 Developer Tool or after the DOM element is loaded on the page. It will have no effects and microphone access will still be blocked.

## Why it is not working?

When SharePoint parse the embed HTML code, it seems it removed all attributes but `src`/`width`/`height`. And it also add `allowfullscreen`. Thus, we are not able to add `allow="microphone *"` to the embed generated by SharePoint.

**Comment by compulim** [comment]
Closing this due to external issues. There is nothing we could do on Web Chat. The hosting app is blocking Web Chat from using any media capabilities.
