### ISSUE TITLE
Could not complete the operation due to error 8150002e 

### ISSUE THREAD

**Issue by Manoj51573** [microsoft/BotFramework-WebChat#2036]
Hi Team,

When user clicks on the button using adaptive card, a java script error comes: "Could not complete the the operation due to error 8150002e" however, this error is intermittent and comes quite seldom.

I am using web-chat. and error is coming in ‘botchat-es5.js’, any help or suggestions will be appreciated.

Kindly see  the below error screen-shot.

![Script-error](https://user-images.githubusercontent.com/46702830/58533966-85620700-821c-11e9-9c84-82435f6f1455.png)

Thanks,
Manoj Kumar

**Comment by corinagum** [comment]
@Manoj51573, please modify your this issue by copy-pasting and using the template provided for bug reports. Once you have done so, please feel free to leave a comment and I can reopen this issue. 
I have pasted the template below for your convenience. 

Please retain the template provided when providing a new bug.
Once you answer the questions below, someone on the team can try and help you.

### [GitHub issues](https://github.com/Microsoft/botframework-webchat/issues) should be used for bugs and feature requests. See the Support section to get support related to Bot Framework and Web Chat.

## Screenshots
- If applicable, add screenshots to help explain your problem. 
- Be sure to remove or obscure personally identifiable information from your code and screenshots 

## Version
- What version of Web Chat are you using? Are you using the CDN? NPM package? Or embedding Web Chat to your site via `<iframe>`? 
- The fastest way to find your Web Chat version is by checking the meta tag on your deployed site. 

## Describe the bug
- Give a clear and concise description of what the bug is. 
- Please be sure to add screenshots of the console errors in your browser, if there are any 

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
- Give a clear and concise description of what you expect to happen when following the reproduction steps above. 

## Additional context
- Add any other context about the problem here.

[Bug]
