### ISSUE TITLE
Microsoft Speech not speaking back issue 

### ISSUE THREAD

**Issue by isathish** [microsoft/BotFramework-WebChat#2037]
webchat.js:69900 Web Chat: Cognitive Services Speech Services support is currently in preview. If you encounter any problems, please file us an issue at https://github.com/Microsoft/BotFramework-WebChat/issues/.

**Comment by corinagum** [comment]
@isathish, please modify this issue by copy-pasting and using the template provided for bug reports. Once you have done so, please feel free to leave a comment and I can reopen this issue. 
I have pasted the template below for your convenience. 

### [GitHub issues](https://github.com/Microsoft/botframework-webchat/issues) should be used for bugs and feature requests. See the Support section to get support related to Bot Framework and Web Chat.

## Screenshots
- If applicable, add screenshots to help explain your problem. 
- Be sure to remove or obscure personally identifiable information from your code and screenshots 

## Version
- What version of Web Chat are you using? Are you using the CDN? NPM package? Or embedding Web Chat to your site via `<iframe>`? 
- The fastest way to find your Web Chat version is by checking the meta tag on your deployed site. 

## Describe the bug
- Give a clear and concise description of what the bug is. 
- Please be sure to add screenshots of the console errors in your browser, if there are any 

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
- Give a clear and concise description of what you expect to happen when following the reproduction steps above. 

## Additional context
- Add any other context about the problem here.

[Bug]
