### ISSUE TITLE
Adaptive cards are not rendering when iframe embed used for WebChat

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/BotFramework-WebChat#2050]
## Screenshots
Ms team channel for same bot shows adaptive rendering
![image](https://user-images.githubusercontent.com/32375467/58719734-085a9d00-8396-11e9-855e-ace11f09d4f7.png)

WebChat using iframe embed for same bot shows broken adaptive cards rendering.
![image](https://user-images.githubusercontent.com/32375467/58720048-c2ea9f80-8396-11e9-8c40-d7a38a30773e.png)

## Version
1. embedding Web Chat to your site via `<iframe>
2.  Using botbuilding v3 SDK to build the bot.

## Expected behavior
Adaptive cards are not channel specific so they should be rendered correctly in all supported channels.  

[Bug]

**Comment by corinagum** [comment]
Hi @rjgmail88, unfortunately v3 of Web Chat (using the `iframe` from Azure Portal) is in sunset mode right now and we're not performing maintenance that doesn't fall under security issues for v3. We are hoping that using v4 of Web Chat in embed (`iframe`) will be available very soon.

Could you try out your bot on a basic web page made by following our sample 01.a? This is just to test if your adaptive cards issues are persisting to v4 of Web Chat. If so, we'll be able to investigate the problem and file this as a bug. Otherwise, my immediate fix recommendation would be to use v4 through CDN or NPM until we get v4 available via embed, which will hopefully be in the upcoming weeks.

**Comment by rjgmail88** [comment]
Thanks @corinagum. I am trying to use sample 01 and not sure how to replace following URL  for my bot

```
https://webchat-mockbot.azurewebsites.net/directline/token
```

**Comment by rjgmail88** [comment]
@corinagum , can you  help with above so I can confirm if this is really a bug or not.

**Comment by corinagum** [comment]
, Mock Bot has code showing users how to implement a token server, which is the API call that you are linking above. 

For protecting the Web Chat secret, the simplest implementation is to store the secret on the bot side so that the client never sees the secret, and exchange it for a token before sending it to the client. If you are interested in implementing a token server like Mock Bot has, you are welcome to take a look at Mock Bot on the following files:

https://github.com/compulim/BotFramework-MockBot/blob/master/src/generateDirectLineToken.js
https://github.com/compulim/BotFramework-MockBot/blob/master/src/renewDirectLineToken.js
https://github.com/compulim/BotFramework-MockBot/blob/master/src/index.ts#L109

(#1534 is for tracking the creation of a sample, but hasn't been implemented yet)

**Comment by rjgmail88** [comment]
Thanks @corinagum , As I'm just testing web chat v4 example to make sure cards work I would like t skip the server steps if implement server step. Do you suggest any other way ? I can still use  sample 01.a

**Comment by corinagum** [comment]
You can temporarily use your secret instead of a token. Remove the token fetch code from sample 01.a and instead place the secret on the createDirectLine line, like so:
` directLine: window.WebChat.createDirectLine({ secret: 'YOUR_SECRET_HERE' })`

Disclaimer: This is not recommended for deployed code and is good for testing only. Please don't use your secret on a deployed app. :)

**Comment by rjgmail88** [comment]
I have verified and adaptive cards worked.

**Comment by corinagum** [comment]
@rjgmail88 thank you for investigating! As I said above, we don't have the bandwidth to commit to v3 fixes right now so I'm going to be closing this issue as a won't fix. Based on your immediate needs, I would recommend either waiting for v4 to be available via embed, or to bump to v4 by following the sample 01.a (or others).
If you need help with implementation, please feel free to check out the Stack Overflow web-chat tag, where our support engineers can help you out. :) Thanks again!
