### ISSUE TITLE
If websocket is enabled there is no chat history on page reload

### ISSUE THREAD

**Issue by eeisenbr** [microsoft/BotFramework-WebChat#2059]
## Version

We're using version 4.4.1, the ES5 version, via CDN:
https://cdn.botframework.com/botframework-webchat/4.4.1/webchat-es5.js

## Describe the bug

If we have webSocket: true passed into window.WebChat.createDirectLine() and reload the page or navigate to different pages in the site, the conversation history is not loaded.  If we simply change that true to false, it works perfectly.

## To Reproduce

1. Interact with the bot
2. Refresh the page
3. See the chat history is empty

## Additional context

ConversationId 79qx4XT19e57wTkNZ8Lc2w-j around 13:23 UTC on June 6th, 2019 shows the problem.
 
[Edit by corinagum]: This is a new issue discussing the closed topic https://github.com/microsoft/BotFramework-WebChat/issues/850, reopened at vince's recommendation. :)

[Bug]

**Comment by tdurnford** [comment]
I was able to load the conversation history using websockets, but since the token encapsulates the conversation id, I had to reuse the token from the previous conversation and set the watermark value. It also worked when I used a Web Chat secret and a conversation id.

### Reusing Token
```javascript
let { token } = sessionStorage;

if (!token) {
  const res = await fetch('/directline/token', { method: 'POST' });
  const { token: directLineToken } = await res.json();

  sessionStorage['token'] = directLineToken;
  token = directLineToken;
}

const directLine = createDirectLine({ 
  token, 
  webSockets: true,
  watermark: 10
});
```
For simplicity, I'm saving the token in session storage; however, this practice is not considered safe - developers should manage tokens on the server side.

### Secret and Conversation Id
```javascript
let { conversationId } = sessionStorage;

const directLine = createDirectLine({ 
  secret,
  conversationId, 
  webSockets: true,
  watermark: 10
});
```
Hope this helps!

**Comment by eeisenbr** [comment]
I originally was saving the watermark and using it during the reconnect and it still wouldn't work using WebSockets.  I removed all that code (for saving the watermark to a cookie) when I discovered that polling worked perfectly.  I just added the watermark code back in and it still didn't work for me using WebSockets.  But even so, why would the watermark be required for WebSockets but not for polling?

**Comment by tdurnford** [comment]
You don't actually need the watermark. It is an optional parameter and acts as a bookmark for previous messages. If you only wanted the last 10 messages, you would have to use the activity id from the 10th last message as the watermark. The code in my comment above works without the watermark, but you will get all of the messages in the conversation, not a subset. 

The issue is more reliant on the conversation id, which is baked into the token. Each time you request a new token, you are creating a new conversation regardless if WebSockets are enabled that is independent of the last conversation and doesn't have permission to access the previous messages.

Are you generating a new token or are you passing your Web Chat secret to DirectLine?

**Comment by eeisenbr** [comment]
We generate a token and save both it and the conversationId to cookies, and pass them to createDirectLine when the page is reloaded.  I will update the code to only pass the token and see if that makes any difference.

**Comment by eeisenbr** [comment]
So I removed the conversationId parameter to the createDirectLine call (it's now just the token) and that fixed the issue.  Closing this (although maybe the documentation/examples need some updates).
