### ISSUE TITLE
Analytics and telemetry

### ISSUE THREAD

**Issue by danmarshall** [microsoft/BotFramework-WebChat#206]
Opening the topic of instrumenting so that we can have usage patterns. Completely respecting privacy. It could be good to know how often people use carousels, how many messages are in an average conversation, window size, etc. Might be nice if the reported data was also open.

**Comment by billba** [comment]
Two out of the three things you mention there could be harvested from the bot itself (or the framework). I'd be interested as to what the control could uniquely tell us.

**Comment by danmarshall** [comment]
Platform / browser would also be a key metric.

**Comment by compulim** [comment]
There are two topics here:

- Microsoft to collect telemetry, this *must* be an opt-in function
- Bot developer to collect telemetry, this is up to the bot developer how to handle privacy issues

**Comment by corinagum** [comment]
> There are two topics here:
> 
> * Microsoft to collect telemetry, this _must_ be an opt-in function
> * Bot developer to collect telemetry, this is up to the bot developer how to handle privacy issues

Second bullet will be resolved with https://github.com/microsoft/BotFramework-WebChat/pull/2922

**Comment by compulim** [comment]
This issue is partly resolved. See [`TELEMETRY.md`](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/TELEMETRY.md)

Web Chat will do measurements, but not collecting any telemetry. It's just a no-op.

Bot developer can write code to collect measurements. The current set of measurements is very limited, pending a talk to CELA team to understand what we can measure.

In future, we can consider collecting measurements:

- In sample, to understand what features are most popular
- In development build, to understand how the developers customize Web Chat
- In IFRAME, to diagnose issues

**Comment by corinagum** [comment]
Closing this issue - the second part of the topic, acquiring telemetry for samples etc, hasn't gained traction. We can always revisit the topic later. :)
