### ISSUE TITLE
Playground is broken due to recent renderMarkdown + CRLF change

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2069]
## Screenshots

![image](https://user-images.githubusercontent.com/1622400/59288822-7ff7ba00-8c29-11e9-98fd-cc5bf5261014.png)

## Version

"master"

## Describe the bug

Playground throw exception after trying to connect to Mockbot.

## To Reproduce

1. Browse to https://webchat-playground.azurewebsites.net/
2. Click on "Connect to official Mockbot"

## Expected behavior

User can start talking to Mockbot.

## Additional context

Seems related to recent CRLF changes on renderMarkdown.

[Bug]

**Comment by tdurnford** [comment]
I'm not exactly sure how the Playground is using the markdown renderer, but the [renderMarkdown](https://github.com/microsoft/BotFramework-WebChat/blob/4f21f0bf5e5d2cfa0e5304bc6c37c9c95357fc29/packages/bundle/src/renderMarkdown.js#L76) function takes a second parameter - styleSet - that is deconstructed to access the markdownRespectCRLF value in Web Chat's style options. Perhaps we shouldn't deconstruct the styleSet in the function declaration and check for the options existence in an if statement instead.

**Comment by compulim** [comment]
`renderMarkdown` should be as simple as `(markdown: string) => string`, without `options`.

And people who send in `renderMarkdown`, e.g. `FullReactWebChat`, should be responsible to configure the Markdown engine.

The current code in `FullReactWebChat` is good (i.e. `memoizedRenderMarkdown` part) because it configure the Markdown engine and send in `(markdown: string) => string`.

**Comment by tdurnford** [comment]
Right, so the markdown renderer being passed to ReactWebChat needs to be of type (markdown: string) => string, but the type of the markdwon renderer being exported by botframework-webchat is of type (markdown: string, options: any) => string. It looks like the Playground is importing the renderer from botframework-webchat and then passing it to ReactWebChat causing the type mismatch. This seems like a redundant step since the renderer is configured in FullReactWebChat by default. 

Should we reconfigure the render function that botframework-webchat is exporting, remove the renderer from the props passed to ReactWebChat in the Playground, or both?
