### ISSUE TITLE
Dutch locale not showing retry when message failed

### ISSUE THREAD

**Issue by GewoonMaarten** [microsoft/BotFramework-WebChat#2121]
## Screenshots

![image](https://user-images.githubusercontent.com/10438686/60094992-d4348b00-974d-11e9-9144-17296f9960af.png)

## Version
Webchat from NPM:
`"botframework-webchat": "^4.3.0"`

## Describe the bug
When you set the locale to `"nl-NL"` and send a message. If it somehow times-out or similar you will get the `Couln't send message (retry)` message. But in Dutch the template is not filled correctly .

## To Reproduce

1. Set the locale of the webchat to `nl-NL`.
2. Send a message and get it to time-out.
4. See error.

## Expected behavior

I expect the failure message to be `Versturen mislukt (opnieuw)`.

[Bug]

**Comment by corinagum** [comment]
Hi @GewoonMaarten, thank you for the submission. This bug has been fixed in https://github.com/microsoft/BotFramework-WebChat/pull/2038, and will be available in our next release (mid-July).

If you need these changes immediately, please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).

**Comment by GewoonMaarten** [comment]
Good to hear! Thank you for the quick response.
