### ISSUE TITLE
Google Speech-To-Text with Web-Chat

### ISSUE THREAD

**Issue by mamhh** [microsoft/BotFramework-WebChat#2126]
How Can we use (Google Speech-To-Text) with WebChat instead of MS cognitive speech services?

**Comment by compulim** [comment]
Web Chat can be used with any speech engine that has a client library that conforms to [W3C Web Speech API standard](https://w3c.github.io/speech-api/).

Looking at [this Google Cloud Speech doc](https://cloud.google.com/speech-to-text/docs/reference/libraries), they currently do not have any client libraries that works in browser.

They do have a [client library for Node.js called `@google-cloud/speech`](https://www.npmjs.com/package/@google-cloud/speech), but it doesn't looks conform to W3C Web Speech API and might not work with browser because their underlying [`google-gax`](https://www.npmjs.com/package/google-gax) library probably [only works with Node.js](https://github.com/googleapis/gax-nodejs/blob/master/src/grpc.ts#L37). So porting that library to browser doesn't sounds very feasible.

So, the easiest path, you will need to build a client library for Google Cloud Speech, by bridging between [their REST API](https://cloud.google.com/speech-to-text/docs/reference/rest/) and [W3C Web Speech API](https://w3c.github.io/speech-api/).

After you have create the W3C-based client library, then you can easily plug it into Web Chat.

**Comment by mamhh** [comment]
> Web Chat can be used with any speech engine that has a client library that conforms to [W3C Web Speech API standard](https://w3c.github.io/speech-api/).
> 
> Looking at [this Google Cloud Speech doc](https://cloud.google.com/speech-to-text/docs/reference/libraries), they currently do not have any client libraries that works in browser.
> 
> They do have a [client library for Node.js called `@google-cloud/speech`](https://www.npmjs.com/package/@google-cloud/speech), but it doesn't looks conform to W3C Web Speech API and might not work with browser because their underlying [`google-gax`](https://www.npmjs.com/package/google-gax) library probably [only works with Node.js](https://github.com/googleapis/gax-nodejs/blob/master/src/grpc.ts#L37). So porting that library to browser doesn't sounds very feasible.
> 
> So, the easiest path, you will need to build a client library for Google Cloud Speech, by bridging between [their REST API](https://cloud.google.com/speech-to-text/docs/reference/rest/) and [W3C Web Speech API](https://w3c.github.io/speech-api/).
> 
> After you have create the W3C-based client library, then you can easily plug it into Web Chat.

Thanks a lot ... could you please provide me with a sample implementation of  [W3C Web Speech API standard](https://w3c.github.io/speech-api/) .. that will be great support

**Comment by compulim** [comment]
Web Chat use [this adapter](https://github.com/compulim/web-speech-cognitive-services) to bridge between [Azure Cognitive Services client library for JavaScript in a browser](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-js-browser), and the [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API). It is a bit easier in our case because the client library of Azure Cognitive Services supports browser, but Google Cloud Speech don't.

This adapter handles both speech-to-text and text-to-speech scenarios. For speech-to-text, it use Azure Cognitive Services client library. For text-to-speech, it use Cognitive Services REST API directly.

Web Chat supports hybrid engine for Web Speech API. So you can configure Web Chat to use your Google Cloud Speech adapter for speech-to-text, and browser speech or Cognitive Services for text-to-speech. You can pick the best of the world based on your scenario. 😉

**Comment by mamhh** [comment]
@compulim   Could you please help me on this ..(you will need to build a client library for Google Cloud Speech, by bridging between their REST API and W3C Web Speech API.)

**Comment by corinagum** [comment]
'How to' questions such as this one are better suited for [Stack Overflow](https://stackoverflow.com/tags/botframework). Please feel free to post other questions you have about developing your own features over there so the community at large may help out. If you need help with a Web Chat implementation, you can post a question to the [Web Chat tag](https://stackoverflow.com/questions/tagged/web-chat). Thank you!

Please share the link to your Stack Overflow question on this issue. The Web Chat team will close this issue after a week or when the Stack Overflow link has been added.

**Comment by mamhh** [comment]
> 'How to' questions such as this one are better suited for [Stack Overflow](https://stackoverflow.com/tags/botframework). Please feel free to post other questions you have about developing your own features over there so the community at large may help out. If you need help with a Web Chat implementation, you can post a question to the [Web Chat tag](https://stackoverflow.com/questions/tagged/web-chat). Thank you!
> 
> Please share the link to your Stack Overflow question on this issue. The Web Chat team will close this issue after a week or when the Stack Overflow link has been added.
@corinagum @compulim 
Well.. I've conceptually primitive question about WebChat.. why did you divide all components into node JS packages ??
Shouldn't everything be simple pure javascript?? WebChat is all about  UI/logic running within browser environment..
It will be great if you explain the concept for me ..

**Comment by corinagum** [comment]
I believe @tdurnford answered your questions on https://github.com/microsoft/BotFramework-WebChat/issues/2123#issuecomment-507407720

I recommend further questions like these be brought to Stack Overflow. :)
