### ISSUE TITLE
Intercept SuggestedActions the same way as cards with attachment middleware

### ISSUE THREAD

**Issue by Hatzman91** [microsoft/BotFramework-WebChat#2146]
Is there a way to replace the components of the suggested actions in the same way as its possible with the cards and the attachment middleware without rewriting the whole webchat?

**Comment by corinagum** [comment]
Related to https://github.com/microsoft/BotFramework-WebChat/issues/1839

At the moment, there isn't. :/ This is something we realize is a big jump in expectations for our users and we plan on investigating ways to improve the send box in order to reduce the amount of overhead for users wanting to customize part of the send box, as opposed to the entire, very large, component.

Please feel free to add your +1 to the issue and any comments or other questions you might have.
