### ISSUE TITLE
Get Blob URL on sample 20 results in error

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotFramework-WebChat#2148]
## Screenshots

![image](https://user-images.githubusercontent.com/11055362/60682771-75f06200-9e49-11e9-97de-f912d10e53ac.png)

![image](https://user-images.githubusercontent.com/11055362/60682797-8b658c00-9e49-11e9-82d1-e17a946748e3.png)

## Describe the bug
Using the https://webchat-sample-upload-to-azure.azurewebsites.net/ sample and uploading a file works, but clicking the Get Blob Url button results in error.

## To Reproduce

1. Go to https://webchat-sample-upload-to-azure.azurewebsites.net/ 
2. Upload an image
3. Click 'Get Blob URL' button

## Expected behavior
Blob URL should be displayed when clicking 'Get Blob URL' button

[Bug]

**Comment by corinagum** [comment]
Thanks for the catch :)

This is expected behavior, since by default the user doesn't have permissions to download the file on the blob the image was uploaded to. 

As an explanation for this, we're going to add a subtitle to the card showing the blob URL informing that the URL can be used for further processing (and providing the link as a button is only for demonstration purposes).
