### ISSUE TITLE
Adaptive card render error in IE11

### ISSUE THREAD

**Issue by Junlol** [microsoft/BotFramework-WebChat#2187]
## Screenshots

![webchat render cards error](https://user-images.githubusercontent.com/19281094/61206009-1ab15000-a724-11e9-90f7-f35dc936d0d5.JPG)

## Version

webchat 4.5.0
cdn: https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js

## Describe the bug

I am use webchat es5 sample in IE11, then typing help to render cards, but cards not rendered.

[webchat es5 sample link](https://microsoft.github.io/BotFramework-WebChat/01.b.getting-started-es5-bundle)

**Comment by corinagum** [comment]
Thanks for reporting this. I am investigating the cause.

**Comment by corinagum** [comment]
To anyone running into this issue, I have the temporary workaround of using the browser-polyfill from babel@5.6. Just add this to your index.html:

<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>

Still investigating the fix.

**Comment by compulim** [comment]
We believe the problem is introduced in #1970 (ESLint) and [on this line](https://github.com/microsoft/BotFramework-WebChat/pull/1970/files#diff-f562daa4cced86e2864050c6038aac8fR164).

The problem is, we moved from:

```js
const firstChildren = element.children[0];
```

to

```js
const [firstChildren] = element.children;
```

In IE11, `NodeList` is not iterable. But in Chrome/Edge, `NodeList` is iterable.

We should include `core-js` module that improvise `NodeList` as iterable. More details can be found on https://github.com/zloirock/core-js#iterable-dom-collections.

**Comment by corinagum** [comment]
@compulim will be doing a patch to 4.5(.1) shortly, after which this fix will be available in the latest release. Thank you for your patience!
