### ISSUE TITLE
Microsoft Bot Directline channel failing on IE 

### ISSUE THREAD

**Issue by tinuCoder** [microsoft/BotFramework-WebChat#2216]
## Screenshots
![image](https://user-images.githubusercontent.com/25457761/61628175-a120e100-ac92-11e9-9016-1d304fcaa724.png)

I am using Microsoft.Bot.Builder v3.20.1.42
and using botchat.js for my UI side look and feel.
Microsoft AppId : 0a083f83-5b28-4daf-b37f-54b0b8e5db9a

## Describe the bug
I have a bot created using botchat.js. This is now completely build and working fine on Chrome, Microsoft's Edge browser but this is not working on IE. 

What might be the reason for the failure only on IE.

On IE when the call is made to Directline channel to get conversation details it fails with error 500 internal server error.

Test URL: https://matoowebapp-stage.azurewebsites.net/chat.html

Is this ecma script issue or is there any other issue also please help me reach the solution.

Thanks.

[botchat.txt](https://github.com/microsoft/BotFramework-WebChat/files/3416988/botchat.txt)

[Bug]

**Comment by corinagum** [comment]
hi @tinuCoder, What version of Web Chat are you currently using? (Bot Builder version and Web Chat version are separate, and Web Chat v4 supports both v3 and v4 of Bot Builder). It looks like you may be using v3 of Web Chat, which unfortunately we are unable to support forked versions of due to time constraints.

It's possible you are having a polyfill issue, or that your code is using lambda functions, which are not supported in IE11. Please look into adding es5 polyfills to add modern browser functionality to IE11, and removing any lambda functions your code might have.

**Comment by tinuCoder** [comment]
Hi @corinagum  thank you so much for your quick response. 
I tried using new es5 js file for botchat even that is failing on the IE.
url : https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js

I am also attaching my js file for your ref on how I am using botchat js.

In AppData --> Bundle Config file i have code 
            BundleTable.Bundles.Add(new StyleBundle("~/bundle/css").Include("~/Content/Styles/bootstrap.min.css",
                                                                            "~/Content/Styles/nanoscroller.css",
                                                                            "~/Content/Styles/botchat.css",
                                                                            "~/Content/Styles/app-specific.css"));

            BundleTable.Bundles.Add(new ScriptBundle("~/bundle/script").Include("~/Scripts/jquery-3.1.1.min.js",
                                                                                 "~/Scripts/bootstrap.min.js",
                                                                                 "~/Scripts/jquery.shorten.js",
                                                                                 "~/Scripts/jquery.nanoscroller.min.js",
                                                                                 "~/Scripts/emoticon.js",
                                                                                 "~/Scripts/botchat.js",
                                                                                 "~/Scripts/nanoscroller.js",
                                                                                 "~/Scripts/botscript.js"));

In my _Layout.cshtml file i am adding these js and css

    
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    @Scripts.RenderFormat("<script type=\"text/javascript\" src=\"{0}?nocache=" + version + "\"></script>", "~/bundle/script")
    @Styles.RenderFormat(@"<link href={0}?nocache=" + version + "  rel=stylesheet />", "~/bundle/css")

[botchat.txt](https://github.com/microsoft/BotFramework-WebChat/files/3420288/botchat.txt)
[botscript.txt](https://github.com/microsoft/BotFramework-WebChat/files/3420293/botscript.txt)


Help me add the required polyfill in the current botchat.js to make it work on IE

**Comment by corinagum** [comment]
Unfortunately I won't be able to help you go through your code. :( Please check for any lambda functions and make sure they are replaced with standard functions. Since I'm sure at this point that you are using v3, my suggestion on top of that would be to migrate your Web Chat to v4, in which case our Support Engineers on Stack Overflow will be able to help you.

'How to' questions such as this one are better suited for [Stack Overflow](https://stackoverflow.com/tags/botframework). Please feel free to post other questions you have about developing your own features over there so the community at large may help out. If you need help with a Web Chat implementation, you can post a question to the [Web Chat tag](https://stackoverflow.com/questions/tagged/web-chat). Thank you!
