### ISSUE TITLE
Support for ToggleVisibility action

### ISSUE THREAD

**Issue by Naveenbc** [microsoft/BotFramework-WebChat#2224]
Adaptive cards have introduced a new action called ToggleVisibility in 1.2 version which seems to be very useful. Is there a plan to support this feature? if yes when can we expect?

**Comment by corinagum** [comment]
https://adaptivecards.io/explorer/Action.ToggleVisibility.html Link to schema explorer specs. :) Thanks for bringing this up! I'm adding this to the team meeting for us to discuss.

**Comment by v-kydela** [comment]
@Naveenbc 
@corinagum 

I expect Direct Line to be removing toggle visibility actions because of this bug: https://github.com/microsoft/BotFramework-Services/issues/87

Since Web Chat already supports Adaptive Cards 1.2, I expect the workaround described in that thread to enable toggle visibility actions.

**Comment by tdurnford** [comment]
Since the Direct Line Connector Service uses Adaptive Cards v1.0.6 and the toggle feature was introduced in v1.2, the toggle attributes are removed from the card in the connector service before the activity reaches Web Chat. It looks like the toggle visibility feature works in Web Chat with the [work around](https://github.com/microsoft/BotFramework-Services/issues/87#issuecomment-499698448) @v-kydela mentioned.

![screengif](https://user-images.githubusercontent.com/17039790/61916363-11329f80-aefd-11e9-9b24-a8c3dbb53a98.gif)

The development team is working to update the connector service to use Adaptive Cards v1.2, and you can track the progress of the update here https://github.com/microsoft/BotFramework-Services/issues/87.
