### ISSUE TITLE
Direct Line Speech Button is not visible

### ISSUE THREAD

**Issue by danieldangler** [microsoft/BotFramework-WebChat#2227]
#### What project is affected?
The Virtual Assistant - especially The Direct Line Channel
#### What language is this in?
C#
#### What happens?
On thuseday i added the direct Line Channel to communicate with the Bot via Webchat.
Now on Friday i changed nothing and the Button isnt there anymore.
#### What are the steps to reproduce this issue?
1. Deploy the VA
2. Add Direct Line Channel
3. Wait 3 Days
4. The Button to insert Speech is away
(I think this isnt reproducable)
#### What were you expecting to happen?
See a Button to speak wioth the bot
#### Can you share any logs, error output, etc.?
/
#### Any screenshots or additional context?
![after_after](https://user-images.githubusercontent.com/39704877/61952975-882b6f00-afb5-11e9-8131-c15a78b21068.PNG)

![after](https://user-images.githubusercontent.com/39704877/61952972-8661ab80-afb5-11e9-88f0-b6105448022f.PNG)

**Comment by darrenj** [comment]
Appears to be a WebChat issue as VA uses the channel like any other Bot. @danieldangler might help if you can share the webchat code your using?

**Comment by tdurnford** [comment]
@danieldangler Have you added the `webSpeechPonyfillFactory` prop to Web Chat?

```javascript
// Note, for simplicity we are using the subscription key on the client side; however, the client should
// always authenticate against your server to avoid exposing the subscription key to any part of your client code.
const webSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
  region: '<region>',
  subscriptionKey: <subscriptionKey>
});

window.WebChat.renderWebChat({
  directLine: window.WebChat.createDirectLine({ token }),
  webSpeechPonyfillFactory
}, document.getElementById('webchat'));
```

Take a look at the [Cognitive Services Speech Services](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.c.cognitive-services-speech-services-js) Web Chat sample for more details.

**Comment by corinagum** [comment]
I'm still investigating whether or not this is related, but when I tried out Mock Bot's speech sample I got the following errors:
![image](https://user-images.githubusercontent.com/14900841/61965539-4c78b100-af85-11e9-8427-22e426034aa7.png)

**Comment by corinagum** [comment]
I commented with an error that I ran into testing speech bots, but it turns out that was specific to my machine only. I tested out Mock Bot speech and everything seems to be functioning as expected (microphone button is showing up and speech interaction works)

![image](https://user-images.githubusercontent.com/14900841/61965885-30294400-af86-11e9-8cdb-b306717394a5.png)

**Comment by tdurnford** [comment]
@danieldangler Did that resolve your issue?

**Comment by compulim** [comment]
The first screenshot is from Azure Portal with Web Chat v3, and the second is from v4.

We recently bumped Web Chat in the "Test in Web Chat" blade to v4.

In Web Chat v3, we provide free trial of Bing Speech in "Test in Web Chat" blade. Since Cognitive Services team is deprecating Bing Speech around mid-October this year, we are also taking away the speech button when we bump to v4.

To use speech, please obtain your Speech Services subscription key and set it in Web Chat. You can find instructions in this sample, https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.c.cognitive-services-speech-services-js.
