### ISSUE TITLE
Question on SSO for teams sample implementation

### ISSUE THREAD

**Issue by saikumaru** [microsoft/BotFramework-WebChat#2234]
I am testing the sample
https://microsoft.github.io/BotFramework-WebChat/19.c.single-sign-on-for-teams-apps/

I started off by creating a Teams app, with personal tab's content populated with
https://webchat-sample-sso-teams.azurewebsites.net/

However I get the below message on the popup, when I test it on Microsoft Teams via the browser.
`Failed to authorize due to FailedToOpenWindow`

Also, if I just try to open the  site on another tab of the browser, it renders a blank page.
There is nothing on the console log either.
Is this example expected to work with teams.microsoft.com?

When I try the same on Teams desktop App, I get the below error.

`Sorry, but we’re having trouble signing you in.

AADSTS50020: User account 'adc@outlook.com' from identity provider 'live.com' does not exist in tenant 'Microsoft' and cannot access the application 'b543fc3e-a618-469e-8f37-e3fed1deb3c4'(Web Chat SSO for Teams Apps) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.`

As I understand, 

(a) I will need to first host the bot on my azure account 
(b) build an AD app 
(c) register the bot on the AD app,

and will not be able to test it just by using the webcontent URL provided, please advise or update the document the steps a bit more elaborately.

**Comment by corinagum** [comment]
Hi @saikumaru, I believe this sample is pretty clear about needing to provide your own `.env` files and secrets, app id, password, etc in order to make it work. Could you be more specific about what your suggestions for improvement are? This sample is not expected to work with teams.microsoft.com.

**Comment by compulim** [comment]
@saikumaru Thanks for reporting.

Few things mentioned in your post:

1. `Failed to authorize due to FailedToOpenWindow` is reported when hosting https://webchat-sample-sso-teams.azurewebsites.net/ in a newly-created personal tab
   - Will investigate
2. Blank page when opening https://webchat-sample-sso-teams.azurewebsites.net/ in a browser (not Teams)
   - This is expected. The website use Teams SDK to open auth prompt. When Teams SDK detect it is not opened in a Teams app, it do a blank page
3. Does not work with `live.com` account
   - I think the OAuth application we configured for https://webchat-sample-sso-teams.azurewebsites.net/ does not support public account, but only work account (a.k.a. Office 365 accounts)

Will investigate point 1.

**Comment by saikumaru** [comment]
Thank you very much to you both for checking this so quickly for me.

@corinagum, as I have mentioned, I haven't tested this with a local/Azure hosted version yet. But did test with the sample link provided. I shall try the local way too as I get a chance updating the .env etc.

@compulim, thank you, will await your response. I also request you to add answer to '3' to the document, so that we know which account to use.

**Comment by compulim** [comment]
@sakumaru I am working on this now.

1. For `Failed to authorize due to FailedToOpenWindow`, I tried the steps below and could not repro in Teams app and Chrome browser.
   1. Using "App Studio" > "Manifest editor", create a new app
   1. Fill out "Details" > "App details"
   1. Add a personal tab
      1. Set entity ID something unique
      1. Set content URL to https://webchat-sample-sso-teams.azurewebsites.net/
   1. Install the app locally by going thru "Finish" > "Test and distribute" > "Install"
1. N/A
1. I have verified the App Registration and it should work with public account.
   - ![image](https://user-images.githubusercontent.com/1622400/62480071-c10cd600-b763-11e9-8429-1e0fffb9d5a7.png)

Are you using free Teams or paid?

**Comment by compulim** [comment]
Updated, I am seeing the same problem with a free Teams account.

1. This is due to popup blocker in browser. Since the error is a popup from Teams, could you submit a feedback to Teams and ask them for a more appropriate error other than `Failed to authorize due to FailedToOpenWindow`?
1. N/A
1. Working on this.

**Comment by compulim** [comment]
For 3, although I have configured it to accept personal Microsoft accounts, looks like it is only working for `@microsoft.com` and there is no way to enable it.

I am going to take out the instructions for simple hosting since it is not working and sounds like there are no ways to make it work outside of `@microsoft.com`.
