### ISSUE TITLE
Quick Reply Buttons

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2272]
i want to use normal button rendering on webchat V3 as quick reply button on webchat.
is it possible to interpret it on webchat using javascript or jquery.
![Screenshot (322)](https://user-images.githubusercontent.com/34365788/62526001-05789e80-b856-11e9-8684-91cabfd5902d.png)

**Comment by corinagum** [comment]
Hi @Bradrajkumar, unfortunately no longer support forks of v3 of Web Chat. However, because React and jQuery don't mix well, I do not recommend using jQuery to  make changes to the DOM. 

Please note that v3 is in sunset and we strongly recommend bumping to v4 of Web Chat before October of this year. Please check out the [Migration Guide](https://github.com/microsoft/BotFramework-WebChat#migrating-from-web-chat-v3-to-v4) for more details.
