### ISSUE TITLE
Using WebChat in SharePoint Script Editor

### ISSUE THREAD

**Issue by virendrak** [Microsoft/BotFramework-WebChat#228]
I have followed the approach mentioned in path - https://github.com/billba/botchattest
As of now this link contains two .html(s), 
_\botchattest-master\Index.html
\botchattest-master\botchat\Index.html_

I have merged the code from both the .html(s) and created one html. So, that I can use the complete code snippet in my SharePoint page in Script Editor Web Part.

I created a Web Part Page in my SharePoint site and added a Script Editor web part, and saved required **.JS** and **.CSS** in Style Library Folder.

Here, the "Click" event of Hero card is get post-back and my whole page is getting refreshed. However when I have used in normal html page (), it's working as expected.

Please Find ZIP, Where it is working fine in HTML Page:
[SPBot.zip](https://github.com/Microsoft/BotFramework-WebChat/files/645670/SPBot.zip)

Web Part - SP Page
I pasted below code in my web part page in Script Editor Web Part:
[WPCode.txt](https://github.com/Microsoft/BotFramework-WebChat/files/645698/WPCode.txt)

Thanks in Advance!

Regards,
Viren

**Comment by billba** [comment]
I haven't looked at your code, but it doesn't make sense to merge the two `index.html` files. One is for the botchat control, one is for the page its embedded in.

**Comment by virendrak** [comment]
Thanks @billba. Now, I have again used the 2 pages logic in share-point page. Since, I cannot serve ._html_ page from SharePoint, it's downloading that page instead of opening, so I have renamed the page _.html_ to _.aspx_

I have pasted below **iFrame** tag in my web part page in **Script Editor** web part. It's working as expected. 

Thanks for your help and information. Now, I am closing this issue.
 
```
<div style="float:right">
<iframe id="botchat" src="../Style Library/botchat/index.aspx?s=<SecureId>" width="450" height="500"></iframe>
</div>
```
**Thanks,
Viren**

**Comment by richdizz** [comment]
Hey viren...billba asked that I look at your issue as I have more experience with SharePoint. I got it working pretty easily using the same steps you used. Only difference is I put my index.aspx/css/js in the SiteAssets library instead of Style Library. I would be really careful in how SharePoint does relative paths with site collections. Here is my embed code as sample (note: "Chatbot" is a subsite off the root site collection of my SharePoint Online tenant):

`<iframe id="botchat" src="/chatbot/SiteAssets/index.aspx?t=<directline secret>" width="320" height="500"></iframe>`

**Comment by virendrak** [comment]
@richdizz Thank you so much for your input.
