### ISSUE TITLE
Update WebChat sample docs to make it clear that the embed script goes to v3 of webchat

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-WebChat#2340]
Some (all?) of the samples give users the assumption that they are on the "latest" version of WebChat given the url slug. We should update this and provide additional documentation denoting the difference of "latest" of the portal hosted WebChat and v4.

**Comment by compulim** [comment]
This work should be done on docs.microsoft.com, not Web Chat repos. We filed here to track the work for the docs team.

**Comment by Kaiqb** [comment]
It references the samples. Which samples?

**Comment by compulim** [comment]
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0

For example, in this article, it is showing Web Chat v1. There are few things it could be updated:

- Update the screenshot, because IFRAME should be showing v3 by default
- The embed script is hosting Web Chat v3, but latest version of Web Chat is v4 (4.6.0)

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-bot-configuration?view=azure-bot-service-4.0

In this article, it is showing "Test in Web Chat" blade:

- The screenshot should show Web Chat v4
- Although this embed version of Web Chat is v4 (4.3.0), it is not the latest of Web Chat (4.6.0)

I just digging two articles. There may be more.

**Comment by corinagum** [comment]
All embeds are now v4
