### ISSUE TITLE
V3 Support

### ISSUE THREAD

**Issue by kesavanpurushothaman** [microsoft/BotFramework-WebChat#2370]
Hi @compulim,

Can you please confirm how long can we use V3?
We have done customization using CSS and we need to plan well in advance for V4 migration.

Thanks, Kesavan

**Comment by compulim** [comment]
Hi @kesavanpurushothaman,

The Web Chat team want to provide support for v3 and all deprecating features for 2 years. The clock count when we ship v4, that's about 10 months ago. So you still have 14 months to go. In the meanwhile, we will fix all security issues related to v3.

We understand v3 and v4 are not compatible. In short, v4 still expose CSS, but the DOM tree is different because we rewrote it to support better accessibility. Our conformance to WCAG 2.1 and Section 508 can be found at https://go.microsoft.com/fwlink/p/?LinkId=2050974.

In v4, we introduce "style options" and "style sets" to enhance the CSS experience for a few good reasons:

- Style set is actually bunches of CSS stylesheet (a.k.a. CSS-in-JSON)
   - Microphone button use the CSS stylesheet in `styleSet.microphoneButton`, but never touch other CSS stylesheet
   - This isolation helps developers/designers creating CSS without worrying accidentally touching other components
   - Because CSS is now in JSON format, you will need to learn this new React CSS syntax at https://reactjs.org/docs/dom-elements.html#style
   - You can find list of style set under `/packages/component/src/Styles/` folder
- Building your own CSS means changing accent color or general stuff is difficult, because they are scattered in multiple places
   - Padding is a headache
   - When our DOM tree change, the CSS stylesheet will also need to be changed
      - For example, to fix accessibility bugs, we might need to change the DOM tree
- Instead of CSS or style set, the developer can pass a *style option* JSON object, which Web Chat will generate a *style set* JSON object
   - You can change accent color in the style option once, and we will generate style set for CSS stylesheets which use your accent color in multiple places
   - You can manually generate the style set from your style options too, and then modify the style set before passing to Web Chat, this give you best of both world
- Also, heading is no longer in Web Chat, because you can always do it better in plain HTML and make it super fancy 😉

And if you move to v4, there are [tons of customizations you can do](https://microsoft.github.io/BotFramework-WebChat/), few highlights:
- Render a custom component, https://microsoft.github.io/BotFramework-WebChat/10.b.customization-password-input/
- Throw away Web Chat but leave its business logic, https://microsoft.github.io/BotFramework-WebChat/21.customization-plain-ui/ (currently broken in the sample, will fix it soon)
   - You can easily write your own UI from ground up but reusing our business logic
   - Your DOM tree will be free from any CSS or anything from us, it's 🌟 super clean 🌟

Feel free to let us know what kind of big customization you made. We can point you to the correct place/way to style it. 😀

**Comment by corinagum** [comment]
Feel free to add more questions to this thread. Otherwise I am closing as answered. :)

**Comment by kesavanpurushothaman** [comment]
Thanks for the quick turn around and well explained responses.
Below are the list of customizations we have done in V3(BotChat.js and BotChat.css).
 1) Logo - Bot and User
 2) Injected <div> tags for Menus, Minimize/Maximize buttons
 3) Dynamically changed bot logo's depending on our business logic
It would be more helpful if you can direct me to the correct sources for our above requirements.

Thanks, Kesavan Purushothaman

**Comment by corinagum** [comment]
1. https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.b.display-user-bot-images-styling
1. https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/12.customization-minimizable-web-chat
1. https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/14.customization-piping-to-redux
