### ISSUE TITLE
Rename webSpeechPonyfillFactory 

### ISSUE THREAD

**Issue by DaveVoyles** [microsoft/BotFramework-WebChat#2371]
Is it possible to rename this function? Or perhaps better understand why it is a Ponyfill factory?

Did someone mean to write Polyfill?

**Comment by corinagum** [comment]
Ponyfill is not a typo. Please see this closed PR: https://github.com/microsoft/BotFramework-WebChat/pull/1663

**Comment by compulim** [comment]
Ponyfill factory is "a function that will create a ponyfill". It is using factory pattern (a function to create something), thus, it is called ponyfill factory.

And ponyfill is better than polyfill, as @sindreshorhus has been pointed out in his article, https://github.com/sindresorhus/ponyfill, ponyfill are pure and is not monkey-patching.

The way ponyfill work, is not overriding what your current environment has, which means, it is pollution-less and preferred in modern JavaScript environment, where tons of packages could load and conflicting with each others.

In the jQuery days, they have ponyfill too. They call it `$.noConflict`. Using `noConflict` will not pollute the environment (other than the namespace it own).

You can turn a ponyfill into a polyfill by simply applying the ponyfill over your current environment. For example, in a browser,

```js
const myPonyfill = someoneGiveThisToMe();

Object.keys(myPonyfill).forEach(name => window[name] = myPonyfill[name]);
```

For Web Speech API, surprisingly, they are not polyfill-able. This is not the primary reason why we use ponyfill. But, you can try out this code in your browser:

```js
window.speechSynthesis = 123;

console.log(window.speechSynthesis === 123); // return false, in Chrome 76
```

For the factory part of the name, this is primarily because we want to conform to W3C Web Speech API as much as possible.

We need to pass options to the Web Speech API, but we don't want to modify the established standard by adding fields/members unknown to other implementations. Thus, we are using a factory function approach to pass options to the Web Speech API. These options are very local to Web Chat, e.g. reference grammar ID (used for LUIS).

This pattern allow us to use Web Speech engines other than Cognitive Services, because we didn't change the W3C API at all. No behavior change and no adds.

So, the name `ponyfillFactory` is correct. And every part of its name has its purpose. And the name is not as meaningless as "adapter", and "manager".

**Comment by DaveVoyles** [comment]
Thank you very much for this thorough response! I take a break from web dev for a bit and there are new terms I've never learned about.
