### ISSUE TITLE
sending "channelData" from webchat V4

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2377]
hi all,

In webchat V3 i was able to send the "channelData" inside the package only.
ex:-  t.channelData["CustomChannel"]=customChannelName;

in webchat V4 i tried to send it as e.channelData["CustomChannel"]=customChannelName; but i am getting error in directline sending activity.
how to achieve the same in webchat V4. please suggest me ASAP.

there are attached screenshot of postactivity inside code 
![Capture](https://user-images.githubusercontent.com/34365788/64239948-c013c380-cf1e-11e9-811b-b146ff07c97e.PNG)
![Capture](https://user-images.githubusercontent.com/34365788/64240029-dae63800-cf1e-11e9-9cad-14d64a291c44.PNG)

and error screenshot.

**Comment by tdurnford** [comment]
Yes, it is possible to add custom channel data to outgoing activities in Web Chat v4. It looks like you are modifying DirectLines `postActivitiy` method which is more of a v3 approach. I would recommend creating a custom store middleware to modify activities sent by the user. Take a look at the [Backchannel Piggyback on Outgoing Activities](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/15.a.backchannel-piggyback-on-outgoing-activities) Web Chat Sample for more details. I modified the code from the sample to work in Internet Explorer since it looks like you are using the es5 buddle. 

**Bot Framework Web Chat v4**
```javascript
const store = window.WebChat.createStore(
  {},
  function() {
    return function(next) {
      return function(action) {
        if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
          // We are using the simple-update-in package to update "action" with partial deep cloning.
          action = window.simpleUpdateIn(action, ['payload', 'activity', 'channelData', 'email'], function () { return 'johndoe@example.com' });
        }
        return next(action);
      }
    }
  }
);

window.WebChat.renderWebChat({
  directLine: window.WebChat.createDirectLine({ token: token }),
  // We will use a custom version of Redux store, which we added middleware to handle backchannel messages.
  store: store
}, document.getElementById('webchat'));
```

If you are debugging locally with Ngrok, 502 errors generally indicate there is an issue sending the message to the bot. I would recommend checking your Ngrok configuration. Note, changing your messaging endpoint in Azure might take 20-30 to propagate. For more details, take a look at https://github.com/microsoft/BotFramework-Services/issues/118.

For future reference, **'how to'** questions such as this one are better suited for Stack Overflow. Please feel free to post other questions you have about developing your own features over there so the community at large may help out. If you need help with a Web Chat implementation, you can post a question to the [Web Chat](https://stackoverflow.com/questions/tagged/web-chat) tag. Thank you!
