### ISSUE TITLE
final release of webchat V4

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2387]
Hi all,

As per my knowledge the other functinalilties are still in progress to add up in webchat V4.
i am downlaoding the latest from the CDN link which you have provided. As i am doing multiple customization as per my requirement so i am curious to know that when you are going to give the **final release of webchat V4**(an estimation).
please provide me the detailed information regarding this.

**Comment by corinagum** [comment]
Hi @Bradrajkumar, Web Chat v4 is closely coupled with the entire Bot Framework SDK v4, which is currently in active development and fully supported. There aren't any current plans regarding an announcement of v.next, which would determine the end of life / last release for v4. 

Due to the above, I think you can safely assume that there are no immediate plans for a final release. :)

Hope that helps!
