### ISSUE TITLE
Better visual feedback on button click.

### ISSUE THREAD

**Issue by matthidinger** [microsoft/BotFramework-WebChat#2401]
@vijaysaimutyala commented on [Fri Aug 30 2019](https://github.com/microsoft/AdaptiveCards/issues/3412)

This is for the card using the WebChat renderer. The earlier version of the Adaptive cards used give a nice visual feedback to the user whether the button was clicked or not. But with the latest updates, the feedback is no longer present. It just shows a outline around the button in accent color which is not very helpful.

Old Adaptive Cards

![Old-Adaptive-Button-Feedback](https://user-images.githubusercontent.com/7084628/63999923-3f218a00-cb22-11e9-82bf-562900a16dbb.gif)

New Adaptive Cards
![New Adaptive Card](https://user-images.githubusercontent.com/7084628/64000299-0e8e2000-cb23-11e9-8903-300c351ad9a7.gif)

Users are not able to understand whether they've clicked the button or not. Sometimes when the  response from the bot needs some time to process and respond, the user without the help of feedback is clicking the button again before the response from bot appears. Any suggestions on this would be helpful.

---

@matthidinger commented on [Mon Sep 16 2019](https://github.com/microsoft/AdaptiveCards/issues/3412#issuecomment-531904886)

@compulim @corinagum can you folks take a look at this?

**Comment by corinagum** [comment]
@matthidinger thanks for the transfer.

Rather than just Adaptive Cards, I would say this is a potential improvement we can make to the entire Web Chat app. We intentionally removed the pointer cursor from buttons in a [#1819 ](https://github.com/microsoft/BotFramework-WebChat/pull/1819) a few months ago, but that doesn't mean we can't improve the :active pseudo class UX throughout the project.

potential design questions: 
1. Should this take the accent color from `styleOptions`? or
1. Should this be a new style option like `buttonActiveBgColor`, `buttonActiveTextColor`, `buttonActiveOutline` etc. 
1. Do we allow differentiation between the styling of Adaptive Cards buttons and other buttons?

**Comment by vijaysaimutyala** [comment]
@matthidinger @corinagum Do you think there's some quick hack that could bring back the visualization ?

**Comment by corinagum** [comment]
@vijaysaimutyala you can consider adding to your web page's CSS specification to the button you want to modify. To do this you would need to trace the DOM to the button, brief example below:

```
.main > div > div > ... .ac-pushButton &:active {
    background-color: #etcetc
}

```

Then once Web Chat's changes are in you can just delete this CSS. :)

**Comment by vijaysaimutyala** [comment]
Thanks @corinagum

**Comment by corinagum** [comment]
The content of the card belongs to adaptive cards team, so it would be better to keep the styling responsibility on that of the Adaptive Card templating.
