### ISSUE TITLE
Trigger listening without clicking

### ISSUE THREAD

**Issue by r3dr4gon** [microsoft/BotFramework-WebChat#2446]
As the open microphone request is still on the backlogs, I was wondering if there is an option to trigger the listening (virtualy click the mic button) manually? I.e. is there any way to simulate the click of the mic button?

**Comment by compulim** [comment]
Today, you could virtually click the microphone button through customization. Look at `microphoneButton.js` with the `connectMicrophoneButton()` function for the HOC.

But there is a requirement on Safari (iOS and Mac OS), which requires "user-initiated gesture" for audio playback and recording. The user would need to physically click/tap on something to start the first recording. Otherwise, the browser would block the access to microphone.

I would suggest also implementing a splash screen. When the user click/tap on it, it will play a very short silent MP3 to "prime" the engine, and also record on the microphone.

In this way, both audio playback and recording are primed, and the browser would not block future playback/recording in the page session.
