### ISSUE TITLE
Pausing while giving input. 

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2468]
## Feature Request

Custom pauses for user speech. 

Not everybody speaks the same way,and in the current build there is a provision of just 1.5s pause between words in the input. A little longer or rather custom pauses would be more ideal

**Comment by corinagum** [comment]
@prashanthsridhar, thank you for filing this issue. I think this is a good idea that we should discuss with the team. For now, I am adding the Backlog label and will bring it up in our team discussions. :)

To anyone else looking for a way to lengthen/shorten the user speech pause time, please feel free to leave your +1 below.

**Comment by compulim** [comment]
Silence detection (i.e. the "1.5s" pause) is controlled by Cognitive Services (or any underlying speech engine). AFAIK, there are no options for us to send to Cognitive Services to modify this behavior.

We have a planned feature #2197 called "push-to-talk" (a.k.a. walkie talkie or truck transponder), which allows the user to control when to start/stop recording on the microphone.

Once #2197 is implemented, the user will be able to control the duration by themselves.

I am closing this because it is technically impossible for Web Chat to modify how silence detection behave.
