### ISSUE TITLE
Need suggestion to configure the reverse proxy w.r.t 19.a.single-sign-on-for-enterprise-apps

### ISSUE THREAD

**Issue by SreekanthOAuth** [microsoft/BotFramework-WebChat#2470]
## Screenshots
My react app folder structure in Azure service. 

![image](https://user-images.githubusercontent.com/24246902/66828062-c1003200-ef6d-11e9-8b75-e0e0d6b57fe2.png)

## Version

4.4.1

## Describe the bug

Getting 404 error even after updating the web.config with rewrite url rule.

https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps

## To Reproduce

Steps to reproduce the behaviour:

1. Go to 'https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps'
2. Click on clone

## Expected behavior

By following https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps, we have implemented same. But seeing 404 execption. 

We have found some references to configure the reverse proxy to react app like,

https://ruslany.net/2014/05/using-azure-web-site-as-a-reverse-proxy/

Followed the same and still seeing 404 error.

My web.config in react app is 
```
<?xml version="1.0"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Reverse Proxy to api" stopProcessing="true">
                  <match url="^api/?(.*)" />
                  <action type="Rewrite" url="https://[app_service]/{R:1}" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```
Could you please suggest how can achieve this.

[Bug]

**Comment by compulim** [comment]
@SreekanthOAuth this one is not related to Web Chat.

I would suggest turning on "failed request tracing" to debug how IIS is doing the redirection. You can read these 2 articles to turn it on, and viewing logs.

Failed request tracing works by logging every decision IIS made. By default, it logs only 400-599, that's why it's called "Failed request". You can configure it to log 100-599, which essentially means all requests.

- https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs
- https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/using-failed-request-tracing-to-trace-rewrite-rules
