### ISSUE TITLE
Speech-enabled bot does not "speak activities" in certain cases

### ISSUE THREAD

**Issue by AndreMantas** [microsoft/BotFramework-WebChat#2474]
Got the speech demos working (eg 06.f.hybrid-speech) but there are at least two cases in which the activities sent from the bot are not spoken out loud:

**a) proactive activities (like welcome message sent by the bot)**

**b) when user uploads a file**

I understand that the bot only "speaks" when the user clicks in the mic button and talks in the first place.

But I need a way to "forward" utterances to be spoken "by the bot"

How can we control this behavior?
Is there some store event that we can dispatch?

Thanks in advance.

**Comment by compulim** [comment]
Hi @AndreMantas, thanks for reporting and interests in speech input.

1. Proactive activities
   - We have a technical issues over here. If the audio playback is done *before any user gesture*, it will be blocked by the browser. For example, welcome messages.
   - If your hosting page could play a short silence MP3 when the user interact on the page, it will unblock the speech synthesis.
   - We are planning to revamp send box in #2211. The revamped send box clearly isolate between keyboard input and microphone input. We will be able to prime the audio playback engine. This will unblock welcome messages.
2. When user uploads a file
   - Because uploading a file is using a mouse, instead of microphone. Bot responses are not synthesized. This is a design problem.
   - We are planning to revamp send box in #2211. In other terms, if the user is in microphone input, Web Chat will always speak out the bot responses. This should solve the issue for attachment.

I would recommend to wait until #2211 land. If you are adventurous and know about Redux, you can look at `/packages/core/src/actions/startSpeakingActivity.js`. If you dispatch this action prior bot responses, the next bot responses will be synthesized.

I have captured both requirements in #2211.

**Comment by corinagum** [comment]
Closing this issue for organizational purposes. For further discussion, please feel free to say something on #2211 Thank you!
