### ISSUE TITLE
Glitch when user send a message

### ISSUE THREAD

**Issue by bleekbless** [microsoft/BotFramework-WebChat#2480]
## Describe the bug

When I open the chat and send a message and it is in the 'sending' status the new message always got to the top of the messages and then when the message is actually sent it goest to its expected position... how can I fix that ?

**Comment by corinagum** [comment]
@bleekless please use our bug template to fill out information that we will need in order to help you.

Based off of your description, it sounds like you are having clock skew problems. Please take a look at these issues before filing another bug:

https://github.com/microsoft/BotFramework-WebChat/issues/1954
https://github.com/microsoft/BotFramework-WebChat/issues/1127
