### ISSUE TITLE
[Message Reactions - UI] Need feature like emojies to get rendered in bot messages for webchat.

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2485]
@compulim  as per the request i have created the mockup for the custom feature.
here is the follow up link of last feature requirement was raised.
Link:- https://github.com/microsoft/BotFramework-WebChat/issues/2431
please see this attachment.
[powerpoint.pptx](https://github.com/microsoft/BotFramework-WebChat/files/3756788/powerpoint.pptx)

**Comment by cwhitten** [comment]
Hello @Bradrajkumar - thanks for the suggestion.  We'll take the UI guidance as we prioritize our upcoming WebChat sprint.

As far as protocol support: making use of custom events going through Direct Line would be the suggested approach for message reactions. The Message Reaction activity type is currently not supported in Direct Line (cc @dandriscoll )

**Comment by tdurnford** [comment]
@cwhitten @dandriscoll Are you sure Direct Line doesn't support message reactions? The current Custom Reaction Button Web Chat sample sends a message reaction activity to the bot and works fine with the `onReactionsAdded` and `onReactionsRemoved` handlers.
```javascript
handleDownvoteButton = () =>
  this.props.postActivity({
    type: 'messageReaction',
    reactionsAdded: [{ activityID: this.props.activityID, helpful: -1 }]
  });
```

https://github.com/microsoft/BotFramework-WebChat/blob/3cf5d9bef057920e7ab8812507d320441594e1de/samples/09.customization-reaction-buttons/index.html#L73

**Comment by compulim** [comment]
IMO, your Teams emoji design is targeting user-to-user conversation, but not user-to-bot conversation. So I don't think 80% or more users are going to benefit from this feature. Making this feature in production doesn't make sense to me.

The sample linked by @tdurnford makes sense to me because it is upvote/downvote button. It will benefit bot designers to get feedback about their bots. And this means it could benefit a larger number of users.

In your #2431, you mentioned React is not an option in your case. Web Chat support different tiers of customization. For this tier of customization (a.k.a. custom activity/attachment renderers), because of its complexity, it is only supported when using React. We won't be able to build this feature for you in JavaScript.

**Comment by Bradrajkumar** [comment]
@compulim  if you are not able to provide me the javascript solution please provide me the react code with the requirement i want i.e. feedback as well as reactions for every mesages rendering from bot side(if possible).

**FYI**
i tried adding feedback for the message using react and it rendering for only text responses, not for any rich responses. so is it possible that for all the responses the feedback option should render from bot side?
please do let me know if possible with required solution.
