### ISSUE TITLE
UI cards behavior change in V4

### ISSUE THREAD

**Issue by alokraj68** [microsoft/BotFramework-WebChat#2579]
## Screenshots
![image](https://user-images.githubusercontent.com/9208731/68475927-6ea1f080-024f-11ea-97e7-0f2e6a82c739.png)

## Version

4.6 Via CDN

## Describe the bug

In V3 Hero cards, there was no spacing between text and button action set. Now there is a visible gap between both and is treated as different objects. This is causing a major change in UI when upgrading from V3 to V4.

## To Reproduce

1. Go to any sample with Hero cards
2. Type a message with Hero card
3. See the changes marked in the screenshot attached.
4. Verify the same with V3

## Expected behavior

UI should be the same as V3. There should not be any gap between text and Action set buttons blobs. 

## Additional context

This is a major change when upgrading from V3

[Bug]

**Comment by compulim** [comment]
In v4, the design was updated and a gap was introduced to improve readability, especially on activities with multiple attachments.

From what I observed from your screenshot, could you try sending an Adaptive Cards instead of hero card? Adaptive Cards has very flexible content, thus, you can add title before an image and action buttons.

You can read more about Adaptive Cards here, https://adaptivecards.io/.
