### ISSUE TITLE
Change color of heroCard titles

### ISSUE THREAD

**Issue by BeschtPlaier** [microsoft/BotFramework-WebChat#2580]
hey, sorry if i am not into the guidelines, it is my first post here.
I am currently working on a qnabot and i am using it per direct line on the web.

I use HeroCards for some decisions and I am not able to change the font color of the heroCard title.

Would be nice if the whole HeroCard css stuff would be editable like the chatbubbles or the suggestedActions

**Comment by compulim** [comment]
We currently do not support customizing the color of hero card and all rich cards.

All rich cards are rendered using Adaptive Cards renderer. And the AC renderer generate complicated DOM tree. Thus, it's impossible to change the color of the title using CSS.

Since we generate hero card using Adaptive Cards, could you use Adaptive Cards instead? There is an option which you could use to specify color for different text block in the card.
