### ISSUE TITLE
Suggestive Actions within Waterfall Dialog not getting triggered ?

### ISSUE THREAD

**Issue by deepanigi** [microsoft/BotFramework-WebChat#2670]
## Screenshots
![image](https://user-images.githubusercontent.com/31543067/70235880-200b4780-1764-11ea-8f07-975eec249d7d.png)

## Version
4.6.0
Using directline to use in website

## Describe the bug
I am trying to trigger a waterfall dialog during the intro of the bot session. I want to show a few suggestive card options along with an intro and use waterfall to follow those steps. But unfortunately the begin dialog is not getting triggered or even no exception is trigged.

## Expected behavior

When I load the bot in the web I expect to see the bot greets me some suggestive card options

**Comment by tdurnford** [comment]
'How to' questions such as this one are better suited for Stack Overflow, and since you’ve already asked this question on Stack Overflow, I’m going to close this issue. One of the Bot Framework Support Engineers will help you address your [question](https://stackoverflow.com/questions/59198495/suggestive-actions-within-waterfall-dialog-not-getting-triggered?r=SearchResults) there.

**Comment by deepanigi** [comment]
@tdurnford  Thanks, I would request this issue to be opened here hoping to get some support from the community. I have raised this issue with Microsoft but still no resolution its been 2 months.
