### ISSUE TITLE
To use WebChat with complete on-premise deployment of Bot Framework

### ISSUE THREAD

**Issue by yogimogi** [microsoft/BotFramework-WebChat#2676]
Hello,
We want to have a 100% on-premise deployment of a MS Bot Framework based bot to be used with BotFramework-WebChat channel.
Consider we have written our bot using Python MS Bot Framework SDK. We were thinking of adding WebSocket support to Django based bot and BotFramework-WebChat can talk to this end-point as opposed to  directline.botframework.com.
Are there any plans/sample code where we can ask BotFramework-WebChat to talk to some other end-point as opposed to directline.botframework.com.
regards, Yogesh

**Comment by compulim** [comment]
Hi @yogimogi,

As long as you can write an adapter for your Django-based bot with the interface defined here ([`BotConnection`](https://github.com/microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L383)), you can pass it to Web Chat (as `directLine` option) and it will just work. You will need to translate from our `IActivity` to your message structure. Internally, we have few prototypes telling successful stories in this area. 😄

```js
export interface IBotConnection {
    connectionStatus$: BehaviorSubject<ConnectionStatus>,
    activity$: Observable<Activity>,
    end(): void,
    referenceGrammarId?: string,
    postActivity(activity: Activity): Observable<string>,
    getSessionId? : () => Observable<string>
}
```

We recommend using ES Observable (from `core-js`) instead of RxJS 5/6. One behavioral difference between RxJS `BehaviorSubject` vs. ES `Observable`: the RxJS version is a shared subscription, i.e. multiple subscribers share the same observer. In contrast, in ES Observable, every subscriber will have their own instance of observer.

Some tips (due to quirkiness of DLJS):

- Establish connection only when subscribe to `activity$`.
   - No-op when subscribe to `connectionStatus$`.
- After `postActivity`, the original activity should be posted to `activity$`. This is read receipt.
- We ignore the result from `postActivity`. This is send receipt, Web Chat don't care.
- `referenceGrammarId`, you can ignore this one. This is for Speech + LUIS.
- `getSessionId`, you can ignore this one until you implement OAuth card support.

FYI, we are planning to rebuild this API signature into a more easier consumption format so everyone can easily use Web Chat on their platform of choice. This is still in very early planning phase, no concrete plan yet. #2665 is trying to move DLJS-related work from Web Chat back to DLJS to clear up responsibilities and lay the road for this work. So don't count on us before working on your adapter.

If you want to know more about it, subscribe to #2665 first. We will have more work items when we start planning. 😉
