### ISSUE TITLE
Sample 21.customization-plain-ui is not working

### ISSUE THREAD

**Issue by joshm998** [microsoft/BotFramework-WebChat#2742]
## Screenshots

![image](https://user-images.githubusercontent.com/1779737/70966877-89844200-20e4-11ea-8f61-87fe8820bb9c.png)

## Version
4.5.1

## Describe the bug
Throws "m.hooks is undefined" and the sample does not load 

## Steps to reproduce

1. Go to 'https://microsoft.github.io/BotFramework-WebChat/21.customization-plain-ui/'
1. See blank page

## Expected behavior

Working plain UI webchat

## Additional context
Tried running the sample locally and still throws the same error

[Bug]

**Comment by samazadi** [comment]
@joshm998 get the latest for both the `botframework-webchat` and the `botframework-webchat-component` and it should resolve the missing hooks:

`npm i botframework-webchat@latest`
`npm i botframework-webchat-component@latest`

I found some issues with the sample like message not sending, but you can fix that directly in the code and it should be fine.

**Comment by corinagum** [comment]
This is fixed in latest bits as of last night. To verify, please clone Web Chat, follow the contributing instructions to build the repo, and use the `webchat.js` file in `/packages/bundle/dist/` to test. If you're still having problems, please leave another comment on this issue. At the moment I am able to build and run with no problems. :)

**Comment by joshm998** [comment]
Thanks its fixed now 🙂
