### ISSUE TITLE
bubbleNub stopped working

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#2779]
Yesterday I noticed that the bubbleNubs are not rendered anymore in webchat
I am using 'https://cdn.botframework.com/botframework-webchat/latest/webchat.js'

```
styleOptions:  {
            bubbleFromUserBackground: '#0063B1',
            bubbleFromUserBorderRadius: '8px 0px 8px 8px',
            bubbleFromUserBorderStyle: 'solid',
            bubbleFromUserBorderWidth: 1,
            bubbleFromUserTextColor: 'White',
            bubbleFromUserNubSize: 10,
            bubbleFromUserNubOffset:  0,
}
```
results in:

![image](https://user-images.githubusercontent.com/23032884/71582507-d0256380-2b0a-11ea-8cc2-01ceacf6fd27.png)

**Comment by cwhitten** [comment]
Hello @HesselWellema. Thank you for the issue. We'll investigate and report back.

**Comment by tdurnford** [comment]
@HesselWellema What version of Web Chat are you using? The Bubble Nub was introduced in v4.6, but the latest cdn is currently pointing to v4.5.3 due to an issue with DirectLineJs. This will probably be resolved after we rerelease v4.7.1.

You can add this code snippet to the script in the HTML file to check what version of Web Chat you are using.
```javascript
[].forEach.call(document.getElementsByTagName('meta'), ({ content, name }) => console.log(`${name}: ${content}`));

```
The resulting console log should look like this:

![image](https://user-images.githubusercontent.com/17039790/71706304-e21c3600-2d98-11ea-924b-e045a221f9e3.png)

**Comment by HesselWellema** [comment]
@tdurnford thank you It is pointing  at 4.5.3
Guess I just have to be patient.
Any ETA on 4.7.1 jou are willing to share with me?

**Comment by corinagum** [comment]
We don't have an ETA at this time. As a stop-gap, I recommend using the `webchat.js` file available in the release section of this repo. Once the patch goes out, you can switch back to the CDN so you continue to get the latest updates.

https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.7.1

**Comment by tdurnford** [comment]
The CDN has been updated to v4.7.1. Bubble Nubs should be working fine with the latest CDN.

**Comment by HesselWellema** [comment]
And it does. Thank you
