### ISSUE TITLE
Hiding The SendBox Hides Typing Animation

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#2871]
## Screenshots
None

## Version

CDN 4.7.1

## Describe the bug

In the webchat when **hideSendBox** option is set to false under **StyleOptions** to hide the **SendBox**, it hides the typing animation too.

## Steps to reproduce

1. Set **hideSendBox** option to **false** in StyleOptions.
2. Send Typing from bot.
3. Observe no typing animation is shown to the user.

## Expected behavior

If **hideSendBox** option is set to false in the **StyleOptions**, than typing animation should not be hidden.

**Comment by tdurnford** [comment]
@arman-g As you noticed, the typing indicator is contained in the send box, so hiding the send box will hide the typing indicator as well - this also true for the connectivity status and suggested actions. @compulim and I have discussed possibly moving the typing indicator to the transcript which would keep it from being hidden by the `hideSendBox` style option.

**Comment by arman-g** [comment]
Hi @tdurnford, yes I agree the typing indicator as well as the connectivity status should be outside of the sendbox. They are simply different things and have no direct relations with each other. This becomes a huge problem if chatbot uses adaptive/hero cards only. Hiding the sendbox by default hides other things too that has no connection to sendbox.

**Comment by corinagum** [comment]
Related to a couple of issues:
https://github.com/microsoft/BotFramework-WebChat/issues/2427 - move suggested actions out of send box so that hiding send box doesn't affect suggested actions
https://github.com/microsoft/BotFramework-WebChat/issues/2323 - create a notification center for the suggested actions typing indicator, and connectivity status separate from the sendbox
https://github.com/microsoft/BotFramework-WebChat/issues/1839 - study improvements to make on the send box component/cutomization
https://github.com/microsoft/BotFramework-WebChat/issues/2211 - changing sendbox to have multiple input modes

**Comment by arman-g** [comment]
@corinagum I hope this will get into near future releases.

**Comment by tdurnford** [comment]
@arman-g PR https://github.com/microsoft/BotFramework-WebChat/pull/2883 is adding a notification bar to Web Chat, and part of that work includes moving the typing indicator from the send box to the transcript. This should be resolved in our next release. Thanks for your patients.

**Comment by corinagum** [comment]
As far as I know #2883 is only adding a notification bar. Did yesterday's discussion include moving typing indicator and/or suggested actions?

**Comment by tdurnford** [comment]
@corinagum Yes, @compulim and I had an offline discussion about moving the typing indicator, and we recapped it again briefly in standup on Wednesday. You can also look at the changes #2883 is making to `basicTranscript.js` and `basicSendBox.js`

**Comment by corinagum** [comment]
@compulim need to add mention of these in the summary
