### ISSUE TITLE
cannot create websocket

### ISSUE THREAD

**Issue by jdwilkin** [Microsoft/BotFramework-WebChat#289]
The main symptom is when I pass true to the DirectLine websocket param and it attempts to create the websocket the operation fails.  After some shallow digging I discovered the streamUrl returned when creating a conversation is essentially just the path and it missing the protocol (ws://) and the domain bits.  I monkeyed with the code a bit to create the proper string with protocol and domain and the websocket creation succeeds, but this seems like a bug or I am missing something in my environment causing this...

**Comment by billba** [comment]
The problem here is that you registered your bot to use WebChat (the official hosted version of this project) and not DirectLine. You need to do the latter and use the secrets it gives you. At the moment using WebChat secrets for this control is just buggy; shortly they will not work at all.

I acknowledge that the naming makes this very confusing and error-prone indeed.
