### ISSUE TITLE
Adaptive Card Input Hint property not working

### ISSUE THREAD

**Issue by manish-95** [microsoft/BotFramework-WebChat#2893]
## Version
4.7

## Describe the bug
I have an adaptive card for which I am setting the inputHint value as "expectingInput". However, the mic is not automatically turned on, after the adaptive card speak property text is spoken.

## Expected behavior
WebChat has to respect the inputHint property of the adaptive card and turn on the mic once the speech has ended.

## Additional context

We are using the WebChat js locally file with Angular, and have made a small change to address issue #2560

**Comment by prashanthsridhar** [comment]
I am facing the same issue too

**Comment by clearab** [comment]
@compulim & @tdurnford: Can one of you please take a look at this?

**Comment by tdurnford** [comment]
@manish-95 It looks like everything is working as expected. Per the [Input Hint](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/SPEECH.md#using-input-hint) section in the Speech Documentation, the microphone should only open if the last message from the user was sent using the microphone.

> The bot can set input hint when sending activity to the user to indicate whether the bot is anticipating user input. This can be used to re-open the microphone if the last message was sent through microphone.

If you use the microphone to send a message to bot and the bot responds with an activity with the `inputHint` set to `'expectingInput'`, the microphone should open. Otherwise, the microphone should remain closed.

**Comment by manish-95** [comment]
@tdurnford My requirement is to turn on the mic after the welcome adaptive card, before the user has had a chance to previously use the mic.
