### ISSUE TITLE
How to Add Autosuggestion/Autocomplete in Bot framework Web-chat using React js?

### ISSUE THREAD

**Issue by thomas023** [microsoft/BotFramework-WebChat#2919]
I want to implement autosuggestion whenever i type something to the input area of my web-chat. It should fetch data from my azure table. I'm using react js as my front end and .net core as back end to generate token and calling bot-framework web-chat to the front end. How to add autosuggestion to this?

**Comment by v-kydela** [comment]
Hello @thomas023 - I understand that you'd like more help with this issue: https://stackoverflow.com/questions/60223610/how-to-add-autocomplete-autosuggestion-in-microsoft-botframework-webchat-using-r/60271292

I'm happy to help if you let me know what information you need that hasn't already been provided. If I've already answered the question and you have more questions, feel free to post more questions that explain what you're now having trouble with. I'll go ahead and close this issue so that your questions can be handled on Stack Overflow.

Related: https://github.com/microsoft/BotFramework-WebChat/issues/476

**Comment by thomas023** [comment]
Hi kyle, for your understanding please find the code i used for React, that is attached above with the question. What i'm trying is to implement autosuggestion whenever i type something to the input area of my web-chat. It should fetch data from my azure table. I'm using react js as my front end and .net core as back end to generate token for calling bot-framework web-chat to the front end. The bot is working fine but i want to do some customization's and for that i'm trying to do this. Is there any builtin feature in bot-framework to add autosuggestion?

[](https://cloud.githubusercontent.com/assets/597759/26473832/21c6c826-41e0-11e7-855d-945aec2bff87.png)

**Comment by v-kydela** [comment]
> Is there any builtin feature in bot-framework to add autosuggestion?

No, there is not. Please refer to the linked issue for more information.
