### ISSUE TITLE
WebChat does not pass locale property with conversationUpdate activity

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/BotFramework-WebChat#2930]
## Screenshots
![image](https://user-images.githubusercontent.com/20775323/74983216-389e0c00-53fb-11ea-904c-de02c933f1ea.png)

## Version
CDN 4.7.1

## Describe the bug
Locale property is set to null for conversationUpdate activity being sent to the bot. This results in welcome message being displayed in default language, instead of the language being passed to WebChat.createDirectLine:

          window.WebChat.renderWebChat({
            directLine: window.WebChat.createDirectLine({ token }),
            styleOptions: {
               hideUploadButton: true
            },
            locale: "es-ES",
            store
            },
            document.getElementById('webchat')
          );

## Steps to reproduce

1. Deploy VA bot with WebChat
2. Change locale in the WebChat to es-ES
3. Open chat page
Welcome message is displayed in English, all subsequent communication switches to Spanish.

## Expected behavior
Welcome message is displayed in Spanish

## Additional context
Note, this works as expected with BF Emulator and corresponding property is set to correct locale on the conversationUpdate activity.

[Bug]

**Comment by tdurnford** [comment]
@turbozapekanka The Direct Line Connector Service is responsible for sending the conversation update event to the bot when the conversation is established, and unfortunately, when the service sends the conversation update event it does not have access to the locale.

I would recommend sending a backchannel welcome event when the Direct Line Connection is fulfilled and sending the welcome message from the event handler instead of the on members added handler if you want to localize the welcome message. I would recommend looking at [Backchannel Welcome Event](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event) Web Chat sample for more details.

**Comment by turbozapekanka** [comment]
@tdurnford looks like a workaround.
Why not pass the locale over to the Direct Line Connector Service?

**Comment by tdurnford** [comment]
@turbozapekanka Correct, this is a workaround. Fixing this would require a change to the [BotBframework Services](https://github.com/microsoft/botframework-services), I don't believe they have this as a priority on their timeline.

**Comment by dstvishnu** [comment]
@tdurnford Is it because of the directline?

**Comment by tdurnford** [comment]
Yes, this is an issue with DirectLine

**Comment by martinoss** [comment]
With [DirectLineJs 0.13.0][1], a property has been added that allows to specify the start locale like this:


  [1]: https://github.com/microsoft/BotFramework-DirectLineJS/pull/293

    ...
    createDirectLine({
      token: tokenResponse.token,
      domain: `https://europe.directline.botframework.com/v3/directline`,
      pollingInterval: 500,
      conversationStartProperties: {
        locale : "fr"
      },
      watermark: "-",
    })
