### ISSUE TITLE
Serve is not recognized as a command

### ISSUE THREAD

**Issue by asifshiraz** [microsoft/BotFramework-WebChat#3006]
## Describe the bug

I cloned the repository, ran 'npm install' and 'npm start'. I'm getting following error:
PS D:\BotFramework-WebChat> npm start

> botframework-webchat-root@4.7.2-0 start D:\personal\projects\MatchMakers\MatchMakers2\BotFramework-WebChat
> concurrently --kill-others --raw "serve" "lerna run --ignore playground --parallel --stream start"

'serve' is not recognized as an internal or external command,

## Steps to reproduce

1. Clone repository
2. Run npm install
3. Run npm start

[Bug]

**Comment by tdurnford** [comment]
@asifshiraz Thank you for reporting this issue. It looks like the `serve` npm package is missing as a dev dependency. @compulim @corinagum We should consider adding `serve` as a dev dependency or changing the start command to use `npx serve` instead of just `serve`.

```diff
- "start": "concurrently --kill-others --raw \"serve\" \"lerna run --ignore playground --parallel --stream start\"",
+ "start": "concurrently --kill-others --raw \"npx serve\" \"lerna run --ignore playground --parallel --stream start\"",
```

https://github.com/microsoft/BotFramework-WebChat/blob/6f0ae7a73530915c4e19db0234ad824b295c4b6b/package.json#L42

**Comment by corinagum** [comment]
adding as a dev dependency approved by compulim :)
