### ISSUE TITLE
Getting a token

### ISSUE THREAD

**Issue by McGern** [Microsoft/BotFramework-WebChat#301]
Hi,

Just looking for some instructions/guidance for the correct flow for getting tokens. If the token is to go in the querystring, at what point am I getting the token and how do I get it into the querystring?

I have an iframe which points to the index.html file, which for my test has the secret key in the querystring. For the production version, I don't know how to apply the token in a manner that doesn't expose the secret to the client.

I have a simple node server setup to host the webchat files (which incidentally is the same server that host the bot api endpoint - is that a bad thing?)

Also, does the directLine library included in the webchat automatically refresh the token internally or is that something the developer needs to do?

Thanks very much for your time,
Jarrod

**Comment by McGern** [comment]
I think I have solved a bit of it, but not sure if it's the right thing.

On my (node) server, I have a route e.g. "/webchat" which call a function to get a token (the secret key is on the server). In the route there is a redirect to index.html?t=[token]

It seems to work, but don't know if this is a good way to do it.

Also am still unsure where the token expire/refresh is happening.

**Comment by billba** [comment]
I'm working on a docs rewrite which will make this stuff clearer. Briefly:

1. The only reason you need tokens is if you want to control access to your bot. Publishing your secret on your web page allows anyone to communicate with it with any Direct Line client.
2. So a common pattern is to have your own web service (can absolutely be the same service as the bot) that holds the secret and publishes an API that spits out tokens. Your web page would call that service to get tokens, then uses that token when creating the WebChat.
3. But if that web service isn't secure, then anyone can use it. So this only really makes sense if there's some kind of authentication going on, although it's still better than nothing because you can always turn off your web service to deny access to the bot.
4. Redirecting to the WebChat index.html is a clever idea, but that limits you to the IFRAME implementation.
5. WebChat refreshes the token every 15 minutes.

Hope this helps. I'll keep this issue open until I've revised the docs.

**Comment by McGern** [comment]
Thanks again Bill. All of your help on my various questions has been great.

**Comment by billba** [comment]
I have updated the README and hopefully this is somewhat clearer now.
