### ISSUE TITLE
Check if web chat has received conversation history from directline

### ISSUE THREAD

**Issue by jriley15** [microsoft/BotFramework-WebChat#3101]
I'm currently working on a feature for my companies react app where we want a search bar on the landing page of the site to enter a message into the botframework-webchat component. The problem I'm running into is that in some scenarios the webchat hasn't been rendered yet - so I'm looking for some sort of redux action or directline event that I could tap into with middleware that would most reliably indicate when the webchat has received the initial conversation history from directline - that way when the we send the message in from the search bar on the home page it doesn't show up in the conversation history as the first message. I'm currently using the `DIRECT_LINE/INCOMING_ACTIVITY` action and setting a 500ms timeout as a hacky way to ensure that the webchat has received the conversation history before pushing the users search text into the bot via `WEB_CHAT/SEND_MESSAGE`. Is there a better way of doing this?

**Comment by v-kydela** [comment]
Thank you for the question, @jriley15 

Can you explain when you say "webchat has received the initial conversation history from directline"? Are you talking about some kind of welcome message, or is your Web Chat resuming a conversation in progress when they had already been talking to the bot? Is the bot sending the transcripts to Web Chat using [Send Conversation History](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference#send-conversation-history) or is the history being stored on the client side?

**Comment by jriley15** [comment]
Yeah so we grab a token for the existing conversation (if the user had started a conversation already) with this [](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation?view=azure-bot-service-4.0#generate-a-new-websocket-stream-url) and pass that directline token to the webchat component which then receives the full transcripts after connecting to directline. We also have a welcome message but that one isn't really an issue - having the transcripts being sent for a pre-existing conversation is the real issue.

**Comment by v-kydela** [comment]
@jriley15 - I'm not sure how to reproduce your issue since I don't see your code, but here are a few things you can try.

1. If you want to respond to a Redux action like you said, you can try an action that fires when Web Chat connects like `DIRECT_LINE/CONNECT_FULFILLED` or `DIRECT_LINE/CONNECTION_STATUS_UPDATE` or `DIRECT_LINE/UPDATE_CONNECTION_STATUS`, you can try an action specifically associated with reconnecting like `DIRECT_LINE/RECONNECT_FULFILLED`, or you can try an action that represents the conversation history being posted like `DIRECT_LINE/INCOMING_ACTIVITY` or `DIRECT_LINE/POST_ACTIVITY_FULFILLED`. You can see the actions available to you here: https://github.com/microsoft/BotFramework-WebChat/tree/master/packages/core/src/actions
2. You might also consider dispatching `WEB_CHAT/SET_SEND_BOX` yourself to put your desired text in the send box for the user to send when they're ready instead of sending it automatically.

Does this resolve your issue?

**Comment by jriley15** [comment]
@v-kydela yes, this helps. Thank you.
