### ISSUE TITLE
send welcome message in react webchat

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#3109]
hi all,

when i have implemented the webchat using react and also added the code for backchannel sending some data to the bot as event.
1. here i am facing a situation that event is not triggering at all.
2. if i am just typing something from webchat(not yet sent from webchat) it is triggering to 
   OnMembersAddedAsync and reply is coming from bot.
3. one more thing i noticed that channel id is adding as "webchat" not as "directline".
4. In react webchat i am using directline secret not the webchat secret.

is that something i am doing wrong here.if it is wrong what approach i should try.
does react webchat, directline and emulator works different in context of sending event. please provide me a legit information regarding this.

**Comment by compulim** [comment]
### For your points

(Thanks for using point form, making it super easy to answer. 😉)

1. `conversationStart` activity may not send if the user ID is not "burnt" into the token.
   - Please follow instructions here to "burn" the user ID into the token, https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0
   - If not "burnt", `conversationStart` activity only send on first activity from user.
   - If "burnt", `conversationStart` activity should send when Web Chat connect.
1. This is because when user type, we send `typing` activity to the channel. The channel will send `conversationStart` activity only when the user send any activity, this include `typing` activity.
1. I just tried and use both Web Chat secret and token, I am seeing `channelId` set to `webchat`.
   - If I am using DL secret/token, I am seeing the `channelId` set to `directline`
1. (This is same as point 3)

### Using secret/token from Web Chat channel

![image](https://user-images.githubusercontent.com/1622400/79595245-58684e00-8093-11ea-84ca-b06a86a583f3.png)

### Using secret/token from Direct Line channel

![image](https://user-images.githubusercontent.com/1622400/79594772-839e6d80-8092-11ea-8361-1d35545918f4.png)

**Comment by Bradrajkumar** [comment]
hi @compulim ,

its quite confusing me to understand these.
1. Is react webchat is using the webchat as a channel or directline as a channel?
2. if react is using webchat as channel and i am using directline secret key on place of webchat secret key then how server side code will react for sending event(as  i am seeing that if i am sending the event activity from directline and non-react webchat then event is triggering just after conversation update happens, but  if i am using directline secret and react webchat it is not triggering the event).

please comment on this.
