### ISSUE TITLE
Adaptive Cards doesn't render Input.Number - values

### ISSUE THREAD

**Issue by MatthiasGwiozda** [microsoft/BotFramework-WebChat#3111]
## Screenshots
**Activity:**

![activity_card_field](https://user-images.githubusercontent.com/22172694/74517415-5b6b8480-4f12-11ea-989f-aa50fe9bb1b1.png)
**result:**

![inputField](https://user-images.githubusercontent.com/22172694/74517413-5ad2ee00-4f12-11ea-9b2d-36160090220d.png)

**expected result:**

![inputField_2](https://user-images.githubusercontent.com/22172694/74517649-cb7a0a80-4f12-11ea-8a59-02309cf19d94.png)

## Version
 **4.7.1** (downloaded from [CDN](https://cdn.botframework.com/botframework-webchat/latest/webchat.js)
(In Version 4.5.2 this issue didn't occur.)

## Describe the bug

When the webchat renders an activity with Input.Number, the value that should be rendered isn't shown.

## Steps to reproduce
Create a Card with a default - Value in Input.Number and send it to the Webchat.
This Issue is not happening in the Emulator. So it should be a Bug in the Webchat itself.

**Comment by compulim** [comment]
Tracking bug at https://github.com/microsoft/AdaptiveCards/issues/3829.

It is not fixed in `1.2.5`.

**Comment by tonyanziano** [comment]
Currently blocked on [Adaptive Cards bug #3829](https://github.com/microsoft/AdaptiveCards/issues/3829). Follow the status of that bug there.

**Comment by compulim** [comment]
Done some investigations today, tl;dr reinforcing what we believe:

1. Bot send the JSON out to the channel, with `value` property of `string`
1. The channel converted the `value` property into `number`
1. Web Chat receive the `value` property as number and send it to `AdaptiveCard.parse()`
1. `AdaptiveCard.parse()` returned with a structure of `value` equals to `undefined`

We try to hack the code in point 3. Web Chat change the `value` property from type number to string. The `AdaptiveCard.parse()` is able to return a structure with `value` of type number.

So, this is outside of what Web Chat could do. This is because the channel is not returning something (number) that the `AdaptiveCard.parse()` is expecting (string). The mismatch of data type is causing data loss.

Either one or both parties need to fix:

1. The service will return value of type string
2. `AdaptiveCard.parse()` will accept value of type number

**Comment by corinagum** [comment]
Per https://github.com/microsoft/AdaptiveCards/issues/3829, this is no longer blocked and requires Web Chat to update to AC 2.x. That work can be tracked at: https://github.com/microsoft/BotFramework-WebChat/issues/3392
