### ISSUE TITLE
The links to samples don't work (since yesterday?)

### ISSUE THREAD

**Issue by raresv** [microsoft/BotFramework-WebChat#3128]
The links to view the actual sample are not working (404).
samples page here:
https://github.com/microsoft/BotFramework-WebChat/tree/master/samples
Example of link not working:
https://microsoft.github.io/BotFramework-WebChat/01.getting-started/h.minimal-markdown

**Comment by tonyanziano** [comment]
Hi @raresv ,

Could you please take a screenshot of your browser window so that we can see what the issue is that you are facing?

I just tried to open the link you posted and it is working for me:

![image](https://user-images.githubusercontent.com/3452012/80249889-84517980-8627-11ea-808e-5f3044692675.png)

**Comment by compulim** [comment]
Thanks for reporting. I fixed it this morning. Weird to see from time to time the GitHub Pages get reverted.

**Comment by raresv** [comment]
Thank you!
