### ISSUE TITLE
Local time format in French (fr-CA) wrong

### ISSUE THREAD

**Issue by UncleZen** [microsoft/BotFramework-WebChat#3144]
## Version

Using CDN v. 4.8.1
https://cdn.botframework.com/botframework-webchat/latest/webchat.js

## Describe the bug

When locale set to fr-CA, the time portion is being formatted as 3:35 PM which is obviously wrong

## Expected behavior

Display the time using 24-hour notation. I.e. instead of 4 mai à 3:35 PM display 4 mai à 15h 35. 

## Additional context

See the attachment.

![webchat_time_format_issue](https://user-images.githubusercontent.com/485880/81006139-01959f00-8e1d-11ea-8647-e2f3e215a9d1.png)

**Comment by compulim** [comment]
This is expected because Web Chat is not localized in `fr-CA` specifically. When an unknown language is selected, it will fallback to closest it can get, `fr-FR`.

For internationalization (unit and date/time formatting), we use a library called `globalize` and it use Unicode CLDR, the official internationalization database.

Please follow the [documentation on adding a new language](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/LOCALIZATION.md#adding-a-new-language).

**Comment by UncleZen** [comment]
@compulim 
Is it possible to override the timestamp format string when rendering webchat, like:

```
window.WebChat.renderWebChat(
  {
    locale: 'en-US',

    overrideLocalizedStrings: (strings, language) => ({
      ...strings,
      TEXT_INPUT_PLACEHOLDER: 'What is on your mind?'
    }),
  },
  document.getElementById('webchat')
);
```

Thanks!
