### ISSUE TITLE
Web page / direct URL does not render cards and prompts

### ISSUE THREAD

**Issue by bdlawrence13** [microsoft/BotFramework-WebChat#3153]
🚨 The issue tracker is not for implementation questions 🚨

When I run my bot in the bot emulator or the test web chat in the Azure portal, the initial card, information, and prompts come up. However, when I run either through the direct URL or from a web app I've published, the first screen is just a "Type your message" prompt and the user has to type something to get the opening card and prompts to display. What am I missing? I've looked all over to try and find some command or parameter that tells the  bot to go and show the opening dialog, but I can't find anything.

**Comment by cleemullins** [comment]
@v-kydela Could you take a look?

**Comment by v-kydela** [comment]
@bdlawrence13 - We have a sample that shows how to provide a welcome message in Web Chat: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/a.welcome-event

Does this resolve your issue?

**Comment by bdlawrence13** [comment]
Not really. I’m pretty new to these. I’m using a sample bot - #13 – Core bot. And sorry, but this phrase in #4:

On your bot, you will need to add a filter to post the welcome message when webchat/join activities are detected.
Mock Bot welcome message:
if (context.activity.name === 'webchat/join') {
  await context.sendActivity(
    `Got \`webchat/join\` event, your language is \`${(context.activity.value || {}).language}\``
  );
}


I don’t have a clue as to where this would be added or how it fits in/replaces the already existing welcome screen.

That sample is built on using a set of cards that should display immediately, but only do if called through Bot Emulator or Test Web Chat.


[cid:image001.png@01D62927.24540DC0]
Brian Lawrence | DWC Solution Architect
3M Health Care, Medical Solutions Division
12930 W. Interstate 10 | San Antonio, TX 78249 | US
Mobile: +1 210-291-4170
brian.lawrence@acelity.com<mailto:brian.lawrence@acelity.com>  |  3M.com/KCI<https://acelity.us.newsweaver.com/11irq2v8ry/3M.com/KCI>
[https://acelity.us.newsweaver.com/files/201/1002105/1021125/194399/bf8606e37335fb7b9da414ea/twitter.png]<https://twitter.com/3MHealthCare?s=20>[https://acelity.us.newsweaver.com/files/201/1002105/1021125/194399/15d04ac8206324fcb3bed0bb/linkedin.png]<https://www.linkedin.com/showcase/3m-health-care/>[https://acelity.us.newsweaver.com/files/201/1002105/1021125/194399/891aaa286cf0c877892e6a7b/facebook.png]<https://www.facebook.com/3MHealthCare/>[https://acelity.us.newsweaver.com/files/201/1002105/1021125/194399/bea95cc9003cf45459e8d4bd/instagram.png]<https://www.instagram.com/3m/>[https://acelity.us.newsweaver.com/files/201/1002105/1021125/194399/6cf95d4e47c26d18bcb799a8/youtube.png]<https://www.youtube.com/user/3MSkinWound>[https://acelity.us.newsweaver.com/files/201/1002105/1021125/194399/b38a3e1c0bde6d1c3cdd4182/3m%20logo%20small.png]<https://acelity.us.newsweaver.com/11irq2v8ry/hzyuvsnxidg?a=6&p=1635141&t=705607>

**Comment by v-kydela** [comment]
Hi @bdlawrence13 

I want to clear up some possible confusion. While the Web Chat sample I linked to you is sample 4a, you need to understand that the Web Chat samples are totally separate from the Bot Builder samples and use a different numbering system. The Core Bot sample is Bot Builder sample 13 and not Web Chat sample 13, and the welcome event sample is Web Chat sample 4a and not Bot Builder sample 4a. It's important to understand that the Web Chat samples show you what you need to do while coding your Web Chat client, and that's a separate thing from coding your bot.

To address the issue of where to put the bot code, you can see the Core Bot code that handles a conversation update by sending a welcome message here: https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/13.core-bot/bots/dialogAndWelcomeBot.js

You want to handles a webchat/join event instead of a conversation update. So instead of `onMembersAdded` you can use `onEvent` or `onTurn` and put the code from the Web Chat sample in there.

Because the Bot Builder SDK comes in multiple programming languages, the Bot Builder SDK samples come in multiple programming languages. I linked to the JavaScript Core Bot sample but I don't know if you're coding your bot in JavaScript. If you would like to help us help you then it would be a good idea to always post links to the things you're talking about. If you had linked to the Core Bot sample you're using then we'd know what language you're writing your bot in.

If you would like to gain a better understanding of how to build a bot, please feel free to review the documentation: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics

(It would be appreciated if you could reply on GitHub instead of email so that your comments will be Markdown-enabled)

**Comment by bdlawrence13** [comment]
Got things to work. Thank you for taking the time to point me to the information needed.

**Comment by v-kydela** [comment]
I'm glad to hear it. Closing now.
