### ISSUE TITLE
Synchronized Voice and Text via Webchat

### ISSUE THREAD

**Issue by Amintasn** [microsoft/BotFramework-WebChat#3159]
## Synchronized Voice and Text via Webchat
I'm using Direct Line, MS Speech Service and Webchat on bot running on Botframework V4.
The application is fully voice based and is working fine.
However, the text and voice motion is not in sync.
In other words, after the first text+voice interaction, the next text is displayed before the previous speech service has been finished - so on and so forth.
Hence, voice is always delayed in relation to the text motion.
I was wondering if webchat.js would be able to automatically orchestrate that or there is another way to accomplish it.
Thx in advance.

[Enhancement]

**Comment by compulim** [comment]
Do you mean?

1. Bot send a response with speech > 5s
2. After 2s, the bot send another response with speech

As the speech of first response took > 5s to complete, the text of the second response will arrive sooner (after ~2s). And the second response show on the screen as soon as it arrive.

Can you confirm my explanation above match your description?

**Comment by Amintasn** [comment]
Thx for you usual support @compulim 
We have variable speech times actually.
Some are >5s some are <5s.
The point is text messages keep coming before the speech service has finished speaking which generates out-of-sync motion.
Hope it helped to clarify your question.

**Comment by Amintasn** [comment]
Hi @compulim, just wondering if you have any update or advice about this case. Thx!

**Comment by a-b-r-o-w-n** [comment]
@compulim do you have any guidance on this?

**Comment by compulim** [comment]
@Amintasn sorry for late response.

This is by design. Because, the speech engine should not interrupt the speech until they are fully spoken. Otherwise, a bot sending 2 responses rapidly (< 1s of each other), the first response will be missing from synthesis.

This design also align with screen reader live region (`aria-live="polite"`), which don't interrupt but add the sentence to the queue.

Could you use the "speak" property to shorten the spoken sentence while displaying a longer version?
