### ISSUE TITLE
Card image is not displayed in WebChat (but works in Emulator)

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/BotFramework-WebChat#3166]
I guess this is self-explanatory,
Not sure if there is any limitation on the image size. The image size is ~70kb

Card image:
<img width="308" alt="CardImage" src="https://user-images.githubusercontent.com/20775323/82258447-7e497280-991f-11ea-8ba6-e7b19a1819c7.png">

Screenshot below:

WebChat:
![image](https://user-images.githubusercontent.com/20775323/82258185-febba380-991e-11ea-91d7-c0d55d7c246e.png)

Emulator (as expected):
![image](https://user-images.githubusercontent.com/20775323/82258227-1004b000-991f-11ea-9326-bf921b318794.png)

**Comment by compulim** [comment]
There is no limit on image size.

Can you share the Adaptive Card with a working public URL to the image?

And can you check F12 and network tab to see if it is fetching the image?

**Comment by turbozapekanka** [comment]
It is NOT fetching the image.
here is the card from LG file:

[card.lg.txt](https://github.com/microsoft/BotFramework-WebChat/files/4651267/card.lg.txt)

**Comment by v-kydela** [comment]
@turbozapekanka - We can see that you're trying to embed the image. You should only do that for very small images. When in doubt, always use uploaded images. Direct Line has a limit on how big your activity can be, and it works in Emulator because Emulator bypasses Direct Line.

Does this resolve your issue?

**Comment by compulim** [comment]
Thanks @turbozapekanka.

It seems DL channel (the services) stripped out that particular string when the content is too large.

For example, when the production bot (not Emulator) send the AC card to Web Chat, the network traffic have the image `content` stripped.

@v-kydela can you follow up with the channel team? Or transfer the bug to `botframework-services`?

#### Content of `card.lg.json` by the customer

![image](https://user-images.githubusercontent.com/1622400/82511152-627dd200-9ac1-11ea-84cd-10a2b1f449dd.png)

#### Content received from Direct Line channel (Web Socket)

![image](https://user-images.githubusercontent.com/1622400/82511001-f00cf200-9ac0-11ea-8b23-de4bfae9e09d.png)

**Comment by turbozapekanka** [comment]
I'm fine with placing the image on a website.
Does it take relative URLs by any chance?
p.s. what is the size limit for embedded images?

**Comment by v-kydela** [comment]
Hello @compulim - can you explain what you want me to say to the channel team? And I'm sorry but you'd have to be the one to transfer this issue because I've lost my permissions.

@turbozapekanka - yes, you would use the image URL. And there is no size limit for embedded images. There is a size limit for activities, which is why you don't want image data expanding the activities. See [here](https://docs.microsoft.com/da-dk/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference#activities):

> The total size of the activity, when serialized to JSON and encrypted, must not exceed 256K characters. Therefore it is recommended that activities are kept under 150K. If more data is needed consider breaking the activity into multiple and/or consider using attachments.

Does this resolve your issue?

**Comment by turbozapekanka** [comment]
Thanks!
Yes you can close this. I will use hosted image.

**Comment by compulim** [comment]
@v-kydela I don't have permissions either. 😂

Few things:
- The card the customer presented is valid, sized 97.8 kB, and well under the limit of 150 kB
- If the card is considered erroneous to handle due to its size, the whole card should be discarded and an error must be raised to the bot
   - We are seeing only part of the card is discarded, this is considered *both* "user data loss" and "silent error"

Thanks @turbozapekanka for reporting. We will keep this issue open and transfer to the services team to follow up.

**Comment by compulim** [comment]
I filed the bug, https://github.com/microsoft/BotFramework-Services/issues/214. Will close this one now.

@turbozapekanka if you are interested in tracking the bug, please subscribe to the bug.
