### ISSUE TITLE
Add Custom Background Image to Webchat Using StyleSet

### ISSUE THREAD

**Issue by akamwand** [microsoft/BotFramework-WebChat#3202]
I have been trying to add a custom background image to the webchat window using StyleSet, however, I've had no luck using styleSet as so:

`styleSet.activities = {
...styleSet.activities,
backgroundImage: "url('myURL')" } `

While I realize styleSet may break with WebChat updates, I am just curious whether adding a background image to webchat is possible, and how so if it is?

**Comment by stevkan** [comment]
@akamwand, presently `backgroundImage` isn't a supported property in either `styleSet` or `styleOptions` (reference [here](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/StyleSet/Root.js)). If you feel this should be added as a feature, you can suggest it as a [feature request](https://github.com/microsoft/BotFramework-WebChat/issues/new?assignees=&labels=Enhancement%2C+Pending%2C+customer-reported%2C+Bot+Services&template=feature_request.md&title=).

In the meantime, the only way to change the background image is directly thru CSS (see below). The element in question doesn't include an `id` and the classes are subject to change, so they cannot be relied upon. The "best" option is to target via the element's assigned role. At this moment, it appears that only one element has the "complementary" role assigned to it. Should that change, you will need to parse the elements to get the correct one.

Please bare in mind, your code will be subject to the same conditions as using `styleSet` (i.e. breaking changes due to Web Chat updates).

```css
div[role=complementary] {
  background-image: url('<<YOUR_URL');
}
```

Closing this as resolved.
