### ISSUE TITLE
[HTML/CSS]Drop-down menu style in AdapativeCards is not configurable enough

### ISSUE THREAD

**Issue by sazarghani** [microsoft/BotFramework-WebChat#3208]
# Platform

* .NET HTML
botframework-directlinejs

# Version of SDK

"Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.8.0"
"botframework-directlinejs": Version="0.11.6",

# Summary
The select/option method used by directlinejs to represent the drop-down items of AdaptiveCards is not the best choice for styling using CSS. One cannot change the hover style of items uniformly for all web browsers. (option:hover has no effect in most Web browsers) 
Could you please use ul/li, for example, instead? 
**We are frustrated** as we must change the colors (hover style, which is currently a blue background and white text color) to make them consistent with our company color scheme, but there seems to be no way to that. 

# Details

We create adaptive cards containing drop-down menus in our .net core back end:
```
{
    "type": "Container",
    "items": [
        {
            "type": "Input.ChoiceSet",
            "id": "CountryCode",
            "value": "DE",
            "choices": [                        
                { "title": "Austria", "value": "AT" },
                { "title": "Belgium", "value": "BE" },
                { "title": "Bulgaria", "value": "BG" },
                ...
            ],
            "separator": true,
            "wrap": true
        }
    ]
}
```
Our Angular 8 based UI establishes a connection using directline and creates a chat window.The 
 dropdown items are representted by the directlinejs as select/option:

``` 
<select class="ac-input ac-multichoiceInput ac-choiceSetInput-compact" style="width: 100%; min-width: 0px;">
<option disabled="" hidden="" value=""></option>
<option value="AT" aria-label="Austria">Austria</option>
<option value="BE" aria-label="Belgium">Belgium</option>
...
</select>
```

It shows a blue background on the items as we hover the mouse on them. We have to change the blue background as well as the text color to be consistent with our company color scheme. 
There seems to be no way to control the option:hover style using CSS. for example, 
```
.ac-choiceSetInput-compact option:hover {
  background-color: red;
  color: yellow;
} 
```
has no effect in Chrome or Firefox.

**Comment by v-kydela** [comment]
@sazarghani - Thank you for the feedback. If you would like to raise an issue with DirectLineJS, the DirectLineJS repo is here: https://github.com/microsoft/BotFramework-DirectLineJS

This doesn't appear to have anything to do with DirectLineJS, however. DirectLineJS doesn't know anything about Adaptive Cards so it's certainly not in charge of rendering them. Web Chat does know about Adaptive Cards, but it delegates the actual rendering to the Adaptive Cards package. You had already posted this issue in the Adaptive Cards repo, so it's very unclear why you thought this issue was more appropriate for Web Chat.

I want to clear up some possible confusion. When you author an Adaptive Card, you do not add drop-down menus to it because a choice set is not a drop-down menu. A choice set is an abstraction that a renderer can choose to render however it likes. It is up to the renderer whether it wants to represent that choice set as a drop-down menu or something else. See my blog post for more information: https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/

Since Web Chat does indeed render choice sets as drop-down menus, I'll say that it looks like styling the hover events for select/option elements is very tricky. There are Stack Overflow posts that offer some advice:

- https://stackoverflow.com/questions/2402146/html-select-selected-option-background-color-css-style
- https://stackoverflow.com/questions/10484053/change-select-list-option-background-colour-on-hover

The easiest thing for you to do would be to set the [`style`](https://adaptivecards.io/explorer/Input.ChoiceSet.html) to "expanded" so that the choice set would be rendered as option buttons instead of a drop-down menu. This might be easier for you to style.

A more difficult solution would be to write your own custom element and include that in the card: https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/extensibility

Since this is largely outside the scope of the Web Chat repo, I'm closing this issue now.
