### ISSUE TITLE
How to apply NubOffset and NubSize to adaptivecards or hero card?

### ISSUE THREAD

**Issue by sudip2805** [microsoft/BotFramework-WebChat#3229]
Hi,
Could anyone suggest, how to apply NubOffset and NubSize to adaptivecards or hero card in SDK4 botframework. Help from any one will be appreciable.

Thanks in advance

**Comment by v-kydela** [comment]
Thank you for the question, @sudip2805 

We do prefer to have how-to questions asked on [Stack Overflow](https://stackoverflow.com/questions/ask) instead of GitHub. This reaches a larger audience, allowing more people to possibly answer the question and more people to be helped by the answer. If you use the [`botframework`](https://stackoverflow.com/questions/tagged/botframework) tag then my team will be sure to see the question.

If you would still like to get help here, can you show us what you've tried so far so that we can understand what part you need help with?

**Comment by compulim** [comment]
Adaptive Cards are *attachment* and is not a message bubble. Thus, bubble nub do not applies to them.

Attachment is not something "mentioned" by the user, but something "attached along side with the mentions".
