### ISSUE TITLE
Links in bot issue creeps up again

### ISSUE THREAD

**Issue by carlosrsolis** [microsoft/BotFramework-WebChat#3254]
Today we have started observing an issue that was reported here back in 2017.  Links added through markdown have started opening inside of the bot.

**Comment by v-kydela** [comment]
@carlosrsolis - Would you kindly provide all relevant links?

**Comment by vishwacsena** [comment]
@carlosrsolis can you please provide a crisp repro or a link to your old bug so we can investigate? Thanks.

**Comment by carlosrsolis** [comment]
@v-kydela and @vishwacsena Thanks for the answer.  we have coded a tag now that forces links to open into a new window, but as my initial post indicated, when we added links in the answers, and the user clicked on the link, it started opening inside the bot dialog, instead to opening in a new window, which was the previously observed behavior.

**Comment by v-kydela** [comment]
@carlosrsolis - We're asking you to post hyperlinks right here in your GitHub issue. We understand that you may be confused by our requests because your issue is itself about links in Web Chat, but we're not talking about those links when we ask you to post links. We want you to post links here for us to read so that we can help you.

For example, here is a link pasted into this GitHub issue: https://www.wikihow.com/Copy-and-Paste-a-Link

**Comment by vishwacsena** [comment]
Closing this since this is not actionable. @carlosrsolis if you continue to see issues that you would like for the team to investigate, please use the issue template and provide relevant repro steps.
