### ISSUE TITLE
Problems concerning idiosyncratic styling after new release (4.9.1)

### ISSUE THREAD

**Issue by PaulAbloescher** [microsoft/BotFramework-WebChat#3259]
Hi,
I previously used the following code to add hover effects, border- and background-color on push-buttons and the sendBoxButton:
```
styleSet.sendBoxButton = Object.assign(
    {},
    styleSet.sendBoxButton,
    {
        backgroundColor: '...',
        '&:hover': {
            backgroundColor: '...'
        }
    }
);

styleSet.adaptiveCardRenderer = Object.assign(
    {},
    styleSet.adaptiveCardRenderer,
    {
        '& .ac-pushButton': Object.assign(
            {},
            styleSet.adaptiveCardRenderer['& .ac-pushButton'],
            {
                color: '...',
                borderColor: '...'
            }),
            '& .ac-pushButton:hover': {
                backgroundColor: '...'
            }
    }
);
```
The font-color of the push-buttons and the sendBoxButton styling broke after the new release (4.9.1).

I wanted to ask if the quick fix that I am currently using is the current way to go?
Quick fix:
```
const sendBoxButton = styleSet.sendBoxButton['&.webchat__icon-button'];
sendBoxButton['backgroundColor'] = '...';
sendBoxButton['&:hover'] = {backgroundColor: '...'};
styleSet.sendBoxButton['&.webchat__icon-button'] = sendBoxButton;

const renderer = styleSet.adaptiveCardRenderer['&.webchat__adaptive-card-renderer'];
renderer['& .ac-pushButton']['color'] = '...';
renderer['& .ac-pushButton']['borderColor'] = '...';
renderer['& .ac-pushButton:hover'] = {backgroundColor: '...'};
styleSet.adaptiveCardRenderer['&.webchat__adaptive-card-renderer'] = renderer;
```

**Comment by compulim** [comment]
@PaulAbloescher our DOM tree change from time to time, we try to minimize the change but it's impossible when we deal with accessibility fixes. 🙏🏻 When we work on #2988, you would have a better way to customize CSS without going to much details here.

For the `sendBoxButton`, we updated the tree, https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/StyleSet/SendBoxButton.js.

```js
styleSet.sendBoxButton = { ...styleSet.sendBoxButton,
  '&.webchat__icon-button': {
    ...styleSet['&.webchat__icon-button'],
    backgroundColor: '...',

    '&:not(:disabled):not([aria-disabled="true"]):hover svg': {
       backgroundColor: '...' // this is for "hover but not disabled", we use `aria-disabled` attribute other than `disabled` attribute for accessibility reason
    }
  }
};
```

For `adaptiveCardRenderer`, https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/bundle/src/adaptiveCards/Styles/StyleSet/AdaptiveCardRenderer.js.

```js
styleSet.adaptiveCardRenderer = { ...styleSet.adaptiveCardRenderer,
  '&.webchat__adaptive-card-renderer': {
    ...styleSet.adaptiveCardRenderer['&.webchat__adaptive-card-renderer'],

    '& .ac-pushButton': {
      ...styleSet.adaptiveCardRenderer['&.webchat__adaptive-card-renderer']['& .ac-pushButton'],
      backgroundColor: '...'
    }
  }
};
```

One thing to note, for [cross-platform accessibility](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/ACCESSIBILITY.md#implementation), we are no longer using `disabled` attribute. Instead, we use `aria-disabled` and style the button as disabled instead. This is because different browser do `disabled` attribute differently and they breaks accessibility requirements.

**Comment by compulim** [comment]
FYI, using `Object.assign` is too tedious sometimes, you can find some helper packages to reduce the boilerplate code. 😉

**Comment by PaulAbloescher** [comment]
Thanks for the quick response!
