### ISSUE TITLE
Toast: Toast and transcript scroll bar looks continuous on Omnichannel

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3438]
> Related to Omnichannel 1941195.

## Screenshots

![image](https://user-images.githubusercontent.com/1622400/91344804-5164f100-e793-11ea-8926-3c4671d290a8.png)

## Version

`4.10.0`

## Describe the bug

The scroll bar of toast and transcript seems visually merged together.

This only repro on Omnichannel because they restyled the scroll bar.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

**Comment by corinagum** [comment]
@compulim please add repro steps

**Comment by Quirinevwm** [comment]
UX recommendation:
Since the scroll bar of toast and transcript are visually merged together, recommending to:
- _Notification pane can be enlarged_: no scroll will appear, when more characters can be shown in the 'small chat view'. Wrap the text so it fits the max of 5-6 lines? Prefer to recommend the max of characters we allow in that space to be around 6 lines (calculate character count for that still). It's better than having the scroll appear when you hit the max of 2 lines in that size of the panel. 
- _Notification can't be enlarged_: make the scroll bar related to the notification (the same color as the message) - if this is not adjustable, then stick to our color blue. So make the tiny scroll bar a different fill color than the standard grey.

**Comment by compulim** [comment]
Based on design feedback, this is a noop for Web Chat. Closing by design.
