### ISSUE TITLE
Request: I need to lengthen the dictation / "Listening" timeout

### ISSUE THREAD

**Issue by nfreear** [microsoft/BotFramework-WebChat#3466]
## Feature Request

**Is your feature request related to a problem? Please describe.**

We're developing a speech-Bot where we have some open-ended questions, where we expect the user to respond with several sentences.

We expect them to pause to think as they respond.

At the moment, a very short pause ends speech recognition prematurely, which causes us a problem.

**Describe the suggestion or request in detail**

Would it be possible to make the "_silence_" timeout configurable, so that we can make it longer?

**Describe alternatives you have considered**

I haven't worked out alternatives.

**Additional context**

We're using _Directline speech_ (Azure speech recognition and TTS) via the "_older_" `create...PonyfillFactory` method.

 * WebChat version :~ 4.9.2;
 * _Microsoft-funded_ ADMINS project.

Thanks,

Nick

[Enhancement]

---
> Investigation questions from compulim: (edited by @corinagum)

### Investigative

- Is it supported in their latest version of JS SDK?
- Is it supported in both Speech Services and Direct Line Speech?
   - Answer: no. this is a feature-request

**Comment by compulim** [comment]
@cwhitten could you help route this feature request to Speech team? On Web Chat side, we can't set the "initial silence timeout" duration. This silence detection is a service-side feature.

This ask also related to the "push-to-talk" scenario.

**Comment by nfreear** [comment]
Thanks.

To add, I think I'm concerned with the `SpeechServiceConnection_EndSilenceTimeoutMs` (not the `InitialSilence`):

 * https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/502

Thanks,

Nick

**Comment by compulim** [comment]
Thanks for the pointer. Someone from our team should look into it:

- Is it supported in their latest version of JS SDK?
- Is it supported in both Speech Services and Direct Line Speech?

**Comment by arturl** [comment]
@ovishesh, any comments?

**Comment by nfreear** [comment]
Hi .. thanks @compulim, @artul, @cwhitten, @ovishesh ... for the comments and actions so far.

Do you have any idea about the timescale for a possible fix please, so I can report back to colleagues?

Just to note, we're now migrating to `webchat` v4.10.1, and the "_newer_" `createDirectLineSpeechAdapters` method.

Thank you,

Nick

**Comment by arturl** [comment]
Need input from @nisheetjain and @ovishesh

**Comment by nfreear** [comment]
Hi All,

As I'm not sure of your and the speech team's time-scales, I'm trying to develop a `SpeechRecognition` _ponyfill_ for WebChat, using _dictation_ mode in the Speech SDK, `initialSilenceTimeoutMs` and `endSilenceTimeoutMs`.

I am drawing inspiration from @compulim's [`createSpeechRecognitionPonyfill`](https://github.com/compulim/web-speech-cognitive-services/blob/master/packages/component/src/SpeechServices/SpeechToText/createSpeechRecognitionPonyfill.js#L129) implementation.

I find that my `SpeechRecognition` _ponyfill_ can recognise speech, and it attempts to send all the events (`start, audiostart ... speechstart ... speechend ... result ... end`), but that the result is not appearing in the chat, or being sent correctly to the Bot.

QUESTION: should this work in principle, with the `initialSilenceTimeoutMs` and `endSilenceTimeoutMs` both set to values between 1000 and 5000 milliseconds?

A key part of the configuration is:

```js
const url = `wss://${region}.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1?initialSilenceTimeoutMs=${initialSilenceTimeoutMs || ''}&endSilenceTimeoutMs=${endSilenceTimeoutMs}&`;
const urlObj = new URL(url);

const speechConfig = SpeechConfig.fromEndpoint(urlObj, KEY);

speechConfig.enableDictation();
```

Any hints as to where to look next would be appreciated.

Thank you!

Nick

(_The Open University, UK_)

**Comment by corinagum** [comment]
@nfreear thanks for checking in. At the moment we don't have a status update. I've tagged @ovishesh and @nisheetjain - let's see what they say.

In terms of your technical ask, @compulim is best equipped to answer your question. Another option you might look into is filing a question on Stack Overflow - one of our support engineers may be able to help.

Some questions:
1. What (if any) errors are you getting? Are they from botframework or speech?
1. Could you share more of your code, as well as a proposed design? This will help provide more guidance. For a template, take a look at the questions a PR submission asks for. :)
   1. Based on the conversation above, I'm not positive a ponyfill will work, since it looks like a service-side change is needed (meaning the Web Chat repo doesn't have control of this change).

Note that right now we're gearing up for a release, so response times might be slow. Thanks for your patience :)

**Comment by nisheetjain** [comment]
Increasing the "listening" timeout isn't supported for direct line speech channel. We understand the requirement and we will internally discuss and get back to you. Please note that the solution for this isn't straight forward, so I wouldn't expect a quick resolution on this.

@nfreear please note that for using direct line speech channel, you must use `dialogServiceConnector` object. `SpeechConfig` won't work against direct line speech channel.

**Comment by corinagum** [comment]
@ovishesh GH is not letting me assign this to you, so for now I've only assigned this to @nisheetjain

**Comment by nfreear** [comment]
Hi @corinagum and @nisheetjain,


> Based on the conversation above, I'm not positive a ponyfill will work, since it looks like a service-side change is needed (meaning the Web Chat repo doesn't have control of this change).
>
Ah. __This is a crunch question for me__. If a custom _ponyfill_-based approach with existing speech services won't work, then I'll stop what I'm attempting, and report back to my team ;).

> In terms of your technical ask, @compulim is best equipped to answer your question.
>
Yes, I'd appreciate more input from @compulim as and when he has the time.

> What (if any) errors are you getting? Are they from botframework or speech?
>
Unfortunately, I'm not getting errors! I'm probably going to have to step through with a debugger to figure out the problems.

> Could you share more of your code, as well as a proposed design? This will help provide more guidance. For a template, take a look at the questions a PR submission asks for. :)
>
I have two(_!_) candidate dictation `SpeechRecognition` classes ...

Option A :~ (_work-in-progress/ rough code_!)

 * Code, https://github.com/nfreear/dictation
 * Demo, https://nfreear.github.io/dictation/?key=AZURE_SPEECH_SUBSCRIPTION_KEY

Option B :~ will see if/how I can share.

>> Note that right now we're gearing up for a release, so response times might be slow. Thanks for your patience :)
>
Understood!

>> Increasing the "listening" timeout isn't supported for direct line speech channel.
>
Hi @nisheetjain, understood. I was evaluating use of the Direct Line Speech channel, but have now reverted to using the speech recognition endpoint(s) directly, via a "_Ponyfill_" and/or the Speech SDK. We will happily use whichever method allows us to fine-tune the configuration (timeouts, etc.), and gives us good synthesis and recognition accuracy of course!

Thank you!

Nick

**Comment by ovishesh** [comment]
Hi @nfreear - I'm the product PM for Direct Line Speech (DLS). As Nisheet pointed out, we have optimized DLS for conversational scenarios, where we typically expect turns to be often shorter and also ensure the end-users get a much better voice UX as a result of this constraint. There is a lot of science that goes behind the scenes to ensure we have generalized solution where we try to balance for low-latency response vs low-cutoff.

In saying that, we do however notice and recognize that there may scenarios where developers would like more granular control for their voice assistants. We are starting to discuss and plan our a potential feature in DLS that will give developers more control to, as you said, fine-tune the configuration as needed.

We have a couple of ways to support this for customers who specifically need low-cutoff or low-latency responses that we handle on a case-by-case basis right now, mostly due to the context I've explained above. If you're interested to use this approach, please feel free to email us at `vi-feedback [at] microsoft [dot] com`. Alternatively, the approach by using the Speech SDK with other endpoint(s) and dictation mode works well too.

**Comment by nfreear** [comment]
Hi All,

I'm happy to say that yesterday I got my dictation-mode speech recognizer working with our Chat-bot,

 * https://github.com/nfreear/dictation

It turned out that I needed:

 1. A `try ... catch` block to catch any errors in the `this.onresult(event);` calls (resulting from a buggy `event.results` object ~ [Line 429+](https://github.com/nfreear/dictation/blob/main/src/createDictationRecognizerPonyfill.js#L429-L438);
 2. To add the `isFinal` property at the correct level in the `resultList` within the `SpeechRecognitionEvent` ~ [Line 81](https://github.com/nfreear/dictation/blob/main/src/createDictationRecognizerPonyfill.js#L80-L81);

So, I think we have a way forward to our larger trial with students in November.

Thank you for all the help and suggestions.

I'll be interested if/when you have something implemented in the `WebChat.js` or service level.

Best wishes,


Nick

**Comment by nisheetjain** [comment]
closing the issue since @nfreear is unblocked now :)
