### ISSUE TITLE
Welcome message not loading on page load while using Iframe using secret

### ISSUE THREAD

**Issue by induyadavusi** [microsoft/BotFramework-WebChat#3536]
I have set one welcome which is suppose to come when page loads but when page load welcome message never come on page load when I will enter something in box after that welcome message comes and then response of earlier type message.
![AzureCoE](https://user-images.githubusercontent.com/50861621/95860289-792d0a00-0d7d-11eb-9a2c-d7b3ac49d2f6.JPG)

**Comment by v-kydela** [comment]
@induyadavusi - If you want to use an iframe then you'll need to provide a token with a user ID. If you want to use a secret then you can't use an iframe because you'll need to get Web Chat to send a backchannel event. Please refer to [this comment](https://github.com/microsoft/BotFramework-WebChat/issues/2120#issuecomment-516056614) for more information.

Closing as expected behavior.
