### ISSUE TITLE
"New message" toast disappears when changing mobile screen orientation

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-WebChat#3597]
## Version

4.11.0 iOS/Android

## Describe the bug

Customer is reporting this issue only for mobile devices when they change the phone orientation.
the "New message" button will show in browsers automatically when the user gets new response and is not in the bottom of the page.

assume he is using horizontal screen now and gets "new message" button, if he switch to use vertical screen now, in some circumstances, the "new message" button should be gone as there is chance that after orientation change, he is already at the bottom.

## Steps to reproduce

1. Go to a Mockbot sample
2. Send "proctive" and scroll up
3. When the message comes in, orient the phone to landscape mode

## Expected behavior

"New message" should be visible

[Bug]

**Comment by compulim** [comment]
The "New message" button should not appears in the repro video.

https://user-images.githubusercontent.com/1622400/105654243-7197f980-5e72-11eb-9567-01adc51d0aa7.mov

**Comment by compulim** [comment]
This is fixed in main branch probably due to a recent bump.

I am writing tests to make sure this does not regress in the future.

https://user-images.githubusercontent.com/1622400/105684764-3b766c00-5eaa-11eb-9bac-0d25e0eac2b6.mp4

https://user-images.githubusercontent.com/1622400/105684848-4f21d280-5eaa-11eb-9271-fb627b24c9f2.mp4
