### ISSUE TITLE
Is it possible to do some auto suggestions for sending msgs to the bot?

### ISSUE THREAD

**Issue by konagallasushmitha** [microsoft/BotFramework-WebChat#3610]
Hi, we are  using botframework webchat for developing a bot in which  backend is nodejs and frontend is reactjs. We want something like when user types anything in the sendbox it would suggest with available suggestions. How can this be achieved pls help me .

**Comment by v-kydela** [comment]
Thank you for the question, @konagallasushmitha 

We do prefer that how-to questions are asked on Stack Overflow, but since you're here I can tell you that Web Chat does not currently have an autosuggest/autocomplete feature and according to this issue there are no plans to implement it: https://github.com/microsoft/BotFramework-WebChat/issues/476

There are already several related questions on Stack Overflow that you might be interested in:
- https://stackoverflow.com/questions/56079912/auto-completion-with-the-botframeworks-webchat
- https://stackoverflow.com/questions/60223610/how-to-add-autocomplete-autosuggestion-in-microsoft-botframework-webchat-using-r
- https://stackoverflow.com/questions/60370672/how-to-append-word-suggestions-to-the-chat-input-area-of-bot-using-react-js

I'll go ahead and close this here.
