### ISSUE TITLE
Handle ExpiredToken (DIRECT_LINE/UPDATE_CONNECTION_STATUS)

### ISSUE THREAD

**Issue by edemehmetcan** [microsoft/BotFramework-WebChat#3628]
Screenshots

![image](https://user-images.githubusercontent.com/28989498/101375816-202aaf80-38b0-11eb-8a99-50e4c98d864f.png)

![image](https://user-images.githubusercontent.com/28989498/101375941-418b9b80-38b0-11eb-8842-55de342d6b33.png)

![image](https://user-images.githubusercontent.com/28989498/101391830-31ca8200-38c5-11eb-949d-04139cc6df9c.png)

Version
Webchat Version: latest (4.11.0)
Platform: Web Browser/

Issue
We need to handle the ExpiredToken, once the token is expired send an event to the backend side in order to sent automatically a message to the user.

I am checking the connection status equals to 3 (ExpiredToken). 

When the token is expired ? When I do a refresh token I have the value of 3600 in expires_in ? The token is expiring after 1 hour or 30min as the documentation says ?...

We could not find proper documentation on handling ExpiredToken event.

Steps to reproduce
Use webchat to converse with the bot.
Keep it unattended for a couple of hours
Come back to webchat to resume the conversation
Expected behavior
Come back to webchat and see the message "your session is expired, please reopen a new conversation"

**Comment by stevkan** [comment]
I don't fully understand the flow you are trying to achieve. If the token is expired, then there isn't a way to send a message via Web Chat (thru the bot) to notify the user as Web Chat relies on having a valid token. You would need to message the user via the client when the token expires.

Is it at this point that you are questioning how to catch an expired token?

**Comment by edemehmetcan** [comment]
@stevkan this is what I want to achieve yes! (I am using C# btw) Do you have a code example which would help me ?

**Comment by edemehmetcan** [comment]
any update?

**Comment by stevkan** [comment]
The token expires after 60 mins (3600 sec / 3600000 ms).

As for notifying the user when the token has expired, that can be achieved by doing something like this simplified example. Essentially, we are detecting if/when the `TOKEN_EXPIRED` connection status is dispatched. When it is, we notify the user asking them if they would like to start a new conversation. Next, detect if the user responds with a 'yes' (true) value. If so, once the Direct Line connection has fully shut down (i.e. `DISCONNECT_FULFILLED` has been dispatched), we then dispatch `RECONNECT`. 

In my tests, this reconnects Web Chat to Direct Line retrieving a new token in the process. There is a caveat, however, in that I am simulating an expired token by calling `directLine.expiredToken()` on a button click. This command tells Direct Line to consider the token as expired, sets the connection status to `TOKEN_EXPIRED`, and so on, as explained above.

In theory, the above should work on an actual expired token. But, it may not present itself until the user returns and attempts to continue the conversation.

```js
let restartConversation = false;

[...]

const store = window.WebChat.createStore (
  {},
  ({ dispatch }) => next => action => {
    switch (action.type) {

      [...]

      case 'DIRECT_LINE/UPDATE_CONNECTION_STATUS':
        if (action?.payload?.connectionStatus) {
          let connectionStatus = action.payload.connectionStatus;
          let connectionType;

          switch (connectionStatus) {
            case 0:
              connectionType = 'UNINITIATED';
              break;
            case 1:
              connectionType = 'CONNECTING';
              break;
            case 2:
              connectionType = 'ONLINE';
              break;
            case 3:
              connectionType = 'TOKEN_EXPIRED';
              restartConversation = confirm("Your session has expired. Would you like to start again?")
              break;
            case 4:
              connectionType = 'FAILED_TO_CONNECT';
              break;
            case 5:
              connectionType = 'ENDED';
              break;
            default:
              return console.log(`DIRECT_LINE >> UNKNOWN_CONNECTION_STATUS: ${ connectionStatus } - Expected a number, received a string`);
          }
          console.log(`DIRECT_LINE >> UPDATED_CONNECTION_STATUS: ${ connectionType }`);
        }
        return next(action);
    }

    case 'DIRECT_LINE/DISCONNECT_FULFILLED':
      console.log('WEB_CHAT >> DISCONNECTED')
      if (restartConversation === true) {
        setTimeout(async () => {
          await startWebChat();
          store.dispatch( {
            type: 'DIRECT_LINE/RECONNECT'
          } )
        }, 4000);
      }
      return next(action);

    [...]

  }
)
```

There are two other options to consider, rather than waiting for a token to expire.

- Set a time out in your Web Chat code that resets after every activity. If the user doesn't return upon some amount of time (10 mins, perhaps), then the session is cancelled.
- [Expire a conversation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-expire-conversation?view=azure-bot-service-4.0&tabs=csharp) - in this scenario, if the bot (not Web Chat) doesn't have any user interaction after a set amount of time, the conversation is expired and restarted. As part of this process, an event could be sent from the bot to Web Chat notifying it to run additional logic, such as, retrieving a new token or redirecting the page back to a starting screen.

**Comment by stevkan** [comment]
Closing this as resolved.
