### ISSUE TITLE
Changing user ID

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#3644]
Is there a way to change/update the user's ID in webchat during conversation with the bot? If yes then how (an example would be great). Thank you!

**Comment by dmvtech** [comment]
Hi @arman-g You want to change the user's ID during a conversation? Are you looking to change the actual user ID or just a name or some identifier that is associated with the user? Can you give more information on the scenario?

**Comment by arman-g** [comment]
Hi @dmvtech, I am looking to change user's ID but if possible name too. Our chatbot is going to be stand alone web app where the user would not be authentication at start. To identify the user we use AdaptivCards to get the user input during conversation between bot and the user. Below I am providing a screenshot of our chat where we request the user to enter the required info. After identifying the user I would like to set the user's ID with the JID from the card. The user's ID (JID) would be helpful in case of handoff to a live agent for conversation history.

![IMG3](https://user-images.githubusercontent.com/22778273/102970353-376ebd00-44ac-11eb-83bf-b8cc47674934.png)

**Comment by dmvtech** [comment]
To clarify; you want to change the `From.Id` (this is what you mean by users ID)? Is there a particular reason you need the from.Id to be the same as the JID? I'm guessing you have some sort of conversation state that you want kept, otherwise it wouldn't matter what from.Id was at all. 

I'm not sure about changing from.id during conversation and how that would/will affect the state of the conversation. Typically, we might suggest using Direct Line enhanced authentication which embeds IDs in the tokens. See more info [here](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0#security-considerations). But as you _currently_ have it, you wouldn't be able to utilize that as you have nothing to go on until they are authenticated with PIN. if you could utilize it using just the JID, then authenticating with the PIN afterwards, that might be a possibility too.

As I'm sure you are aware; you don't want users to be able to be able to change their own ID without any authentication/authorization. 

You have some other alternatives/approaches available as well, including using different conversation states. Let me know more of the requirements needed and I we can find the best solution for you.

**Comment by arman-g** [comment]
Thanks @dmvtech, we save the state in our bot and JID is one of the fields. The reason I wanted to change the user id with jid is for handing off the conversation to the live agent. I assume the turn context will be supplied to the agent hub which will have the user id. Anyway, I guess I can't change it after the conversation started but it would be very helpful if webchat supported that in the feature.
