### ISSUE TITLE
Bot Single Sign On for Angular8+

### ISSUE THREAD

**Issue by anandk95** [microsoft/BotFramework-WebChat#3664]
We are trying to integrate our chat widget in 3rd party website, where the user will login using Azure AD credentials. Can you please show or point me in direction where i can find how to do it With Angular8+

**Comment by v-kydela** [comment]
Thank you for the question, @anandk95 

You can find our SSO documentation here:

- https://docs.microsoft.com/azure/bot-service/bot-builder-webchat-sso
- https://docs.microsoft.com/azure/bot-service/bot-builder-concept-sso
- https://docs.microsoft.com/azure/bot-service/bot-builder-authentication-sso

You can find the Angular Web Chat sample here:

- https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/f.host-with-angular

I hope this helps. If you have any further questions, we would prefer that you ask them on [Stack Overflow](https://stackoverflow.com/questions/tagged/web-chat) so that our answers may help more people.
