### ISSUE TITLE
Avatar Middleware does not register new activity until switch in fromUser

### ISSUE THREAD

**Issue by 01** [microsoft/BotFramework-WebChat#3685]
## Version
Master

## Describe the bug
When utilizing avatar middleware, the hook seems to store the first activity when change in "fromUser" and does not register new activity until fromUser changes

## Steps to reproduce

1. Print out activity on multiple messages inside the avatar middleware  from user or from bot. 

## Expected behavior

Expected each individual activity to be registered

**Comment by stevkan** [comment]
A few questions:

- Can you specify which hook are you referring to?
- Are you able to include the code you are running (minus any keys, passwords, etc.) so I can attempt a precise repro?
- Can you include a screenshot or copied text of the printed out activities you are referring to?
- Which version of Web Chat are you using?
- Is it a CDN, npm package, etc.?

**Comment by 01** [comment]
@stevkan thanks for looking into this.

Can you specify which hook are you referring to?
**Im not sure which hook it would be. Im assuming something in regards to how avatar is rendered.  Its simply guess based on behavior I am seeing and how avatar works without avatar middleware**

Are you able to include the code you are running (minus any keys, passwords, etc.) so I can attempt a precise repro?
**There is nothing special to reproduce the issue. Simply sending multi messages from user without a bot response. Looking at the Botframework-WebChat test functions im guessing this was missed because tests and demos are are alternating between user and bot responses.**
![image](https://user-images.githubusercontent.com/17934292/105860725-e32f8f00-5fbb-11eb-9f80-66cf6f7ab0c1.png)

Can you include a screenshot or copied text of the printed out activities you are referring to?
**I can not as the activities contain employee information in the backchannel value of the activity. But there is nothing useful in the activities. The bug is that multiple activities coming through the avatar middleware show only the first activity until there is a change in fromUser**

Which version of Web Chat are you using?
**4.11.0**

Is it a CDN, npm package, etc.?
**npm package**

**Comment by stevkan** [comment]
I gather from your comment of "multiple users on the same chat" that you are trying to build some sort of group chat.

The first thing to understand is Web Chat, as it is currently designed, is not intended to be used in a multi-user or group setting. It is designed with the expectation that a conversation will occur between a bot and a user, only. With that in mind, the avatar middleware works as expected as the avatar will only attach itself to the first activity in a group of activities, where those activities all originated from either the bot or the user.

Because you are attempting to coerce Web Chat to support multiple users, you are going to have to think creatively to find ways to accomplish what you are intending while using the tools that are available.

Alternatively, you can clone the Web Chat repo making customizations to the core code that would then support multiple users.

**Comment by 01** [comment]
@stevkan 

Thanks for looking into this. Thats disappointing to here. My team has been waiting for the ability to have control over avatar on a "per message basis" as described by the sample, though seems its an a "per activity grouping". I have attempted to reduce the grouping time to separate but the attachment seems to be based on something else. If you could point me where in the core code this distinction is happening it would be much appreciated

**Comment by 01** [comment]
To anyone coming across this its actually easily doable but turning off avatars and taking care of logic in an activity Middleware

**Comment by stevkan** [comment]
@01, Here is the link to the code that is used to generate the [avatarMiddleware](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Middleware/Avatar/createCoreMiddleware.js) middleware.

If you don't mind, could you post the solution you came up with so other's looking for a similar solution can benefit?

I'm going to close this issue since a solution was found.

**Comment by 01** [comment]
@stevkan 

Sure. To accomplish this will need to add own styling for div and image 

![image](https://user-images.githubusercontent.com/17934292/106769826-6334a500-660b-11eb-96fc-ffe6cd1c9d17.png)
