### ISSUE TITLE
[Screen Readers-Intelligent Support Experience-Rate your Experience]: Talkback focus is not sequential on invoking any of the Star rating buttons in 'Rate your Experience' section while navigating using right swipe

### ISSUE THREAD

**Issue by Amit8527510735** [microsoft/BotFramework-WebChat#3702]
User Impact:
Screen Reader dependent users who navigate using Talkback right swipe are misguided as Talkback focus is not sequential on invoking any of the Star rating buttons in 'Rate your Experience' section while navigating using right swipe

Product name, version, and build: Intelligent Support Experience/Chrome v.83
Device: Android
OS : Version 10
Browser: Chrome version 83.0.4103.106
URL: https://servicesuat.microsoft.com/#/time/timeentry
Screen Readers: Talkback

Does this repro with other AT? (If applicable): NA

AT version and build (if applicable): NA

Repro Steps:
Step 1: Enable Talkback & Open the above URL in Chrome browser with valid credentials
Step 2: Select 'Bot' control from the header section of the page.
Step 3: Say 'Hi' to Iris chat bot.
Step 4: 'Would you like me to create a support ticket for you?' response comes back.
Step 5: Choose 'No' to reply back.
Step 6: Reply with 'No' for 'Is there anything else that I can help you with?' response from chat bot.
Step 7:Navigate over the star rating buttons of 'Rate your experience!' message using right swipe and double tap on any of the Star rating buttons & verify Talkback behavior.

Screenshots:
![100317783-e79ef200-2fe2-11eb-8021-e346a1f2c97d](https://user-images.githubusercontent.com/53263029/106737425-a5c2a580-663c-11eb-925f-8b7890dc53dd.png)

Actual Result:
Talkback focus is not sequential on invoking any of the Star rating buttons in 'Rate your Experience' section while navigating using right swipe.
Observation: On invoking any of the Star rating buttons, Talkback focus is moving to Email edit field.

Expected Result:
Talkback focus should stay on the selected Star rating button on invoking any of Star rating buttons in 'Rate your Experience' section while navigating using right swipe.
Ex: If 1 Star button is invoked, Talkback focus should stay on 1 Star button and should narrate as "1 Star button selected".

WCAG Reference:
https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence

**Comment by Amit8527510735** [comment]
#A11yMAS;#A11ySev2;#Accessibility;#WCAG1.3.2;#HCL;#HCL_BotFramework_WebChat;#Linked:BUG6373874;#LinkedBug

**Comment by Amit8527510735** [comment]
@amal-khalaf  Access granted on your alias. Closed bug https://github.com/microsoft/BotFramework-WebChat/issues/3620 due to SLA and created new bug for the same.

**Comment by srinaath** [comment]
@amal-khalaf  Is this ticket on your plate?

**Comment by compulim** [comment]
This also repro on Adaptive Cards Designer, https://adaptivecards.io/designer. So the problem is on Adaptive Cards side. I am using Android 10 (55.1.A.12.28) with Chrome 88.0.4324.181 and TalkBack.

My repro is slightly different: instead of the focus jumped to the email box, it jumped to the top of the page. Thus, the focus is still not as sequential as we hoped.

This card use `action.toggleVisibility` to change between lit and unlit state for the star. And when changing the state, the focus is lost. However, `action.toggleVisibility` does not provide same accessibility feature as a push button. If Adaptive Cards does not make toggle visibility a button, the star control will still not be accessible as a button.

@Amit8527510735 could you send this bug to Adaptive Cards for investigation? It seems the `action.toggleVisibility` have accessibility issues around the focus management. It will be easier if you can send them a stripped down card with just `action.toggleVisibility`, it will reduce repro complexity.
