### ISSUE TITLE
[Web Channel] Update activity is not working for Adaptive card

### ISSUE THREAD

**Issue by MUKESHNITP** [microsoft/BotFramework-WebChat#3709]
We are working on web channel. We have some feature, where we need to update the adaptive card. We are trying to update the adaptive card using the updateActivity method by response activity id but it is giving the process activity error. We also tried from postman using put method, but it is giving the error that "This channel does not support this operation"[PFA]. This updateActivity logic work fine for teams channel.

We got to know from below link update activity don't work on web channel.
Link - https://stackoverflow.com/questions/57402058/how-to-update-an-existing-activity-in-webchat

Could you please let us know that can we update the adaptive card on web channel ?

Please find the below screen shot of error from postman -
image
![102973085-2c567400-4522-11eb-9f08-730570f57a49](https://user-images.githubusercontent.com/35325927/107064238-4d88d080-6801-11eb-9760-efd47773f763.png)

**Comment by stevkan** [comment]
@MUKESHNITP, as you have already noted, the ability to update an activity in Web Chat (via the Direct Line channel) is not a supported feature. Therefore, there is no way to update the adaptive card as a method/feature of BotFramework (in Web Chat).

However, you _can_ update the HTML of the adaptive card as a browser action in response to some activity being passed from your bot to Web Chat. In short, by using Web Chat's store, you can filter the incoming activities for a particular value. When that activity arrives, you can use it as a trigger to update the HTML values of the adaptive card.

If you are looking to update the adaptive card as it is arriving in Web Chat, there are a couple caveats to be aware of:
1) Because you would be updating the HTML that is generated by Web Chat, any refresh to the page and anytime the user navigates away and returns (if you are persisting the chat session) will reset those updated values back to their original values.
2) If you are updating the HTML as a triggered action from an activity in the store, you need to apply a time out of approximately 300 ms (adjust as needed). This is because, without the time out, the triggered update to the HTML will occur _before_ the activity (with the adaptive card) has actually rendered. The time out allows the render to occur first.

I removed the 'feature request' tag on this because it has already been determined that, at this time, updating an activity via Direct Line (which Web Chat is built off of) is backlogged with no ETA on development. As such, please note the attached message below.

---------------------

The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/microsoft/botframework-sdk/) repo is the preferred platform for information on submitting **bug fixes** and **feature requests**.

**Comment by dawolff-ms** [comment]
@stevkan sorry for bringing an old thread back to life, but just wanted to check in on this feature; is updating an activity officially supported yet? If not, is there any updates on an ETA? 

I did a little searching myself but couldn't find anything more recent than your last comment.

**Comment by Godrules500** [comment]
Any chances on this ever being added?
