### ISSUE TITLE
how to get direct line token

### ISSUE THREAD

**Issue by Malith1994124** [Microsoft/BotFramework-WebChat#373]
Can u tell me how to get this  {token: your_token} with {secret: your_secret} for direct line web chat

**Comment by Malith1994124** [comment]
i try this URL - 'https://directline.botframework.com/api/conversations?secret=XXXX'

but i get this error

"message": "The requested resource does not support http method 'GET'."

Can u help me

**Comment by danmarshall** [comment]
Hi @Malith1994124, you can get your token from https://dev.botframework.com/ where you registered your bot with the Bot Famework. On your bot's dashboard, click Edit on the WebChat channel and create a secret in the following page.

**Comment by billba** [comment]
@danmarshall I edited your comment because you said WebChat channel but it should be Direct Line channel

@Malith1994124 you do not pass secrets as parameters, instead you pass them as an `Authorization` header. Please see [the Direct Line docs](https://docs.botframework.com/en-us/restapi/directline3/) for more information.

In general please use StackOverflow for general questions about the Bot Framework. I am closing this issue as it is not a problem with WebChat.

**Comment by ShujaathKhan** [comment]
This should answer what you're looking for
https://github.com/compulim/BotFramework-Samples-Template/blob/master/packages/bot/src/index.js#L59
