### ISSUE TITLE
Chatbot doesn't greet with correct user id

### ISSUE THREAD

**Issue by FrancoCorleone** [microsoft/BotFramework-WebChat#3741]
Hello all,
I took one of the JS examples: QnABot, and wanted to greet users with personal note. 
Unfortunately, I noticed two weird behaviors:
1. Bot first answers simple Hello (from knowledgebase) and a couple of seconds later pushes the greeting message in between messages. Is that expected behavior?
2. membersAdded is trigger when I click into chat window, that's expected, but it has no context of the userid whatsoever, so it answers with some random id. Is is even possible to greet user on start, before he/she sends a message to chatbot?

**Comment by compulim** [comment]
Hi @FrancoCorleone,

`conversationUpdate/membersAdded` event is always fired before any messages. But the timing could varies:

- If you are using Direct Line token containing an user ID (see [point 1 in this article](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0#security-considerations)), then your bot will receive user ID as soon as the conversation started;
- Otherwise, your bot will receive user ID just before the first message sent from the user, to be specific:
  - Your bot will receive `memberAdded` with your bot ID (i.e. your bot joined the conversation)
  - Just before the bot receive the very first message from the user, your bot will receive another `membersAdded` with user ID

We always recommend using a Direct Line token with an user ID.

You can read more about the behavior at [`docs/WELCOME_MESSAGE.md`](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/WELCOME_MESSAGE.md).

**Comment by FrancoCorleone** [comment]
Ok. @compulim, that seems ok, but if I try it ootb, it gives me 403 on call to https://directline.botframework.com/v3/directline/conversations.
I'd be glad if you could point me to some documentation here, as I'm struggling with it big time

**Comment by FrancoCorleone** [comment]
Ok nvm, I figured it out ;) It was my fault
