### ISSUE TITLE
Response timeouts with DirectLineSpeech

### ISSUE THREAD

**Issue by hrazmsft** [microsoft/BotFramework-WebChat#3773]
## Screenshots

![image](https://user-images.githubusercontent.com/66222191/109778388-6ec8bb00-7c0d-11eb-9b9c-9b84c68a9a18.png)

## Version

NPM: `botframework-webchat": "^4.11.0`

![image](https://user-images.githubusercontent.com/66222191/109778648-bd765500-7c0d-11eb-99cf-4c44ce0eb542.png)

## Describe the bug

After connecting a bot with DirectLineSpeech, every activity (except of the first one), no matter if text or speech, receive timeout while waiting for reply. In other platforms (emulator, postman, azure portal emulator) there is no timeout and all the responses are quick. 

## Steps to reproduce

1. Render WebChat component with DirectLineSpeech support.
2. Send one message to the bot (text or speech)
3. The response should be quick
4. Send another message to the bot (text or speech)
5. The response has timeout

## Expected behavior

The response should be quick like the first response

## Additional context

None

[Bug]

**Comment by corinagum** [comment]
@hraz-msft I tested this out on our [sample](https://microsoft.github.io/BotFramework-WebChat/03.speech/a.direct-line-speech/) and my behavior is slightly different from yours - when you say timeout, does the response eventually show up? Or no?

For me these timeout messages are non-blocking.

Sounds like a channel issue - Support team could someone help debug? Thanks.

**Comment by tomlm** [comment]
yes, it does show up, but 3 seconds later

**Comment by compulim** [comment]
After some investigations: since Direct Line Speech works quite differently at the protocol level, the delay that applies to Direct Line protocol could not applies to DLSpeech protocol.

Essentially, DLSpeech does not tell Web Chat when it has successfully sent a message (a.k.a. no send receipt, no read receipt). In other words, Web Chat never know the ID of the activity just sent. That means, activities sent from user will not have an ID.

Thus, since the activity from the bot has a reply-to-ID, we can never match that ID in our transcript. Thus, we can never sequence the transcript correctly. The delay is meaningless in DLSpeech protocol.

**Comment by hraz-msft** [comment]
Look, only the WebChat component has that delay and that delay is happening from the second activity. In other platforms there is no such delay for the same bot

**Comment by compulim** [comment]
The delay is required for accessibility, and it was introduced for Direct Line protocol.

DL protocol is a distributed system: [message comes in a very random order](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/media/direct-line-sequence-diagram.png). But accessibility and screen reader doesn't work that way. It requires message to be injected on the screen in a *time-sensitive manner*.

As an accessible UI component which complies to WCAG 2.1, Section 508, and EN 301 549, Web Chat is required to re-sequence the message from a chaotic order. We need to inject those messages on screen in an order meaningful to people who can't see the screen.

To re-sequence the message, delay is required. It is similar to how packet defragmentation works in other systems, such as, TCP/IP.

Unfortunately, Speech SDK (used by DLSpeech) doesn't give us ID or send receipt. It means, DLSpeech client has no way to verify whether a message has sent to the bot, or it failed due to intermittent network connectivity. Also, DLSpeech does not fill in the details of an outgoing activity, such as conversation ID, timestamp, sender ID, activity ID, etc.

As we mentioned in [this introductory article](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/DIRECT_LINE_SPEECH.md#what-is-direct-line-speech), DLSpeech is a protocol designed for a non-transcript-based UI, such as home assistant, smart display, automotive dashboard, navigation system, etc. We have a [demo here](https://microsoft.github.io/BotFramework-WebChat/06.recomposing-ui/c.smart-display) to show how to better utilize the protocol.

**Comment by hraz-msft** [comment]
Maybe @tomlm or @damarqmsft can give more data. But the weird thing is that other platforms has no delay or timeout (emulators and azure portal WebChat)

**Comment by damarqmsft** [comment]
> Maybe @tomlm or @damarqmsft can give more data. But the weird thing is that other platforms has no delay or timeout (emulators and azure portal WebChat)

Emulator and portal webchat are not using DLSpeech and they might not be implementing the delay. The problem here is we were waiting for a confirmation that would never come via DLSpeech (it comes only with Direct Line).

William's PR should fix it.

**Comment by compulim** [comment]
This will be released as a daily build tomorrow ~3-4 AM.

https://github.com/microsoft/botframework-webchat/releases/daily
