### ISSUE TITLE
Missing ChannelData when using speech

### ISSUE THREAD

**Issue by damarqmsft** [microsoft/BotFramework-WebChat#3774]
## Version

<meta name="botframework-directlinespeech:version" content="4.11.0">
<meta name="botframework-webchat:bundle:variant" content="full">
<meta name="botframework-webchat:bundle:version" content="4.11.0">
<meta name="botframework-webchat:core:version" content="4.11.0">
<meta name="botframework-webchat:ui:version" content="4.11.0">

## Describe the bug

I have custom code to add data to ChannelData at every message. I can see the extra data, inside my bot, for typed messages but I can't see the data for spoken messages.

Something between WebChat and Bot server is dropping ChannelData for spoken messages.

## Steps to reproduce

1. Try HTML file: [try.txt](https://github.com/microsoft/BotFramework-WebChat/files/6077093/try.txt) . Make sure to change token URL at line 31
2. type "hi"
    - The bot receives this Activity **containing channelData.email**  [typed_message.txt](https://github.com/microsoft/BotFramework-WebChat/files/6077141/typed_message.txt)
3. Speak "hello"
    - The bot receives this Activity which **doesn't contain channelData.email**  [spoken_message.txt](https://github.com/microsoft/BotFramework-WebChat/files/6077145/spoken_message.txt)

## Expected behavior

ChannelData should arrive on bot side for both typed and spoken messages.

## Additional context

[Bug]

**Comment by compulim** [comment]
This is a known issue with Direct Line Speech, please refer to [`DIRECT_LINE_SPEECH.md`](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/DIRECT_LINE_SPEECH.md#no-additional-data-can-be-piggybacked-on-speech-recognition).

The issue is being tracked at #2680.

If you would like to see this being implemented, please vote up on the issue. And if you can give an user story, it will help our PM to better prioritize this work too.
