### ISSUE TITLE
Keyboard navigation issue inside the Chatbot window

### ISSUE THREAD

**Issue by venkatoesc** [microsoft/BotFramework-WebChat#3783]
We are using webchat-es5.js for our Virtual assistant and it should be 508 compliant. Users not able to navigate the virtual agent using keyboard. The focus is not going inside the chatbot window. When pressing tab key, the entire chatbot window getting focused and shows "end of transcript" with black outline. In version 4.11.0, it works fine and no Black outline. 

## Screenshots
![image](https://user-images.githubusercontent.com/74585902/110465333-4869ba80-80fa-11eb-9866-cb2a49e93987.png)

## Version
webchat es5 version 4.12.0
https://cdn.botframework.com/botframework-webchat/4.12.0/webchat-es5.js
Integrating the CDN version js directly on the page using script tag (No Iframe). Desktop Chrome Browser.

```
<meta name="botframework-directlinespeech:version" content="4.12.0">
<meta name="botframework-webchat:bundle:variant" content="full-es5">
<meta name="botframework-webchat:bundle:version" content="4.12.0">
<meta name="botframework-webchat:core:version" content="4.12.0">
<meta name="botframework-webchat:ui:version" content="4.12.0">"
```

## Describe the bug
We are using webchat-es5.js for our Virtual assistant and it should be 508 compliant. Users not able to navigate the virtual agent using keyboard. The focus is not going inside the chatbot window. When pressing tab key, the entire chatbot window getting focused and shows "end of transcript". 

## Steps to reproduce

1. Create web app bot 
2. Integrate the bot as floatable using Javascript (add in host webpage DOM) + webchat-es5.js version 4.12.0
3. Open the chatbot in Chrome browser.
4. Press tab key on keyboard.
4. Type some text in question box and press Shift + Tab (to navigate backwards).

## Expected behavior

1. On Step 3 and Step 4 above, the focus should navigate to each element(Buttons, textboxes) in the chatbot.

## Additional context
When the chatbot div is on focus, it shows black outline, but doesn't allow to navigate inside with keyboard.

[Bug]

**Comment by corinagum** [comment]
This is by design. When user is focused inside the transcript (black line), they are able to use up/down arrows to navigate individual activities.

https://github.com/microsoft/BotFramework-WebChat/pull/3703

**Comment by compulim** [comment]
@venkatoesc you can read more about the design here, https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/ACCESSIBILITY.md#ux-navigating-activities-in-the-transcript.

The background story is:

- This is an accessibility requirement we gathered from our customers. In one-liner: use up/down arrow keys to navigate the transcript;
- Web Chat is a complex UI component. I mean, in the transcript, some activities may contains focusable elements, such as buttons.

[WAI-ARIA](https://www.w3.org/TR/wai-aria/) do not offer any guidelines for chat UI or UI with nested focus like Web Chat. Please do correct us if we overlooked it.

So, the closest we could get from [WAI-ARIA](https://www.w3.org/TR/wai-aria/) and [WAI-ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices/) is a grid scenario, like Excel.

So, we start thinking accessibility of transcript is like a grid:

- After end-user focus on the grid, they can use up/down arrow keys to navigate across cells;
- 50% cells contains focusable buttons;
- The grid is very large, we are only able to show < 5% of all cells in any viewport;
- The input box is next common thing they would use, but unlike Excel where it is at the top of the grid, it is below the grid
  - In other words, to get to the input box, instead of <kbd>SHIFT</kbd> + <kbd>TAB</kbd> (or <kbd>F2</kbd>), they will press <kbd>TAB</kbd>

In this setting, if end-user's focus in on the grid. What's the quickest way to get to the input box? They will press <kbd>TAB</kbd>. But since many grid cells contains multiple focusable buttons, it is very likely that the viewport will jump to a place they have no idea where it is. Their action does not lead to their intention, and is pretty far. They need to press <kbd>TAB</kbd> many times to get to the input box.

So we decided not to allow end-user to use <kbd>TAB</kbd> key to focus on the button. Instead, they would use up/down arrow keys plus <kbd>ENTER</kbd> to focus inside the message, i.e. focus on the button.

If you have a better (or more creative) idea to make the Web Chat more accessible and would provide a better UX, please do let us know. I am happy to experiment it together and potentially implement it in production.

**Comment by venkatx5** [comment]
Thanks a lot for the clarification!
