### ISSUE TITLE
Unable to access Kusto DB from 1ES bot code 

### ISSUE THREAD

**Issue by phaneendra-zen3** [microsoft/BotFramework-WebChat#3830]
We are trying to connect Kusto Database( **https://*****.kusto.windows.net** ) for 1ES BOT code using Tenant ID. In local we are able to access without any issues whereas in production it is failing with authentication issue.

![image](https://user-images.githubusercontent.com/69052406/113585328-b77af600-9649-11eb-90f5-5543119d3de8.png)

**Error:-**

![image](https://user-images.githubusercontent.com/69052406/113586274-ed6caa00-964a-11eb-9a6e-c87096199020.png)

Can you please help me on this?

**Comment by peterinnesmsft** [comment]
Hi @phaneendra-zen3,

Based on what you're describing, this does not look to be a Bot Framework-related issue. You are most likely hitting network access issues due to firewall permissions or similar which are preventing your compute of choice from communicating with the Kusto cluster.

I would recommend checking internally with folks to determine which ports need to be given access on your compute nodes, as well as determine if any allowances need to be opened up on the Kusto cluster side in order to enable communication.

As there is no evidence that this is a Bot Framework issue, I'll be closing this out. Let me know if there are any concerns.
