### ISSUE TITLE
Change voice to neural with Node.js and Direct Line Speech

### ISSUE THREAD

**Issue by NereaCabiedasMoreno** [microsoft/BotFramework-WebChat#3869]
**hello, I am trying to change the voice to be neural, with this code in dialogBot.js but i can't get it to use neural voice in the whole bot**

  `this.onMessage(async(context, next) => {

            console.log('Running dialog with Message Activity.');

            await this.dialog.run(context, this.dialogState);
            const speakText =
                `<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="es-ES">
                    <voice name="es-ES-ElviraNeural">
                       "${context.activity.text}"
                    </voice>
                </speak>`;

            await context.sendActivity(speakText);

             await next();
       });`

**Comment by stevkan** [comment]
@NereaCabiedasMoreno, I'm exploring some options to see if they will work and will let you know what I find.

**Comment by NereaCabiedasMoreno** [comment]
okey, Thank you very much! @stevkan

**Comment by NereaCabiedasMoreno** [comment]
Have you been able to find any solution or help? @stevkan @compulim Thanks!

**Comment by stevkan** [comment]
@NereaCabiedasMoreno, there are a few different places you could choose to implement something like this. I chose to do it as middleware in order to get the activities before they are processed by the main application. Beyond that, there wasn't a specific reason I chose to do it this way.

Please find the example code below. You will need to customize it, regardless of where it lives, in order to catch all the possible activities you are passing thru (i.e. simple text responses, adaptive cards, hero cards, carousel, etc.) as the affected text will live in different places. As you can see, I have an example that captures the text from simple text responses and adaptive cards. Note that each adaptive card in your bot should have the same initial setup so the text value is always in the same location. Or, be prepared to write code that respects cards with different formatting.

**Index.js**
```js
const { DirectLineSpeechMiddleware } = require('./resources/scripts/directLineSpeechMiddleware');

const adapter = new BotFrameworkAdapter(adapterSettings)
  .use(new DirectLineSpeechMiddleware());
```

**directLineSpeechMiddleware.js**
```js
class DirectLineSpeechMiddleware {
  constructor() {
    // Defines SSML to be wrapped around the bot's text responses
    this.ssmlStart = "<speak version='1.0' xmlns='https://www.w3.org/2001/10/synthesis' xml:lang='en-US'><voice name='de-DE-KatjaNeural'>";
    this.ssmlEnd = '</voice></speak>';
  }

  async onTurn(context, next1) {
    let responses = {};
      context.onSendActivities(async (ctx, activities, next2) => {
          const len = activities.length;
          let lastActivity = {};
          let speech = '';

          if (len > 1) {
            const index = len - 1;
            lastActivity = activities[index];

            // If activity has attachment which contains an adaptive card
            if (lastActivity.attachments && lastActivity.attachments.length) {
              if (lastActivity.attachments[0].contentType === 'application/vnd.microsoft.card.adaptive') {
                for (const items of lastActivity.attachments[0].content.body[0].items) {
                  for (const item in items) {
                    if (item === 'text') {
                      speech += `${ items[item] } `;
                    }
                  }
                }
              }
            }
            speech = speech.trim();

            // Test is text value or adaptive card text value is present, wrap in SSML, and assign to 'speak' property.
            lastActivity.speak = lastActivity.text ? `${ this.ssmlStart }${ lastActivity.text }${ this.ssmlEnd }` : `${ this.ssmlStart }${ speech }${ this.ssmlEnd }`;
          }

          // run full pipeline
          // Filter on 'directline' and 'directlinespeech' channels
          switch (lastActivity.channelId) {
            case 'directline':
            case 'directlinespeech':
              responses = await next2();
              return ctx;
          }
        return responses;
      });

    // hook up update activity pipeline
    context.onUpdateActivity(async (ctx, activity, next3) => {
      // run full pipeline
      const response = await next3();
      // add Message Update activity
      return response;
    });

    // hook up delete activity pipeline
    context.onDeleteActivity(async (ctx, reference, next4) => {
      // run full pipeline
      await next4();
    });
    await next1();
  }
}

module.exports.DirectLineSpeechMiddleware = DirectLineSpeechMiddleware;
```

Things to consider:
- If you plan to run your bot on other channels, then you will need to do additional testing to be certain it _isn't_ conflicting, at all.
- Running this middleware alerted me to several dialogs where I was not returning a dialog turn status. If a status is not being returned, an error will surface.

**Comment by stevkan** [comment]
As this is technically a 'how to' question, I am going to close this as resolved. If you need additional support regarding this, please post your question(s) on Stack Overflow.

-----------------

The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotFramework-SDK/) repo is the preferred platform for information on submitting **bug fixes** and **feature requests**.

**Comment by NereaCabiedasMoreno** [comment]
What do you have in adapterSettings? @stevkan

**Comment by NereaCabiedasMoreno** [comment]
Hi @stevkan  i have this error  [onTurnError] unhandled error: DialogContextError: Cannot read property 'status' of undefined when i use this code , Can you help me , please? @compulim

**Comment by NereaCabiedasMoreno** [comment]
How can I return a dialog turn status?? @stevkan @compulim
