### ISSUE TITLE
Missing `directLine` prop?

### ISSUE THREAD

**Issue by hrazmsft** [microsoft/BotFramework-WebChat#3908]
## Screenshots

![image](https://user-images.githubusercontent.com/66222191/119332089-cb79c600-bc90-11eb-9ca3-fe4136dc822a.png)

## Version

NPM: botframework-webchat ^4.13.0

## Describe the bug

The `directLine` property is missing since version 4.13.0 in TypeScript

## Steps to reproduce

1. Run `npm install botframework-webchat`
1. Follow one of the samples in this repo.

## Expected behavior

`directLine` prop will be defined in Typescript.

## Additional context

[Bug]

**Comment by stevkan** [comment]
@hrazmsft, can you provide more details on the steps you took that lead to this error? I just tested by copying the [04.api/h.clear-after-idle](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/04.api/h.clear-after-idle) sample and running it and didn't encounter any errors or issues. To be clear, I ran `npm install` in the root folder and then ran the sample.

**Comment by hrazmsft** [comment]
Did you use Typescript? The type definitions seems to be worng. Almost no props expect styling... I will send more photos soon...

**Comment by stevkan** [comment]
@hrazmsft, thank you for your patience. I'm still unable to repro. However, I want to try one other variation in my implementation. I should have an update for you by EOD, today.

**Comment by hrazmsft** [comment]
@stevkan I don't know why you unable to repro... It super easy:

* Run `npx create-react-app my-app --template typescript` to create a new React project with Typescript template
* Add the WebChat component with `yarn add botframework-webchat`
* Start one implementation from your samples (I chose https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/01.getting-started/e.host-with-react)

And that's it...

Anyway, I've created a repo with these steps: https://github.com/hrazmsft/webchat-issue. 
You can see there this issue and another issue that I've opened: https://github.com/microsoft/BotFramework-WebChat/issues/3909)

Here is a screenshot from that repo:
![image](https://user-images.githubusercontent.com/66222191/120621033-359b2380-c466-11eb-8702-606e0b3bfe6a.png)

I hope it will help to resolve this issue ASAP.

**Comment by stevkan** [comment]
@hrazmsft, I will try with your steps, as well. Hopefully, I will be able to see what you are seeing and can then move to finding a proper fix.

**Comment by hrazmsft** [comment]
@stevkan thanks! But as I mentioned above, I have created a repo for you with a repro: https://github.com/hrazmsft/webchat-issue

**Comment by stevkan** [comment]
@hrazmsft, yes. I was using 'steps' generally. I'll respond here once I've run throw it.

**Comment by stevkan** [comment]
@hrazmsft, I was able to repro the issue now. Turns out one of the culprits blocking me was yarn. Switching over to npm, I was able to encounter the errors you have reported. So, yes, I am now able to repro.

That being said, there is a comment further up that I missed that already identifies this as a known problem, issue #3856. Customers there report that downgrading to 4.11.0 alleviates the issue. It appears that 4.12.0 works for me. There will likely be a fix applied for 4.14 as the issue has been flagged for consideration.

As this appears to be a duplicate issue, I am going to close in favor of the other. If you are able, please add any comments there (if you haven't already) showing support. Doing so will help in prioritizing development.
