### ISSUE TITLE
How to get rid of black border?

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#3987]
I am not sure what has changed in resent webchat versions, but I am noticing black border around the chatbot box when it has focus (please see the images below).
My question is how to prevent this happening? I do not want this black border to appear, it does not go away on mobile and looks terrible.

On desktop:
![IMG](https://user-images.githubusercontent.com/22778273/125536344-3842e8ea-ffe8-4b31-8949-064788132336.png)

On mobile:
![InkedLASC - MH Chatbot (Dev) (002)_LI](https://user-images.githubusercontent.com/22778273/125536553-7269c21a-ecdc-4fcd-a149-9a100e10df16.jpg)

**Comment by AkashGovani** [comment]
facing the same issue. on clicking the response area, a black border appears

**Comment by stevkan** [comment]
The black border is an accessibility feature designed to benefit disabled or otherwise challenged users. If you want to disable it, it can be done so thru Web Chat's "styleOptions" via the `transcriptVisualKeyboardIndicatorColor` property (introduced in v4.12.0), as shown below. You can read more about the topic in the repo's [readme](https://github.com/microsoft/BotFramework-WebChat/blob/31d0b69ccee674174634d8da10ff7670ffdfc5e9/README.md#visual-focus-changes-to-transcript-in-web-chat-4120). You can also look over other transcript styling options [here](https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/api/src/defaultStyleOptions.ts#L195).

```js
const styleOptions = {
  transcriptVisualKeyboardIndicatorColor: 'transparent',
}

[...]

window.WebChat.renderWebChat(
  {
    directLine: directLine,
    styleOptions: styleOptions,
  },
  document.getElementById( 'webchat' )
);
```

Closing as this should resolve the issue. If the problem persists, please feel free to reopen.

**Comment by arman-g** [comment]
@stevkan thank you! I think this will be better for me:
`const styleOptions = {
  transcriptVisualKeyboardIndicatorWidth: 0,
}
`
