### ISSUE TITLE
Is it possible to change the webchat's language after it has been loaded?

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#4005]
As title says, is it possible to change the webchat's language after it has been loaded? If yes then how? If not then I would suggest adding this feature which will be a good addon to multi lingual support. Thanks!

**Comment by benbrown** [comment]
@compulim is this currently possible?

**Comment by compulim** [comment]
Yes, it is possible.

In fact, since Web Chat is based on React, you can change almost all options you passed into Web Chat. The only exception is `directLine` object, i.e. you can't change the connection once Web Chat is started.

If you are using CDN to host Web Chat, just call `renderWebChat` again with the new options. Make sure you also pass in options that you didn't change.

For example, the following code will initially render Web Chat in Japanese. And after 10 seconds, it will render Web Chat in Traditional Chinese.

```js
const baseOptions = {
  directLine,
  locale: 'ja-JP'
};

window.WebChat.renderWebChat(
  baseOptions,
  document.getElementById('webchat')
);

setTimeout(() => {
  window.WebChat.renderWebChat(
    {
      ...baseOptions,
      locale: 'zh-Hant'
    },
    document.getElementById('webchat')
  );
}, 10000);
```

p.s. you can also change all middleware and style options too.

**Comment by arman-g** [comment]
@compulim thank you! I assume once chotbot is re-rendered the history is gone, am I right?

**Comment by compulim** [comment]
No, the history is not gone. Good to bring this one up.

`renderWebChat` is actually a wrapper for `ReactDOM.render`. [Its API is here](https://reactjs.org/docs/react-dom.html#render), excerpt:

> If the React element was previously rendered into `container`, this will perform an update on it and only mutate the DOM as necessary to reflect the latest React element.

It is not commonly known that the `ReactDOM.render` (wrapped by `renderWebChat`) function is actually (more-or-less) an upsert function.

Web Chat is trying our very best to make sure all options are *reactive*, i.e. can be changed on-the-fly without hurting the state. Please do let us know if you changed an option and it caused weird behaviors. Love to fix them.

**Comment by arman-g** [comment]
@compulim perfect! thank you.
