### ISSUE TITLE
Unable to show "open in new window" icon for external links

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#4062]
I am working from the minimizable webchat sample.
I updated to  4.14.0 and added a new icon (base64) to the markdownExternalLinkIconImage to my styleOptions.

In Webchat.js:

```
// emoji support
var md = require('markdown-it')({ breaks: true });
var emoji = require('markdown-it-emoji');
md.use(emoji);
```
and
```
<ReactWebChat className={`${className || ''} web-chat`} directLine={directLine} **renderMarkdown={md.render.bind(md)}** store={store} activityMiddleware={activityMiddleware} styleOptions={styleOptions} />
```

Markdown like 

```
More informatione [on our website](https://mysite.com/faqpage)
```

Does not result in an icon. I checked in development console and I think nothing is rendered. Not even the one pixel icon.
Do I need to do more?

```
  "dependencies": {
    "botframework-webchat": "^4.14.0",
    "classnames": "^2.2.6",
    "markdown-it": "^12.2.0",
    "markdown-it-emoji": "^2.0.0",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "^3.4.3",
    "webpack": "^4.43.0"
  },
```

**Comment by compulim** [comment]
The "open in new window" icon was added by our default Markdown engine. Since you overrode the Markdown engine, thus, the icon is no longer showing up.

Since you are using `markdown-it` engine, same as the one we use. You can look at how we added a plug-in to `markdown-it` to render the icon. Here is the link to the code, https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/bundle/src/renderMarkdown.ts#L88.

Thanks.

**Comment by HesselWellema** [comment]
Tnx. Tbh, I don't remember why I'm overriding the renderer in the first place. I'll try and use yours
