### ISSUE TITLE
Using word-wrap in Adaptive Cards ActionSet and markdown list

### ISSUE THREAD

**Issue by avrum** [microsoft/BotFramework-WebChat#4075]
I've been having issue with word-wrap property when using ActionSet with mark down list.

For some reason when I'm including a markdown list in the "ShowCard" the text get the wrap property but the boundaries seems to be shifted to the right.

screenshot that demonstrate this issue:

[![enter image description here][1]][1]

When viewing in in dev mode (marking the component edge):

[![enter image description here][2]][2]

This works as expected without the bullets(list), but I need this design to work with bullets

The original card JSON:

    {
    	"contentType": "application/vnd.microsoft.card.adaptive",
    	"content": {
    		"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    		"type": "AdaptiveCard",
    		"version": "1.2",
    		"body": [
    			{
    				"type": "TextBlock",
    				"size": "Large",
    				"weight": "Bolder",
    				"text": "Emergency Ambulance"
    			},
    			{
    				"type": "TextBlock",
    				"size": "Medium",
    				"weight": "Bolder",
    				"text": "Care Instructions:"
    			},
    			{
    				"type": "ActionSet",
    				"actions": [
    					{
    						"type": "Action.ShowCard",
    						"title": "Call an Ambulance",
    						"card": {
    							"type": "AdaptiveCard",
    							"body": [
    								{
    									"type": "TextBlock",
    									"text": "- The is a very long text, one two three four five six seven eight nine ten, eleven twelve thirteen fourteen .\n\n- The is a very long text, one two three four five six seven eight nine ten, eleven twelve thirteen fourteen .\n\n- The is a very long text, one two three four five six seven eight nine ten, eleven twelve thirteen fourteen .\n\n",
    									"wrap": true
    								}
    							]
    						}
    					}
    				]
    			}
    		]
    	}
    }

This seems to work as expected in "https://adaptivecards.io/designer/" :

[![enter image description here][3]][3]

but in BotFramework-WebChat recent version it doesn't work as expected, and we have lots of customers suffering from this bug

  [1]: https://i.stack.imgur.com/O3e9C.png
  [2]: https://i.stack.imgur.com/pZaBQ.png
  [3]: https://i.stack.imgur.com/rwRjb.png

**Comment by avrum** [comment]
@compulim you're welcome :)
Thank you guys for the fast response.

**Comment by compulim** [comment]
Some early investigations. I have a tool called "Adaptive Card loader", which load AC outside of Web Chat. But also have an option to pass styling (a.k.a. AC Host Config). I use it to verify if it is an issue on AC vs. Web Chat.

Here is my quick tool, https://compulim.github.io/adaptive-card-loader/. Check the "Enable Markdown" checkbox.

![image](https://user-images.githubusercontent.com/1622400/138362803-47eeb468-9899-4a2f-889c-6693024e120c.png)

With default styling, the `<ul>` also leaked.

But if I manually removed `width: 100%`, it works.

![image](https://user-images.githubusercontent.com/1622400/138362890-e2efda9b-b372-489e-b876-7cb567d94798.png)

Need more investigations to see if it's AC vs. Web Chat.

**Comment by lauren-mills** [comment]
@compulim - adding this to the backlog since it seems like you have a couple of options for resolutions.

**Comment by compulim** [comment]
I just reached David from AC team and they suggest adding `box-sizing: border-box` to the whole AC component.

I will add the following CSS stylesheet:

```css
.webchat__adaptive-card-renderer {
  box-sizing: border-box;
}
```

**Comment by compulim** [comment]
While fixing the issue, I found that AC is applying some styles only for the first child element. These styles are not added by Markdown-It but Adaptive Cards.

Since Web Chat don't have a test that only a single list in Adaptive Card, thus, we never catch this bug. I am adding a test to prevent regression.

@avrum a temporary workaround here would be adding a line of text before the list.

## Technical details

If the Markdown list is the first thing in the `TextBlock`, then AC apply some style to the `<ul>` and it breaks word wrap due to its assumption of `border-box` mode.

- Styles applied to the first item
   - `style="margin-top: 0px; width: 100%; overflow: hidden; text-overflow: ellipsis; margin-bottom: 0px;"`
- Styles applied to all items
   - `style="margin-bottom: 0px;"`

### If paragraph is the first thing in the Markdown

![image](https://user-images.githubusercontent.com/1622400/140391203-b75fad3a-4437-4ea9-a09b-52bab4ae8137.png)

### If unordered list is the first thing in the Markdown

![image](https://user-images.githubusercontent.com/1622400/140391251-a36557d8-e761-453a-9ceb-88ca74463846.png)

**Comment by avrum** [comment]
Thank you guys for fixing this issue!

**Comment by avrum** [comment]
Thanks again for fixing this 🪲 👏
