### ISSUE TITLE
Toggling the visibility of content within a card does not always work.

### ISSUE THREAD

**Issue by KarlPurk** [microsoft/BotFramework-WebChat#4119]
## Screenshots

![image](https://user-images.githubusercontent.com/1528469/151013129-5deae9b3-cc16-4693-85ee-f7e38eae4b3d.png)

This screenshot doesn't capture the behaviour - in the above screenshot I have clicked "Hide history" but the content is still visible.

## Version

I reproduced the issue using one of the samples which points to the latest version via CDN.  However, this particular issue was introduced in v.4.12.0.  

## Describe the bug
Toggling the visibility of hidden content does not work correctly in all cases.  When this issue occurs the user is no longer able to toggle the visibility of hidden content.  

## Steps to reproduce
Please see steps listed in the [reproduction repo](https://github.com/KarlPurk/webchat-adaptive-card-toggle-visibility-issue/tree/main/samples/01.getting-started/a.full-bundle#reproduction-steps).

## Expected behavior

When a user clicks on a toggle visibility trigger the content visibility should be toggled - if it's visible it should become hidden, if it's hidden it should become visible.

## Additional context

Please refer to the [reproduction repo](https://github.com/KarlPurk/webchat-adaptive-card-toggle-visibility-issue/tree/main/samples/01.getting-started/a.full-bundle#reproduction-steps).

This issue might be related to https://github.com/microsoft/BotFramework-WebChat/issues/4118.

[Bug]

**Comment by msomanathan** [comment]
@stevkan Could you please provide an update to this issue?

**Comment by stevkan** [comment]
@KarlPurk, thank you for your patience. I should have a response for you by end of day, today.

**Comment by stevkan** [comment]
@KarlPurk, unfortunately, I am unable to repro the issue you are experiencing. You did reference some conditions that were necessary. I'm going to take another dive and double check that the conditions are being met.

In the meantime, are there any specific changes you made to the code beyond what you have cited above?

**Comment by KarlPurk** [comment]
@stevkan no, nothing specific.  I kept everything as vanilla as possible to ensure the problem wasn't related to anything we were doing on our team.

Did you try on iOS?  The issue does not exist on desktop or via browser emulation.

**Comment by stevkan** [comment]
@KarlPurk, thank you for reminding me to check the behavior on iOS. Yes, I believe I have repro'd your issue. When I tap on one of the chevrons or on the show/hide history and then try reversing the action by tapping again, then the card does not respond. What I found is that if I tap elsewhere on the card and then re-tap the same element, then the card functions as expected.

For example, tapping chevron "1" expands the details of the expense. Next, tap in a non-responsive part of the card, and then re-tap chevron "1" again to collapse the details of the expense.

Now that I have had a chance to see the behavior, I don't believe this to be a Web Chat issue. Web Chat merely imports the Adaptive Cards libraries for use in rendering cards passed in via an activity; it does not make any changes to the code or how they function in a web app.

As a workaround, you could try resetting focus to somewhere else on the page after one of the chevrons or show/hide history has been tapped. Otherwise, if that isn't a viable option, I would recommend you open an issue in the [Adaptive Cards](https://github.com/Microsoft/AdaptiveCards) repo for help on this problem.
