### ISSUE TITLE
Can't stop bot speech first 1 second by using WEB_CHAT/STOP_SPEAKING

### ISSUE THREAD

**Issue by Hevanddd** [microsoft/BotFramework-WebChat#4126]
## Screenshots

![image](https://user-images.githubusercontent.com/57950022/151523473-30d5dcd5-fc30-4456-bef9-2184dd0e0f96.png)

## Version
Npm "botframework-webchat": "4.8.1",

## Describe the bug

Hi. I'm using a botframework-webchat with cognitive services and when I'm trying to stop bot speech in first second by using WEB_CHAT/STOP_SPEAKING action - it doesn't work. As I see, in the console there is an action WEB_CHAT/MARK_ACTIVITY with payload speak: true and after that in the network I see the post request 

![image](https://user-images.githubusercontent.com/57950022/151525321-9e1a921b-48af-4447-a1d0-4cb8ca7da26e.png)

As I see, before this request is completed we can't stop bot speech. I use WEB_CHAT/STOP_SPEAKING and in the console we can see that bot uses WEB_CHAT/MARK_ACTIVITY with payload speak: false, that is correct. But anyway bot continues to speak.

Also, I tried to use useWebSpeechPonyfill hook to check if bot is speaking, but it shows that bot is speaking right after WEB_CHAT/MARK_ACTIVITY action and it is not true.

Is there any way to make sure that bot speech can be stopped?

## Expected behavior

I expect that we can stop bot speech in any moment after action WEB_CHAT/MARK_ACTIVITY with payload speak: true. 
## Additional context

After request bot really starts to speak and can be stopped by WEB_CHAT/STOP_SPEAKING  action as expected.

Thanks.

[Bug]

**Comment by stevkan** [comment]
@Hevanddd, unfortunately, I am unable to repro the issue you are experiencing. I setup Web Chat so that when I speak the phrase "stop bot from speaking", the store then dispatches `WEB_CHAT/STOP_SPEAKING`. And it works as expected. If I speak any other phrase, the bot responds by speaking the response. If I speak the above phrase, the bot does not respond with speech.

Regarding the `WEB_CHAT/MARK_ACTIVITY` action, I only see it dispatched when the bot response is spoken. Once prior, setting the `speak: true` property to the activity, and once after setting the `speak: false` property to the activity.

Are you able to supply a copy of your web chat code so that I may attempt a repro with it? If so, be sure to remove any secrets/keys defined within.

Lastly, is there a reason you have not upgraded to the newest version of Web Chat? There have been a number of improvements and bug fixes made since 4.8.1 was released.

**Comment by Hevanddd** [comment]
@stevkan thank you for your response.
I tried to upgrade to the newest version but it didn't help me.
The easiest way to reproduce this bug is to create middleware.
![image](https://user-images.githubusercontent.com/57950022/151786854-3e643002-230d-4d6b-8871-d244114d83ea.png)

![image](https://user-images.githubusercontent.com/57950022/151786926-14f3d664-5959-4678-9c20-0af9528b27d0.png)

![image](https://user-images.githubusercontent.com/57950022/151786985-e2f2ff05-674f-4b9c-bc93-eb3b2ccd67b0.png)

Then you should say something to the bot and he will start to answer and it will call WEB_CHAT/MARK_ACTIVITY with speak: true. After that, we call in our middleware action WEB_CHAT/STOP_SPEAKING to stop bot speech, then the bot calls  WEB_CHAT/MARK_ACTIVITY with speak: false. And firstly try to set timeout like 2000 ms and you will see that it works as expected - bot starts to speak and in 2 seconds it stops.  Then, please, set timeout like 200ms and you will that actions were called, but the bot speaks anyway...

In our application, we have 2 problems with this bug.
1) On the web we have a button that should stop bot speech. When the user clicks on it right after WEB_CHAT/MARK_ACTIVITY with speak: true - it doesn't work. In real life, this case is hard to reproduce.
2) We have react-native application that uses bot framework-webchat via webview and when the user goes to the background we call WEB_CHAT/STOP_SPEAKING and if the user catches this moment after WEB_CHAT/MARK_ACTIVITY with speak: true action, bot speaks in the background anyway.

**Comment by stevkan** [comment]
@Hevanddd, thank you for your patience while I looked into this. The issue you are encountering in your code really comes down to timing. Because you are filtering on 'MARK_ACTIVITY' (and 'speak' and 'true') and not on the incoming activity, itself, you are having to try and time when to silence the actual speaking process.

When I tested your code, I found that adjusting the timeout to 250 ms appeared to sufficiently block Web Chat from speaking the response. If I chose <250 ms, then I would be issuing 'STOP_SPEAKING' before the incoming activity arrived. If I chose >250 ms, then I'd catch it after it had already started speaking.

I've encountered this 'issue' before when trying to make adjustments to the CSS of an adaptive card being rendered in Web Chat. In this case, the AC attachment is in the incoming activity, but it takes time to process the activity and render it. I found that <50ms and I would risk 'missing' the AC card being rendered by issuing changes too soon. And, >~500 ms and the changes to the CSS are potentially visible to the user (i.e. they'll see colors change and divs move).

In your case, however, I have found that if you forgo filtering on 'MARK_ACTIVITY', and 'speak' and 'true', and just filter on 'DIRECT_LINE/INCOMING_ACTIVITY', it hits it on the head every time. There is no need to use `setTimeout()`.

```js
if ( action.type === 'DIRECT_LINE/INCOMING_ACTIVITY' ) {
      dispatch( {
        type: 'WEB_CHAT/STOP_SPEAKING'
      } )

}
```

That being said, if there is some reason you can't/don't want to filter on 'INCOMING_ACTIVITY' and, instead, use 'MARK_ACTIVITY', then you will need to figure out what timing looks like for the `setTimeout()`. I also can't speak to how latency and other network-type issues may or may not affect this on a per message basis.

One final note - in the setup shown above, while 'STOP_SPEAKING' is dispatched, it doesn't appear to be captured in the stream of actions passing thru Web Chat's store. I have some ideas on why, but they aren't important here. I just wanted you to be aware. I had added a console.log in the above to indicate when it was being issued as I was curious (see below).

![image](https://user-images.githubusercontent.com/18403946/153288877-0065d4e2-8a73-4055-bdbf-05e04aa305d6.png)

**Comment by Hevanddd** [comment]
@stevkan, DIRECT_LINE/INCOMING_ACTIVITY action doesn't help me, because a user can go to the background at any moment, so I need to have an opportunity to stop the bot speech at any moment and even right after WEB_CHAT/MARK_ACTIVITY with speak: true action. 

When I'm trying to stop speech right after DIRECT_LINE/INCOMING_ACTIVITY - it works as expected.
![image](https://user-images.githubusercontent.com/57950022/153392201-82641ad9-b514-4972-b7bd-746740a109ec.png)
![image](https://user-images.githubusercontent.com/57950022/153392408-b76b0490-f880-40b4-95ce-c53171504ef7.png)

But when I'm trying to stop speech right after WEB_CHAT/MARK_ACTIVITY - it doesn't work.
![image](https://user-images.githubusercontent.com/57950022/153392540-426bf295-baa3-4b39-9ffb-0d5d01f09e22.png)
![image](https://user-images.githubusercontent.com/57950022/153392797-2fbbca29-e9ea-41d9-99c2-d50eef67def6.png)

I tried to dispatch WEB_CHAT/STOP_SPEAKING via setTimeout with 1000ms right after WEB_CHAT/MARK_ACTIVITY speak: true, it helped me, but anyway, there are cases when a user has a bad internet connection and this action doesn't work. This approach is not safe.

Can I get from the library some promise and when it's done I would call stop WEB_CHAT/STOP_SPEAKING? Or maybe there is some way to cancel this request? I think that the library should do it from the box when WEB_CHAT/STOP_SPEAKING was called.

**Comment by stevkan** [comment]
@Hevanddd, thank you for your patience. The method by which you are trying to stop the speaking activity from occurring is not a supported method. The recommended way is as a response to the `INCOMING_ACTIVITY` action.

While I don't fully understand what you mean by "a user can go to the background at any moment", this shouldn't have an effect on whether or not the speech is able to be stopped or not.

Regardless, the recommended best practice is the process I referenced above. You are free to try other methods, but they then fall outside what is supported. If you choose to stay with what you are attempting to do and continue to encounter difficulties, it would be better to post the problem on Stack Overflow.
