### ISSUE TITLE
voice enabled bot

### ISSUE THREAD

**Issue by disha-s** [Microsoft/BotFramework-WebChat#413]
Hi,

I would like to know if there are any plans for introducing the feature of, user asking question to the bot over voice. Since we have this requirement of voice enabled bot.

**Comment by billba** [comment]
Direct Line itself doesn't have a notion of voice. So what is needed is a way to perform voice->text, then sending text to Direct Line. Then the other way around when a message is received from Direct Line.

There are a number of voice<->text services, including OS-level support, browser support in Chrome, and services from Microsoft, Google, Amazon, et al.

**Comment by disha-s** [comment]
We have tried using the browser support in chrome to enable voice -> text, then sending text to Direct Line by cloning the repository.
I would like to contribute on implementing this functionality. Please let me know on this.

**Comment by disha-s** [comment]
Any updates on this?

**Comment by billba** [comment]
Not yet. Please stay tuned.

**Comment by danmarshall** [comment]
Hi @disha-s we now have a solution for speech input - please see https://github.com/Microsoft/BotFramework-WebChat#enabling-speech-capabilities

**Comment by jaiswati** [comment]
In our webchat, we have enabled BotAuth , so that user should be able to login using Azure AD credentials (as follows) await context.Forward(new AuthDialog(new MSALAuthProvider(), options), async (IDialogContext authContext, IAwaitable authResult) => { aresult = await authResult; .... }

To enable voice, we are using Directline client as described here https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat-speech

For the first time , Bot displays Login Button and user is able to Login and can see email is sent to his/her id..

For the second time if another user logs in it does not display login button instead it shows email is sent to First user, somehow first user's token is retained for second user and so on.

If we remove the reference of Webchat.html (that contains directline reference to the Bot the functionality works fine..) Seems Directline retains the token, which causes above issue..

Any idea on how to fix this? quick response would be appreciated.
