### ISSUE TITLE
Direct line POST Invoke sign in Activity returns 400 Status Code error with message "Invalid or missing activities in HTTP body"

### ISSUE THREAD

**Issue by rudoleksa** [microsoft/BotFramework-WebChat#4260]
## Version
Direct Line REST API v3.0

## Describe the bug
To implement WebChat SSO, as described in the documentation, you need to send an activity to the bot with TokenExchangeInvokeRequest in the body of the request.
Flow 4th step - [https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-sso?view=azure-bot-service-4.0#sso-components-interaction](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-sso?view=azure-bot-service-4.0#sso-components-interaction). 
But as a result the API returns not 200 OK response with TokenExchangeInvokeResponse in a body. API returns 400 Bad Request with body:
```
{
    "error": {
        "code": "MissingProperty",
        "message": "Invalid or missing activities in HTTP body"
    }
}
```

## To Reproduce
1. Generate token for WebChat:
```
POST https://directline.botframework.com/v3/directline/tokens/generate
Authorization: Bearer <WebChat secret>
```

2. Send an invoke sign in activity to the bot
```
POST https://directline.botframework.com/v3/directline/conversations/<conversation id>/activities
Authorization: Bearer <token from previous step>
Content-Type: application/json
[other headers]

{
    "type": "Invoke",
    "name": "signin/tokenExchange",
    "value": {
        "id": "<any unique ID>",
        "connectionName": "<OAuth connection name (from the OAuth Card)>",
        "token": "<exchangeable token>"
    }
}
```

## Expected behavior
Returns 200 OK with TokenExchangeInvokeResponse in body:
```
{
    "status": "<response code>",
    "body": {
        "id":"<unique ID>",
        "connectionName": "<connection Name on the skill bot (from the OAuth Card)>",
        "failureDetail": "<failure reason if status code is not 200, null otherwise>"
    }
}
```

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by stevkan** [comment]
@rudoleksa, apologies for the delay and thank you for your patience. Are you still experiencing an issue with this? I attempted a repro with the solution you linked, however I am unable to get it to run. I added values into the two appsettings.json files. To be clear, for the ASP.NET.WebChat.SSO.Web project, I'm assuming that the AzureAD.ClientId and ClientSecret are coming from the OAuth app registration? I used the Application (client) ID located on the Overview blade as well as generating a new secret from the Certificates & secrets blade.

Also, in the Index.cshtml.cs file, I see it is looking for "<WebChat Secret>", "<Resource Uri>", and "connectionName" variables\properties to be defined. It doesn't appear that these are being pulled from anywhere. Do I need to hard code these values in? What value should be supplied for the `resourceUri` variable? I think I know what the value should be, but want to be sure since the solution is failing for me.

Are there any other values that I need to supply elsewhere or other details I should know that comes to your mind?
