### ISSUE TITLE
Property 'conversation' does not exist on type 'WebChatActivity'

### ISSUE THREAD

**Issue by mhmuftee** [microsoft/BotFramework-WebChat#4291]
Hello,

In 4.15.2 release changelog. 

A new type WebChatActivity is introduced in the botframework-webchat-core package

- If you are previously using the type DirectLineActivity, you may need to move to this new type

- All Web Chat APIs will use the newer type WebChatActivity
- The new type WebChatActivity is a well-defined type for handling activities inside Web Chat
- The existing type DirectLineActivity will be used solely for communicating with type DirectLineJSBotConnection, a.k.a. botframework-directlinejs package

I was using DirectLineActivity in my project, There was Conversation object in there.

Now I have tried to update to WebchatActivity, but my code does not work, as there is no Conversation object in the new WebchatActivity.

How do I solve this issue?

**Comment by stevkan** [comment]
@mhmuftee, do you have a project or code you can share that reproduces this? If yes, please remove any keys/secrets prior to posting here.

**Comment by mhmuftee** [comment]
`
import React from "react";

import { AttachmentMiddleware } from "botframework-webchat-api";

const attachmentMiddleware: AttachmentMiddleware =
  () =>
  (next) =>
  (...args) => {
    const [attachmentProps] = args;

    if (attachmentProps) {
      const { activity } = attachmentProps;
      console.log(JSON.stringify(activity, null, 2));
      //const { conversation } = activity;
    }

    return next(...args);
  };

export default attachmentMiddleware;

`

I have written an attachment middleware and pass it in webchat as a prop. The project is in TypeScript. 
When you print the activity you could see the conversation id there. but when I want to access the conversation in code 
it gives me an error that  **Property 'conversation' does not exist on type 'WebChatActivity'**

const { conversation } = activity;


`import attachmentMiddleware from "./AttachmentMiddleware";

<ReactWebChat
      className="react-web-chat"
      directLine={directLine}
      attachmentMiddleware={[attachmentMiddleware]}
    />
`

**Comment by stevkan** [comment]
@mhmuftee, I had a chance to speak with the lead developer of Web Chat and the `conversation` object was intentionally left out. In his words:

> `WebChatActivity` is a Web Chat-biased version of DL Activity. If `conversation` is not there, that means Web Chat "doesn't care" if this field exists or not.

His recommendation, if you are in need of it, is to extend the `WebChatActivity` class, adding the `conversation` property (and `id` sub-property) to it before sending.

As the `conversation.id` is part of the response when getting a token from Direct Line, it wouldn't be hard to append it to the new "`WebChatActivityWithConvoId`" class you created.

If that is too much overhead, you could simply append the conversation object to each outgoing activity, as shown in sample [04.api/b.piggyback-on-outgoing-activities](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/04.api/b.piggyback-on-outgoing-activities). I'm not sure if there is any reason to not use this method (I have used it and it has functioned fine) since the first option was the recommended method. But, it might be worth trying and testing.

**Comment by mhmuftee** [comment]
@stevkan 

Thank you for the response.

I kind of used the 1st approach, to get the conversation id from the activity.
