### ISSUE TITLE
response for thumbs up in javascript

### ISSUE THREAD

**Issue by akshay4malik** [microsoft/BotFramework-WebChat#4292]
Hi , 
I am facing an issue while displaying thumbs up and thumsdown after every response for my chatbot and it should display a differenr different message for both one for Thumbs up and one for thumbs down. I have used a js code which is able to display the icon and changing its color on hover but i am unable to achieve the response.

This is the code i have used-
```
var feedback = document.createElement("div");
     feedback.className="rating";
     responsePara.appendChild(feedback);
     // like button
     var like = document.createElement("div");
     like.className = "like grow";
     var thumbsUp = document.createElement('i')
     thumbsUp.className = "fa fa-thumbs-up fa-2x like";
     thumbsUp.ariaHidden = true;
     feedback.appendChild(like);
     like.appendChild(thumbsUp)


     // dislike button
     var dislike = document.createElement("div");
     dislike.className = "dislike grow";
     var thumbsDown = document.createElement('i')
     thumbsDown.className = "fa fa-thumbs-down fa-2x  dislike";
     thumbsDown.ariaHidden = true;
     feedback.appendChild(dislike);
     dislike.appendChild(thumbsDown)


$('.like, .dislike').on('click', function() {
    event.preventDefault();
    $('.active').removeClass('active');
    $(this).addClass('active');
```

Please help

**Comment by stevkan** [comment]
If you have the web chat components working as you want, then it's just a matter of instructing web chat to send an activity when either the thumbs up or thumbs down has been clicked and then having your bot respond, in kind. 

You can set this up by creating an event dispatcher on the thumbs up/down elements that, when clicked, fire an event. You then also setup an event listener that, when triggered, an activity is posted to your bot. The [04.api/d.post-activity-event](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/04.api/d.post-activity-event) demonstrates how to achieve this.

The kind of activity you send is up to you. You can send an event, a postBack, or even a custom activity type (e.g. instead of `activity.type: 'message'` you can send `activity.type: 'messageReaction'`). Once you decide on the kind of activity, then just have your bot respond to that specific activity.

This is basically the same process I did in my test bot and test Web Chat instances, as you can see below:

![messageReactionButtons](https://user-images.githubusercontent.com/18403946/169174470-4724a849-3414-4740-8807-f6b8f54956d9.gif)

This should get you on your way. I'm closing this as resolved.
