### ISSUE TITLE
[Screen Readers-Ask HR Virtual Assistant]: Screen readers(NVDA/JAWS) are narrating the source code in chat window when user invoked the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.

### ISSUE THREAD

**Issue by kattepalli** [microsoft/BotFramework-WebChat#4298]
**PWD Impact:**
Screen reader users are getting impacted if screen readers(NVDA/JAWS) are narrating the source code in chat window when user invoked the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.
 
**Test Environment:**
OS: Windows 10 version 21H1 (OS Build 19043.1110)
Browser: New Edge Version 92.0.902.62 (Official build) (64-bit)/Chrome Version 92.0.4515.107 (Official Build) (64-bit)
URL: https://askhrvadev.azureedge.net/?botOrigin=ec
Tools: NVDA 
 
**Repro Steps:**
Step 1: Enable Screen readers (NVDA/JAWS) and Open the above URL in the Chrome/Edge Browser using valid credentials.
Step 2: 'AskHR Virtual Assistant' Home page gets opened.
Step 3: Navigation: Select Benefits--> select Wellbeing Programme-->Wellbeing Programme gets displayed in chat window using down arrow key navigate to wellbeing Programme content and verify the Screen readers(NVDA/JAWS) behavior
 
**Actual Result:**
Screen readers(NVDA/JAWS) are narrating the source code in chat window when user invoked the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.
Ex: NVDA/JAWS narrating as "You said: Wellbeing Programme send at September 28 at 7:20 PM……………………………………….</span></p> </div></div>'',''Order".'',''ContentType}}} sent at send at September 28 at 7:20 PM Press ENTER to interact blank out of message blank activity Bot said: list with 1 items wellbeing programme"
 
**Expected Result:**
Screen readers(NVDA/JAWS) shouldn't narrate the source code in chat window when user invoked the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.
Ex: NVDA/JAWS should narrate as "You said: Wellbeing Programme send at September 28 at 7:20 PM activity Bot said: list with 1 items wellbeing programme"
 
**MAS Reference:**
[MAS 1.3.1 – Info and Relationships](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7b97358E88-4367-4121-BF9D-F0C6597D03B7%7d&file=MAS%201.3.1%20%E2%80%93%20Info%20and%20Relationships%20.docx&wdLOR=cC67AE285-FA8E-4A9C-8615-42813289BF4A&action=default&mobileredirect=true)

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html

**Comment by kattepalli** [comment]
Bug copied from CSEO team Bug id:-https://microsoftit.visualstudio.com/OneITVSO/_workitems/edit/8007427

**Comment by compulim** [comment]
The text content of the activity is actually code. That's why the screen reader is narrating code.

![image](https://user-images.githubusercontent.com/1622400/172481436-13854614-5b50-4cb8-b2d0-9d39ea40de08.png)

Please refer to this article to see how to add "alt text" to a message, https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/ACCESSIBILITY.md#controlling-the-narration-of-activities-and-attachments.

**Comment by compulim** [comment]
Talked with Sukesh offline. There are 2 approaches:

1. Easier
   - Add alt text to `channelData['webchat:fallback-text']`
2. More correct
   - Move the JSON from `text` field into `channelData`, the channel data is a property bag for storing anything serializable as JSON
   - Put human-readable text into the `text` field (say, alt text)
   - On custom render code, instead of parsing the JSON from the `text` field, use the JSON from the `channelData` field

**Comment by cwhitten** [comment]
Given offline discussions and approaches to address the issue. No action is needed on WebChat. This is a matter of adjusting the use of Web Chat and the configuration of the Bot. Closing
