### ISSUE TITLE
Adaptive Card - $when and isVisible parameters do not work on webchat

### ISSUE THREAD

**Issue by Kevv-J** [microsoft/BotFramework-WebChat#4421]
### Is it an issue related to Adaptive Cards?

- [X] Yes, this is an Adaptive Card issue but it is specific to Web Chat.

### What version of Web Chat are you using?

I am not using latest

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest), Browser: Firefox (latest), Platform: macOS

### Which area does this issue affect?

Attachment: Adaptive Card

### Is this an accessibility issue?

- [ ] Yes, this is an accessibility issue.

### Please describe the bug

$when and isVisible parameters in Adaptive Cards do not work in webchat which work in [Adaptive Card Designer](https://adaptivecards.io/designer/) as well as on Teams Channel.

### How to reproduce the issue?

1. Try to Render an Adaptive Card with isVisible set to False or $when parameter that evaluates to False
2. Elements with isVisible or $when evaluating to False are rendered on the webchat.

### What is the expected and actual behavior?

Expected:
Elements of the Adaptive card should be rendered depending on isVisible and $when params
Actual:
Elements are always being rendered regardless of isVisible or $when params

### Adaptive Card JSON
```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "TextBlock",
            "text": "Hello",
            "wrap": true,
            "isVisible": false
        },
        {
            "type": "ActionSet",
            "isVisible": false,
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Action.Submit"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "Hi",
            "wrap": true
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Action.Submit"
                }
            ]
        }
    ]
}
```

### Additional context

The WebChat version I'm using is 4.14.1.

**Comment by stevkan** [comment]
@Kevv-J - First and foremost, I would recommend that you update the Web Chat version as well as your adaptive card's schema version to the latest. For Web Chat, if using the CDN, you can simply specify 'latest' in the `src` ("<script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>"). Otherwise, if you're accessing the library via NPM, then the latest as of this writing is 4.15.4. For the adaptive card schema, the current version is 1.5 (which Web Chat supports). Using the latest of both will provide you with access to the most recent features, improvements, and fixes.

All that having been said, both of these features (i.e., the `isVisible` and `$when` properties) work for me using both Web Chat version 4.14.1 and adaptive card schema version 1.3. The issue you are encountering seems to be a misunderstanding of how these features are implemented. Well...that is true for `$when`. I'm not certain why `isVisible` isn't working for you as your code worked when I tested it.

To clarify, Web Chat doesn't build adaptive cards. It only renders the cards that are passed in. If the card is constructed correctly, then it will render it. The building of _any_ adaptive card is done only in the bot on the server side. With that in mind...

Regarding `isVisible`, updating the schema to version 1.5 _may_ help. It _should_ work already since it was introduced with version 1.2. I would also suggest sending the most basic adaptive card possible that implements this feature (i.e., just a TextBox in the body) and see if that works. Then add elements to your card and see if and when it stops performing.

Regarding `$when`, this is specifically a feature [adaptive tempating](https://learn.microsoft.com/en-us/adaptive-cards/templating/) which, as I mentioned earlier, is implemented on the server side. If you do not implement and only send this property in a card to Web Chat, it will be rendered as-is because Web Chat only renders the cards sent to it. It does do some validation and the sort, but it won't know how to read the `data` in this card because it only implements rendering. Thus, the card below would display `Your price is ${price}`, instead of the passing in the actual price value.

```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.5",
    "$data": {
        "price": 35
    }
    "body": [
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "Your price is ${price}"
        }
    ]
}
```

So, how can you implement templating in your bot for use in Web Chat? For a good understanding, follow the docs listed [here](https://learn.microsoft.com/en-us/adaptive-cards/templating/sdk). For a basic understanding (in a Javascript bot), here is a working example that sets up templating in a component dialog:

_Note:_ I have used schema version 1.3 to demonstrate it works, but I still strongly recommend updating to 1.5.

First, you need to store the templating **data** you want to access in a json file. You can call it "adaptiveCardData.json" or something else. Most of this came from sample data, but note I added two properties at the bottom: `price` and `sayHiOrHello`.

```json
{
  "title": "Publish Adaptive Card Schema",
  "description": "This is an adaptive card using templating.",
  "creator": {
    "name": "Matt Hidinger",
    "profileImage": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg"
  },
  "createdUtc": "2017-02-14T06:08:39Z",
  "viewUrl": "https://adaptivecards.io",
  "properties": [
    {
      "key": "Board",
      "value": "Adaptive Cards"
    },
    {
      "key": "List",
      "value": "Backlog"
    },
    {
      "key": "Assigned to",
      "value": "Matt Hidinger"
    },
    {
      "key": "Due date",
      "value": "Not set"
    }
  ],
  "speak": "This is an adaptive card using templating.",
  "price": 25,
  "sayHiOrHello": "Hello"
}
```

You also need your adaptive card JSON **template** (named "templatingDialog.json") which looks like an adaptive card but has templating values that correspond with the properties in the **data** file. In the below, I have added three TextBlocks: one that can be hidden and two that conditionally display based on the `sayHiOrHello` value. For fun, I also added an action button that toggles the hide-able TextBlock.

```json
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "text": "${title}"
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "type": "Image",
              "style": "Person",
              "url": "${creator.profileImage}",
              "size": "Small"
            }
          ],
          "width": "auto"
        },
        {
          "type": "Column",
          "items": [
            {
              "type": "TextBlock",
              "weight": "Bolder",
              "text": "${creator.name}",
              "wrap": true
            },
            {
              "type": "TextBlock",
              "spacing": "None",
              "text": "Created {{DATE(${createdUtc},SHORT)}}",
              "isSubtle": true,
              "wrap": true
            }
          ],
          "width": "stretch"
        }
      ]
    },
    {
      "type": "TextBlock",
      "text": "${description}",
      "wrap": true
    },
    {
      "type": "FactSet",
      "facts": [
        {
          "$data": "${properties}",
          "title": "${key}:",
          "value": "${value}"
        }
      ]
    },
    {
      "type": "TextBlock",
      "text": "TextBlock to Hide",
      "isVisible": true,
      "id": "hideTextBlock"
    },
    {
      "type": "TextBlock",
      "text": "Hi",
      "$when": "${sayHiOrHello == 'Hi'}"
    },
    {
      "type": "TextBlock",
      "text": "Hello",
      "$when": "${sayHiOrHello == 'Hello'}"
    }
  ],
  "actions": [
    {
      "type": "Action.ToggleVisibility",
      "title": "Toggle Text Visibility",
      "targetElements": ["hideTextBlock"]
    },
    {
      "type": "Action.ShowCard",
      "title": "Set due date",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "Input.Date",
            "id": "dueDate"
          },
          {
            "type": "Input.Text",
            "id": "comment",
            "placeholder": "Add a comment",
            "isMultiline": true
          }
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "title": "OK"
          }
        ],
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
      }
    },
    {
      "type": "Action.OpenUrl",
      "title": "View",
      "url": "${viewUrl}"
    }
  ],
  "speak": "${speak}",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3"
}
```

Lastly, here is the component dialog. For this to run I first installed the adaptive card templating library: `npm i adaptivecards-templating`.

```js
const {
  ActivityTypes,
  CardFactory,
} = require('botbuilder');
const { ComponentDialog, WaterfallDialog } = require('botbuilder-dialogs');
const ACData = require('adaptivecards-templating');

const calendarTemplate = require('./resources/json/ac-CalendarTemplate.json');
const templatePayload = require('./resources/json/ac-CalendarData.json');

const ADAPTIVE_CARD_TEMPLATING_DIALOG = 'adaptiveCardTemplatingDialog';

class AdaptiveCardTemplatingDialog extends ComponentDialog {
  constructor(id) {
    super(id);

    this.addDialog(new WaterfallDialog(ADAPTIVE_CARD_TEMPLATING_DIALOG, [
      this.displayAdaptiveCard.bind(this),
    ]));

    this.initialDialogId = ADAPTIVE_CARD_TEMPLATING_DIALOG;
  }

  async displayAdaptiveCard(stepContext) {
    const template = new ACData.Template(calendarTemplate);
    const cardPayload = template.expand({
      $root: templatePayload,
    });

    const reply = { type: ActivityTypes.Message };
    const adaptiveCard = CardFactory.adaptiveCard(cardPayload);
    reply.attachments = [adaptiveCard];
    return await stepContext.context.sendActivity(reply);
  }
}

module.exports.AdaptiveCardTemplatingDialog = AdaptiveCardTemplatingDialog;
module.exports.ADAPTIVE_CARD_TEMPLATING_DIALOG = ADAPTIVE_CARD_TEMPLATING_DIALOG;
```

This _should_ work for you as it does for me. If your bot is in C#, there are libraries available for use. Setup would be similar. Please test and let me know if it works.

**Comment by Kevv-J** [comment]
Hi @stevkan,
I have found the issue and its an issue on our UI package which was setting the CSS property `display: block !important;` to all elements of adaptive card, which forced all elements to be displayed, ignoring isVisible and $when params.
I am really sorry for the trouble I've put you through for giving me such a detailed reply.

From your inputs we have decided to upgrade webchat to the latest 4.15.4 version as well as try to upgrade to Adaptive Cards version 1.5. Although we had been reluctant about upgrading before because [Adaptive Card Designer](https://adaptivecards.io/designer/) still gives the warning that the target version(1.5) is greater than the version supported by webchat(1.3), just above the card payload editor.
![Screenshot from 2022-09-28 11-55-36](https://user-images.githubusercontent.com/38836436/192703833-518db32d-dea2-4108-81ef-d6cbbd4907e8.png)

Also thanks for explaining how templating works in adaptive cards. We have been using inline templating using $data which is what I used to test $when param like this -
`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "$data": {
        "name": "Kevin"
    },
    "version": "1.5",
    "body": [
        {
            "type": "TextBlock",
            "text": "This is a visible text block",
            "wrap": true,
            "$when": "${$data.name == \"Kevin\"}"
        }
    ]
}`

Sorry for the trouble and thanks for the quick reply.

**Comment by stevkan** [comment]
No worries! Glad you got it working.

Inline templating is perfectly acceptable. Using a separate file is useful when you have a collection of data to be used/maintained and you don't want to have to go chasing after it across your project.

As for the Designer, yeah, it needs to be updated. If you look at the change log for Web Chat you can see that in v4.12 the code was updated to automatically use the latest schema version available. Alternatively, you can set the max schema version that can be used via the `adaptiveCardsParserMaxVersion` StyleOptions parameter. Ref [here](https://github.com/microsoft/BotFramework-WebChat/releases/tag/v.4.12.1).

Closing as resolved.
