### ISSUE TITLE
How to remove suzie name for Action type ImBack

### ISSUE THREAD

**Issue by Aiswarya1794** [microsoft/BotFramework-WebChat#4455]
### I have a question

I have updated the manifest file to version 1.11 to receive all channel messages without @mentioned. ApplicationPermissions are also added.

We are using herocard to show all the commands ,

new CardAction()
{
                        Title = ResourceString.AvailableCommand,
                        Type = ActionTypes.ImBack,
                        Value = new Command(CommandType.SignIn, null, botName).ToString()
},

While clicking on the button , it is displaying the suzie name also. Can we remove that suzie name before the command

![RemoveSuzieName](https://user-images.githubusercontent.com/109646037/196250854-99d6df78-2010-4599-8bc9-110db16a7bd9.png)

**Comment by dmvtech** [comment]
Hi @Aiswarya1794 

Can you please provide a bit more information?

- This issue is oepned in the WebChat repository, but it _appears_ from the screen shot that the channel you are using is Teams.
- What channel are you using (does the issue happen in all channels or just one or a few)?
- What do you mean by *suzie* name? I don't see the name suzie anywhere in the screenshot.
