### ISSUE TITLE
How to send the title of the selected option to the bot?

### ISSUE THREAD

**Issue by MrDave1999** [microsoft/BotFramework-WebChat#4586]
### I have a question

I have the following adaptive cards:
```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Input.ChoiceSet",
            "choices": [
                {
                    "title": "Brackets",
                    "value": "1"
                },
                {
                    "title": "Cleaning",
                    "value": "2"
                }
            ],
            "id": "dentalServiceId",
            "placeholder": "Select"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"
        }
    ]
}
```
**Preview mode:**

[![choice-set](https://i.stack.imgur.com/FYRbk.png)](https://i.stack.imgur.com/FYRbk.png)

I use webchat bot framework and when I click "submit", it sends me only the **value** of the selected option in json format:
```json
{ "dentalServiceId": "1" }
```
I would like to know if it is possible to send the **title** of the selected option when clicking on the **submit** button.

**Comment by stevkan** [comment]
@MrDave1999 - The short answer is, if you don't need to rely on the numbered values in each choice, then simply replace them with the values you actually wish to receive. If you do need the numbered values, then I would suggest creating an array, enum, or similar on the bot side that will map the returned value to a string value of the same name as the selected button title. Otherwise, there is no way to send the title in place of the value.

Closing the issue as this should resolve the problem. If you need a more detailed response, please note the below.

-------------------------
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework-WebChat Github](https://github.com/Microsoft/BotFramework-WebChat/) repo is the preferred platform for information on submitting **bug fixes** and **feature requests**.
