### ISSUE TITLE
Webchat keyboard focus not moving focus to new message on submission

### ISSUE THREAD

**Issue by LawrenceHarvey123** [microsoft/BotFramework-WebChat#4663]
Hi,

I've been asked to see if there a way for force the keyboard focus to move from an adaptive card action when pressed.

The idea being that the keyboard focus could then move to the new reply from the bot as a result or pressing the adaptive card action button.

Please let me know if there are any overrides that may help with this.

Kind regards

**Comment by stevkan** [comment]
@LawrenceHarvey123 - Can you provide some additional details:

- Which version of Web Chat are you using (4.15.x or something else)?
- Which flavor of Web Chat are you using (`WebChat.renderWebChat()` or `ReactDOM.render()`)?
- To clarify, when a user clicks a button and the transcript window advances as new messages are processed you are wanting the focus to shift back to the send box, correct?
- Are you able to share your code (minus any secrets / keys)?

In the meantime, I will research this and let you know what I find.

**Comment by LawrenceHarvey123** [comment]
Hi @stevkan,

Please see below for the answers. It's also interesting to note that the behaviour also exists for PVA preview when using a "basic card". Essentially when clicking action buttons on cards from earlier in a conversation the incoming bot response to the button scrolls the user to see it. The keyboard focus is still locked on clicking the button. The user has to manually exit the card and scroll to see the response a second time. The ideal would be that the keyboard focus goes to the latest response or at least goes to the message box I guess.

**- Which version of Web Chat are you using (4.15.x or something else)?**

4.15.7

**- Which flavor of Web Chat are you using (WebChat.renderWebChat() or ReactDOM.render())?**


WebChat.renderWebChat() 

**- To clarify, when a user clicks a button and the transcript window advances as new messages are processed you are wanting the focus to shift back to the send box, correct?**

Either the send box or ideally the latest response from the bot.

**- Are you able to share your code (minus any secrets / keys)?**

Not sure I can share the code I'm afraid. But as I said this is even the case for a basic PVA preview bot embed.
Using keyboard controls click an action button and notice how the keyboard focus is locked to the button pressed rather than moving to the response or message box in reaction.

**Comment by stevkan** [comment]
@LawrenceHarvey123 - The simplest solution would be to set the focus on the send box after every message activity from the bot. Obviously, I can't say for certain that this won't interfere with other activities that might come thru since I am not familiar with the conversational flow of your bot. But, as it's based off of conditions, the most basic being `if ( activity.from.role === 'bot' )...`, you can adjust those to meet your needs.

```js
const store = window.WebChat.createStore( {}, ( { dispatch } ) => next => action => {
  if ( action.type === 'DIRECT_LINE/INCOMING_ACTIVITY' ) {
    const activity = action.payload?.activity;
      if ( activity.from.role === 'bot') {
        document.querySelector( 'input.webchat__send-box-text-box__input' ).focus();
      }
  }
  next( action );
};

[ ... ]

window.WebChat.renderWebChat(
  {
    directLine: directLine,
    store: store
  },
  document.getElementById( 'webchat' )
);
```

![setFocusToSendBox](https://user-images.githubusercontent.com/18403946/225084638-530d588f-04d8-49f7-bda3-9a3709a83435.gif)

This should suit your needs, but test this out and let me know.

**Comment by LawrenceHarvey123** [comment]
Hi @stevkan ,

Thank you for this. Seems to be working for us.

Out of interest is there a way to shift the focus into the most recently received item or is it message box only you think?

Really helping us move forward, thanks again.

**Comment by stevkan** [comment]
@LawrenceHarvey123 - Thank you for your patience. You _should_ be able to focus on any element that is rendered. To do this you will need to consider the following:

1) Since there may be multiple cards already displayed that have the same element type or class, you will need to capture the last one to have rendered and act on that one.
2) There is a very slight delay between Web Chat receiving an activity and Web Chat rendering the associated HTML. It may be necessary to wrap a small time out (~50-300 ms) around the focus call in order to ensure the element exists on the page. In past tests, going much beyond 300 ms can result in any UI updates becoming noticeable. You will want to experiment with this, however, if even necessary.
