### ISSUE TITLE
DirectLine Bot Framework Reset Activities Array when a new Conversation Id is Created

### ISSUE THREAD

**Issue by aliraza944** [microsoft/BotFramework-WebChat#4682]
### I have a question

I am integrating my bot deployed on Microsoft azure with React. I am using the `botframework-webchat-component` and `botframework-webchat` to create a directline. To display my conversation with the bot I am using the `useActivities()` hook from the `botframework-webchat-component`.<br/>
The problem is that when I create a new **conversation id** the `useActivities()` is not resetting to its default value. The latest message in the default message from the array but it also contains all the conversation texts of the previous conversation.<br />
**My question is how can I reset the `useActivities()` hook to remove all the conversations when a new conversation ID is created?**

**Comment by stevkan** [comment]
@aliraza944 - The simplest method for resetting the store's state is to pass in an empty array, like so: `store.getState.activities = []`.

As this should resolve your issue and because this is a 'how to' question, I am closing this. Please note the below message.

------------------------

The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework-WebChat](https://github.com/Microsoft/Bot Framework-WebChat/) GitHub repo is the preferred platform for information on submitting **bug fixes** and **feature requests**.
