### ISSUE TITLE
Mutation Observer Error on Web Chat with DirectLine

### ISSUE THREAD

**Issue by pkbullock** [microsoft/BotFramework-WebChat#4849]
### Is it an issue related to Adaptive Cards?

Yes, this is an Adaptive Card issue, however it only repro on Web Chat.

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest)

### Which area does this issue affect?

Attachment: Adaptive Card

### Please describe the bug

Getting an error when rendering an adaptive card. The same card works in other channels e.g. Teams.  The bot works but when asking question, the response is blank with the below error.

My bot is using direct line (not the App Extension) 

Tried versions: 4.15.9 and 4.15.8 still show same issue.

### Do you see any errors in console log?

```js
webchat.js:2  TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at webchat.js:2:357774
    at webchat.js:2:366928
    at va (webchat.js:2:3150203)
    at Ya (webchat.js:2:3157002)
    at Wa (webchat.js:2:3159971)
    at webchat.js:2:3177636
    at t.unstable_runWithPriority (webchat.js:2:3188508)
    at Ms (webchat.js:2:3177570)
    at ks (webchat.js:2:3177346)
    at xs (webchat.js:2:3176691)
```

### How to reproduce the issue?

1. Navigate to the bot site
3. Type "anything" in the send box

Adaptive card does not render.

### What do you expect?

Render of the adaptive card.

### What actually happened?

Blank reply box.

### Adaptive Card JSON

```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "Container",
            "style": "emphasis",
            "items": [
                {
                    "type": "TextBlock",
                    "size": "large",
                    "weight": "bolder",
                    "text": "Example Adaptive Card",
                    "style": "heading",
                    "wrap": true
                }
            ],
            "bleed": true
        },
        {
            "type": "Input.Date",
            "label": "Enter the start date with the company",
            "id": "startDate",
            "isRequired": true,
            "errorMessage": "Please enter a date"
        },
        {
            "type": "Input.ChoiceSet",
            "choices": [
                {
                    "title": "Yes",
                    "value": "yes"
                },
                {
                    "title": "No",
                    "value": "no"
                }
            ],
            "placeholder": "Select an option",
            "label": "Have you had a change of contract this year?",
            "id": "contractStart",
            "isRequired": true,
            "errorMessage": "Please select an option"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Next",
                    "id": "calculateForm",
                    "associatedInputs": "auto",
                    "style": "positive",
                    "data": {
                        "verb": "verbhere"
                    }
                }
            ]
        }
    ]
}
```

**Comment by compulim** [comment]
> This seems to be a timing issue with loading the page possibly.

I tried to trace the code and it is probably passing `element` as falsy [here](https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/bundle/src/adaptiveCards/Attachment/AdaptiveCardRenderer.tsx#L224).

However, to make it passing falsy, rough looking, the possible cause could be a [render error](https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/bundle/src/adaptiveCards/Attachment/AdaptiveCardRenderer.tsx#L178C20-L178C27). The `errors` variable was set.

The `errors` should be propagated by the `<ErrorBox>`. However, since we didn't check `errors` before calling `useLayoutEffect()`. The call failed and we couldn't render the `<ErrorBox>`.

So tl;dr, I guess:

- Web Chat failed to render the Adaptive Cards
- An error was thrown during the call to AC renderer
- We didn't check error, we still apply the AC mod to a falsy `element`, which triggered an uncaught exception
- The uncaught exception stopped us from rendering the `<ErrorBox>` and displaying the error message properly

Web Chat should do an error-check before applying the AC mod. Then, you may see the AC render error message.

FYI, I am able to render your card without any `MutationObserver` error.

![image](https://github.com/microsoft/BotFramework-WebChat/assets/1622400/f0032373-fc7e-4ab9-993f-5fdff0ee5e88)

Note to dev:

1. In this [`useLayoutEffect`](https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/bundle/src/adaptiveCards/Attachment/AdaptiveCardRenderer.tsx#L223), add a condition
2. If the `element` is falsy, there is a render error. We should not apply the mods

**Comment by compulim** [comment]
This card will fail with Adaptive Cards renderer error.

```js
{
  contentType: 'application/vnd.microsoft.card.adaptive',
  content: {
    // We want to render a failing Adaptive Cards, adding "*" here to fail the renderer.
    type: '*AdaptiveCard*',
    $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
    version: '1.5',
    body: [
      {
        text: 'Hello, World!',
        type: 'TextBlock'
      }
    ]
  }
}
```

**Comment by compulim** [comment]
@pkbullock We have a fix in pull request.

I think the Adaptive Cards you are rendering is not correct. Thus, it's causing a weird `MutationObserver.observe` error.

Once this PR is merged, you can see what render error the AC card is causing in console. However, to workaround the issue today, you should look at the AC card JSON and see what's happening. I think the card you pasted above isn't the one that is causing the error.

**Comment by pkbullock** [comment]
Thank you @compulim, I found the PR #4852  and tested it, was much easier to diagnose the issue with the adaptive cards when the error message contained the details. Apparently, I needed to add errorMessages and labels to input fields. 

Apologies the original supplied adaptive card didn't have the input fields.
