### ISSUE TITLE
It it possible to hide black frames (solid and thin dashed) appears when click on free space inside webchat

### ISSUE THREAD

**Issue by namit008** [microsoft/BotFramework-WebChat#4859]
### Is your feature request related to a problem?

Black frames (solid and thin dashed) appears when click on free space inside webchat.
Client is not ready to accept black borders.

### Describe the suggestion or request in detail

There must be a way to over ride the boders.

**Comment by namit008** [comment]
![Screenshot_2023-09-13-18-14-52-97_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/microsoft/BotFramework-WebChat/assets/68066146/3938deac-c09d-47a2-82d3-d798a391bb27)

In above image we need to hide borders.

**Comment by stevkan** [comment]
@namit008 - I don't know if you are still experiencing an issue with this. However, you can alter the dashed border that surrounds the individual message in the transcript window by targeting the below classes (according to my tests).

**For example:**
```js
.webchat__basic-transcript:focus .webchat__basic-transcript__activity-indicator--focus {
  border: 2px !important;
  border-color: red !important;
  border-style: dotted !important;
}
```

![image](https://github.com/user-attachments/assets/784a15c3-231b-4cf4-8a93-46171f5837b1)

Please keep in mind that Web Chat is built with React. As such, while sometimes necessary, it is considered a best practice to _not_ make changes to the DOM outside of Web Chat as React is not able to track these changes. Additionally, because you would be targeting classes defined by Web Chat in order to make the UI adjustment, future changes to Web Chat may result in a broken experience for your users should these classes receive an update in either name or function.

As this should resolve your issue, I am closing this. If you experience an issue with this implementation, please feel free to reopen this. Otherwise, any how-to type questions should be directed to Stack Overflow for community support.
