### ISSUE TITLE
WebChat: Support for ‘stream’ output in ChatGPT style while using Azure OpenAI Completion

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-WebChat#4876]
Bot responses with Azure OpenAI Completion, but we need the response to be displayed in a live streaming format.

### Describe the suggestion or request in detail

Allow Application that uses Bot framework webchat to stream out the response like ChatGPT web chat does.

**Comment by compulim** [comment]
This is good.

Internally, we are planning this feature, streaming texts/completions from Azure OpenAI and other capable services into Web Chat.

**Comment by HesselWellema** [comment]
Implementing this would be much appreciatedd. We still rely on your webchat widget for most of our implementation. The time it takes to get the full response from the azure openai-api is perceived as latency by users.

**Comment by pedrojlazevedo** [comment]
This feature, after MSTeams update is a must!

**Comment by wsp174212** [comment]
Thanks for your help, Is there an ETA for this feature?

**Comment by HesselWellema** [comment]
Or maybe share some insight in what to expect

**Comment by biyukai88** [comment]
May I ask when you plan to go online？We are all looking forward to this feature！

**Comment by HesselWellema** [comment]
I spend a lot of time the last days to find a solution for this. All samples I found only print chunks to the console. I did not find one sample or idea to send it to an application. Is it even possible via directLine? I did find some workarounds wrt Teams chatbots but the seam a bit hacky

**Comment by HesselWellema** [comment]
Working on some ideas to make this work made me wonder.
Streaming the content to the webchat agent might end up being very expensive since webchat is a premium channel. Are there any plans to address this by the team?

**Comment by HesselWellema** [comment]
@compulim. Just a question. Would it be an option to use a signalR service to manage the streaming of answers.

**Comment by rliberoff** [comment]
Hello Team!

This feature is really important. Today, it is possible to update an activity in teams (`await turnContext.UpdateActivityAsync(responseActivity, cancellationToken);`) creating a stream (or typing) experience like ChatGPT. 

However, it is currently impossible to do so with the Webchat 😟

When can we expect this feature?

Thank you.

**Comment by anshumankmr** [comment]
Hey folks, is there a workaround for this in Bot Framework WebChat?

**Comment by HesselWellema** [comment]
https://github.com/microsoft/BotFramework-WebChat/issues/5121#issuecomment-2042229329

**Comment by DukaJ** [comment]
Dear Mr. Wong, first of all thank you for your effort and commitment that Webchat is working stable so many years!
Please check my question below:

Are there any updates on this topic that enable streaming responses through Webchat component through Bot framework SDK?
This is extremely important feature since without it, in the era of LLM, usage of the component is having challenges.

**If you may please share expected date for this to be enabled** @compulim 

Kind regards and thank you in advance!

**Comment by Joekraft** [comment]
@compulim could you clarify what #5141 is meant to resolve here? It appears to be implementing a typing indicator, and "livestreaming"? But there is no clear documentation or examples how this links back to the expected support of response streaming from AI generated answers?

**Comment by compulim** [comment]
I am adding a `LIVESTREAMING.md` in the PR #5265. The document outlines how to send livestreaming from the bot code and also bot/channel/client supportability.

@DukaJ thanks for your support and understanding, the document would explain how to add it to the bot.

@Joekraft we are extending the typing activity for livestreaming. So, yes, you will send a typing activity for livestreaming. Despite typing activity has been available for a very long time, its design is naturally extensible to cover livestreaming cases in additional to typing indicator. In some future, it could be used for bot-assisted auto-completion too. 😉

**Comment by ericzon** [comment]
Hello @compulim I've been following the LIVESTREAMING.md because I would like to test it in the webchat version and I created a code like this (this is being executed in on_message_activity):

```python
async def streaming_example(self, turn_context):
        typing_activity = Activity(
            type=ActivityTypes.typing,
            text="loading...",
            channel_data={
                "streamType": "streaming",
                "streamSequence": 1
            }
        )
        first_chunk = await turn_context.send_activity(typing_activity)
        print(f"first_chunk -> {first_chunk}")
        partial_responses = ["Part 1 of the message...", "Part 2 of the message...", "Part 3 of the message..."]
        stream_id = first_chunk.id
        print(f"first_chunk.id -> {stream_id}")

        for i, part in enumerate(partial_responses, start=2):
            typing_activity = Activity(
                type=ActivityTypes.typing,
                text=part,
                channel_data={
                    "streamId": stream_id,
                    "streamSequence": i,
                    "streamType": "streaming"
                }
            )
            print(f"sending activity > typing_activity: {typing_activity}")
            response = await turn_context.send_activity(typing_activity)
            await asyncio.sleep(2)

        final_activity = Activity(
            type=ActivityTypes.message,
            text="Full message genereated by the bot.",
            channel_data={
                "streamId": stream_id,
                "streamType": "final"
            }
        )
        print(f"sending activity > final_activity: {final_activity}")
        return await turn_context.send_activity(final_activity)

```

In my frontend I have a basic webchat example using https://cdn.botframework.com/botframework-webchat/latest/webchat.js but as a result it starts with the typing until it appears the last message. Nothing similar to a chatgpt style. Maybe I'm missing something?

Thank you

**Comment by JordanReyesLeger** [comment]
Hello @compulim  
I’m implementing the [LiveStreaming functionality as documented in livestreaming.md](https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/LIVESTREAMING.md), but I'm experiencing issues when testing it with WebChat using DirectLine.

Here’s the C# code I’m using based on the documentation:

```csharp 
var activityInicial = new Activity
{
    Type = ActivityTypes.Typing,
    ChannelData = JObject.FromObject(new
    {
        streamSequence = 1,
        streamType = "streaming"
    })
};
`
var response = await dc.Context.SendActivityAsync(activityInicial, cancellationToken);
await Task.Delay(500, cancellationToken); // Simulate generation delay

var activity2 = new Activity
{
    Text = "A quick brown fox",
    ChannelData = JObject.FromObject(new
    {
        streamId = response.Id,
        streamSequence = 2,
        streamType = "streaming"
    }),
    Type = ActivityTypes.Typing,
};
await dc.Context.SendActivityAsync(activity2, cancellationToken);
await Task.Delay(500, cancellationToken);

var activity3 = new Activity
{
    Type = ActivityTypes.Typing,
    Text = "A quick brown fox jumped over the",
    ChannelData = JObject.FromObject(new
    {
        streamId = response.Id,
        streamSequence = 3,
        streamType = "streaming"
    })
};
await dc.Context.SendActivityAsync(activity3, cancellationToken);
await Task.Delay(500, cancellationToken);

var activity4 = new Activity
{
    Type = ActivityTypes.Typing,
    Text = "A quick brown fox jumped over the streaming text",
    ChannelData = JObject.FromObject(new
    {
        streamId = response.Id,
        streamSequence = 4,
        streamType = "streaming"
    })
};
await dc.Context.SendActivityAsync(activity4, cancellationToken);
await Task.Delay(500, cancellationToken);

var finalActivity = new Activity
{
    Type = ActivityTypes.Message,
    Text = "A quick brown fox jumped over the streaming text",
    ChannelData = JObject.FromObject(new
    {
        streamId = response.Id,
        streamSequence = 5,
        streamType = "final",
    })
};
await dc.Context.SendActivityAsync(finalActivity, cancellationToken);

``` 
Despite following the instructions in the documentation, all the content appears at once at the end, instead of progressively rendering as expected (similar to the Teams streaming example (I saw the idea is the same that teams):

- https://learn.microsoft.com/es-es/microsoftteams/platform/bots/streaming-ux?tabs=csharp).

This seems to contradict the intended UX described in the doc. I’ve also reviewed this thread and @ericzon has the same problem

My assumptions so far:
Implementation is correct and follows the documented guidance.

The problem may be related to how DirectLine handles streaming activities.

Either the functionality is not working as documented, or the documentation is missing important configuration requirements.

Some body can help us to update the documetation or fix the problem? 

Thank you!
