### ISSUE TITLE
Presence of extraneous <article> tags can cause confusion for screen reader users

### ISSUE THREAD

**Issue by cryptasian** [microsoft/BotFramework-WebChat#4984]
### Is it an issue related to Adaptive Cards?

No.

### Are there any code-based customization done to Web Chat?

No, I am using Web Chat without any customizations except "styleOptions".

### What version of Web Chat are you using?

Latest production

### Which area does this issue affect?

Live region

### What is the public URL for the website?

https://edfinancial.com

### How to reproduce the issue?

This is feedback from the accessibility company Allyant who has been testing our website and has people who use screenreaders and other assistive technologies as a part of their testing team.

![extraneous-article-tags](https://github.com/microsoft/BotFramework-WebChat/assets/30207740/fbec5e90-adc1-4051-86e6-a2b725d1964f)

### What do you expect?

Remove the extraneous <article> tags from the page. Also remove any child <header> or <footer> elements if present inside of the <article> tags.

### What actually happened?

See other responses.

### WCAG reference

https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships

**Comment by compulim** [comment]
This is by design. Chat history is implemented using `feed`/`article` roles, https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Feed_Role.

You can read more about it here, https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/ACCESSIBILITY.md#using-rolefeed-and-rolearticle-to-represent-the-chat-history-and-activity.
