### ISSUE TITLE
Vertical Image is Stretched in Chat Window

### ISSUE THREAD

**Issue by chergott** [microsoft/BotFramework-WebChat#5227]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which area does this issue affect?

Chat history

### Which theme pack does this issue affect?

I did not test it on other theme packs

### Please describe the bug

When user attaches a vertical image (more height than width), the image is stretched to fit chat bubble's width

Image should preserve the same aspect ratio

Issue reported in https://msazure.visualstudio.com/CCI/_workitems/edit/27675762

### How to reproduce the issue?

Steps to reproduce found in https://msazure.visualstudio.com/CCI/_workitems/edit/27675762

### What do you expect?

Image should preserve aspect ratio and not stretch fully to chat bubble's width

### What actually happened?

Image is stretching horizontally and image appears distorted

### Do you have any screenshots or recordings to repro the issue?

![image](https://github.com/microsoft/BotFramework-WebChat/assets/17168935/b0e9f48f-1bb6-42e8-bf9d-153281e2fbe5)

![image](https://github.com/microsoft/BotFramework-WebChat/assets/17168935/dd518895-5aeb-4434-8222-00f3091aab9b)

**Comment by stevkan** [comment]
@chergott - Just a few questions:

- Verifying that the 'latest production' version that you used is 4.17.0?
- The link you provided is generating a 404. I'm not certain that either my colleague or I can access it, anyhow. Could you post the steps for repro'ing directly?
- How is the image being sent? Is it part of a card (hero card, for example)? Can you provide sample bot code for this? Actually, it looks like this is from Copilot Studio...? Can you provide any relevant details on how you constructed this in Copilot?

**Comment by compulim** [comment]
Verified this issue is related to a CSS rule overridden in Copilot Studio, causing Web Chat not to honor the aspect ratio of the image.

![image](https://github.com/microsoft/BotFramework-WebChat/assets/1622400/62d2c6e4-ed07-4992-ab94-6b9a509380f5)

When the highlighted rule is disabled, the image will display using its default aspect ratio.

During investigation, we found a potential feature improvement, https://github.com/microsoft/BotFramework-WebChat/issues/5235.

Closing this issue as the aspect ratio bug is related to Copilot Studio.

The feature improvement would help reducing paddings across images.
