### ISSUE TITLE
End conversation topic doesn't end the chat

### ISSUE THREAD

**Issue by SriChandraDronavalli** [microsoft/BotFramework-WebChat#5348]
### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which theme pack does this issue affect?

I did not test it on other theme packs

### Please describe the bug

End conversation topic doesn't end the chat  while working with Webchat in Javascript.

### How to reproduce the issue?

1. Navigate to ...
2. Click on ...
3. Type "..." in the send box

### What do you expect?

When a end conversation topic is triggered it should end the chat

### What actually happened?

It is not ending the chat after end conversation topic is triggered.

**Comment by stevkan** [comment]
@SriChandraDronavalli - Thank you for your patience. While there are technically both `OnEndOfConversation` and `OnEndOfConversationActivity` handlers in the ActivityHandlers class, these two are used only with bots built in Composer and with skills. You can't rely on these handlers to be called in order to issue a related activity to Web Chat.

However, with respect to Web Chat, this can be fudged, as Web Chat doesn't restrict the type of activities that can be received. So, for instance, if your bot has a cancel/quit type of event or activity, the bot can issue an activity of type `endOfConversation`, or whatever you would like your activity type to be called. The naming is up to you. For simplicities sake, I'll use the above.

In Web Chat, you just need to handle it. I have a test instance of Web Chat where I test a lot of custom implementations, including this, successfully.

In my bot, I have a cancel interrupt. When the user types 'cancel' (plus some other dialog), I send the following from the (JS) bot:

```js
const message = { type: `endOfConversation` };
await context.sendActivity(message);
```

In Web Chat's store, I have the following (plus a bunch of other unrelated stuff):

```js
const store = await createStore({}, ({ dispatch }) => next => async action => {
    switch (action.type) {
        case 'DIRECT_LINE/INCOMING_ACTIVITY':
            const activityType = action.payload.activity.type;
            switch (activitytype) {
                case 'endOfConversation':
                    console.log('WEB_CHAT => END_OF_CONVERSATION_RECEIVED');
        		    // Do stuff
            }
    }
});

window.WebChat.renderWebChat({
    directLine: directLine,
    store: store
})
```

Under the 'Do stuff' section, you have a couple options that can be included here:
1) If you want to clear Web Chat's store of stored activities, but retain the conversation Id and the watermark, then enter the following:

```js
store.getState().activities = [];
```

2) However, if you want to clear the store as well as restart Web Chat with a new conversation Id, then do the following. To explain, first, (if desired) you will want to clear the stored activities otherwise they still display after restarting. Second, you will need to create a new `directLine` object and pass that into the `renderWebChat` component. Third, you will need to dispatch `DIRECT_LINE/RECONNECT` which tells Web Chat to, essentially, reload the `renderWebChat` component now using the new 'directLine' object.

The result will be a cleared Web Chat transcript window, followed by any start of conversation dialog, and a new conversation Id and reset watermark.

```js
store.getState().activities = [];
await restartWebChat();
store.dispatch( {
	type: 'DIRECT_LINE/RECONNECT'
} )
```
