### ISSUE TITLE
Move React, react-dom and @types to npm peerDependencies

### ISSUE THREAD

**Issue by prannayb** [Microsoft/BotFramework-WebChat#598]
Our parent project uses react 15.6.1 and latest @types/react 15.0.39. But the botframework-webchat package lists react and the types as dependencies. This causes react and the 15.0.38 typings to get installed under the bot package and conflict with the typings in my project, and doesn't compile. Please move react and its typings package to peerDependencies so that it can use the ones already installed via my project.

**Comment by danmarshall** [comment]
Hi @prannayb thank you for reporting this. I'm not certain that we can move our typings to peerDependencies. Would this force others to manually install each of the peer dependencies manually?

FYI we just recently locked to exact version numbers because some updates were breaking our build. We may be able to revisit this for React.

**Comment by corinagum** [comment]
Fixed in v4
