### ISSUE TITLE
HeroCard does not work on webchat but works perfectly on the emulator

### ISSUE THREAD

**Issue by vademecumx** [Microsoft/BotFramework-WebChat#647]

**Comment by billba** [comment]
A bug report is more than a title.

There is ample evidence that HeroCard does work in WebChat, so you'll need to provide data to show otherwise. Ideally you'd show us the JSON for the message in question.

Also "does not work" can mean any number of things. Be specific. What results do you expect, and what results are you getting?

What form of WebChat are you using - the channel? The npm package (w/version)? Your own build?

Help us help you.

**Comment by vademecumx** [comment]
Thanks for your answer.
![code](https://user-images.githubusercontent.com/25336177/29575339-72baa76a-8764-11e7-87cf-d239d591f991.png)


Thus, i don't use the JSON implementation. My app is deploy on Heroku . 

![webpage](https://user-images.githubusercontent.com/25336177/29575178-0680663e-8764-11e7-843c-58252df03fb2.png)
![emulator](https://user-images.githubusercontent.com/25336177/29575179-06823bd0-8764-11e7-8fde-ee9683cc39d1.png)

On the emulator, i have the expected result but on webchat (not the skype one), I just have the text message and not the card one. 

node v8.0.0
npm v5.3.0

**Comment by danmarshall** [comment]
Hi @vademecumx can you tell me how you are using the WebChat? Is this an iframe of webchat.botframework.com, or are you hosting your own? Is this happening in all types of browsers?

Also, can you open you browser's debugger and see if you have any errors in the console.

**Comment by vademecumx** [comment]
Thanks every one. I finally succeed to fix my problem using JSON implementation.
