### ISSUE TITLE
Button orientation in Hero/reciept cards

### ISSUE THREAD

**Issue by ac-vikram** [Microsoft/BotFramework-WebChat#685]
Hello, 
 By default in hero or receipt card, we get the buttons vertically using latest version of botchat.js. But I want buttons side by side (horizontally) in some cards and vertically in some other cards in same application. is there a way that I can send actionOrientation -vertical or horizontal from code behind? Or any other way you can tell that I can show buttons as per my need.
Thanks.

**Comment by ac-vikram** [comment]
![image](https://user-images.githubusercontent.com/30788239/30289415-b5778ad8-9749-11e7-8bd4-e4e036b22a4a.png)

This is image of buttons in horizontal orientation. The same way we can show vertically. please response if there is a way that we can control while making card and buttons in it.

**Comment by danmarshall** [comment]
Hi @ac-vikram, you can change your [actionsOrientation](https://docs.microsoft.com/en-us/adaptive-cards/display/hostconfig#actionsorientation) in the [adaptivecards-hostconfig.json file](https://github.com/Microsoft/BotFramework-WebChat/blob/master/adaptivecards-hostconfig.json#L70). After you [change this value you will need to rebuild your chat](https://github.com/Microsoft/BotFramework-WebChat/blob/master/AdaptiveCards.md#building-your-customization). 

Keep in mind that all of your cards will have the same orientation. If you need different orientation on a card-by-card basis, you might try creating completely custom AdaptiveCards, where your buttons are in a [ColumnSet](http://adaptivecards.io/explorer/#ColumnSet). Then, each Column can have a [SelectAction so that they are clickable and act like buttons](http://adaptivecards.io/explorer/#Column).

**Comment by ac-vikram** [comment]
Hi danmarshall, thanks for your reply. But we are not using Adaptive cards, we are using receipt and hero card only in our application. It would be good if you could tell the solution for receipt and hero card.

**Comment by ac-vikram** [comment]
@danmarshall , that's true. we can achieve that in adaptive cards. But we are using receipt/hero card already for existing functionality as there was no adaptive card introduced earlier . So, it wouldn't be possible for us to make it adaptive from receipt/hero for existing functionality.

**Comment by danmarshall** [comment]
Hi @ac-vikram, Adaptive Cards are the Bot Framework's way of creating cards for custom scenarios. If this doesn't work for you, then this is why we have provided the source code for you. Feel free to modify the source code to fit your needs.

**Comment by danmarshall** [comment]
You may also want to try [SuggestedActions](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-suggested-actions) which appear as a slide-up drawer at the bottom of the chat.
