### ISSUE TITLE
Uncaught exception SpeechRecognitionError

### ISSUE THREAD

**Issue by Akhila9** [Microsoft/BotFramework-WebChat#716]
How to resolve this error

**Comment by Akhila9** [comment]
@msgits2 @msftgits @eanders-MS @billba @danmarshall Can you help me resolving this issue.

**Comment by billba** [comment]
Please don't randomly spam people to get help.

Also, a one sentence title isn't a bug report. Please report as many details as possible, sample code, etc.

**Comment by Akhila9** [comment]
As mentioned in https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/speech/index.html, I have used Native browser speech as a speechoption, then I am facing this error, Hope you can help to resolve that.
![screenshot 115](https://user-images.githubusercontent.com/16335305/31349008-1684d24e-ad3f-11e7-955b-05e0d57f6394.png)

**Comment by danmarshall** [comment]
Hi Akhila, I agree with Bill - the best way to get help is to provide details.

Please see this article: https://docs.microsoft.com/en-us/bot-framework/channel-connect-webchat-speech
The "not-allowed" error usually means:
* The user did dot allow the browser access to the microphone
* The URL of the page that contains Web Chat begins with `http://` instead of `https://`
* The URL is a local file using the `file://` protocol instead of `http://localhost`...

**Comment by Akhila9** [comment]
Okk @danmarshall. Thank you for your help,I will try resolving that.

**Comment by danmarshall** [comment]
Hi @Akhila9 - hope you got this issue resolved. I am closing for now but you can re-open if you are still seeing issues.
