### ISSUE TITLE
Name: BotChat or WebChat

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#73]
I'm using a simple "wc-" prefix for CSS class names to avoid collision. If we standardize on BotChat perhaps I should change to "bc-", or even something else. Also, I'm considering the [SUIT naming convention](https://suitcss.github.io/), if it's not too heavyweight. The high level consideration is avoiding naming collision when this is embedded.

**Comment by billba** [comment]
The reason I chose "BotChat" is that it's perfectly descriptive in the domain of web components. If you're creating a React app that consumes multiple components it would be silly to have WebChat and WebCalendarPicker and WebTable.

One could argue that it would be even more descriptive to call it MSBotChat.

**Comment by danmarshall** [comment]
MSBotChat sounds good

**Comment by billba** [comment]
I'm probably okay with that. What would you like to use for the prefixes? msbc-?

**Comment by danmarshall** [comment]
According to SUIT, it would be MSBotChat

**Comment by billba** [comment]
Okay by me.

**Comment by eanders-MS** [comment]
At the same time, “web chat” is a common name we give to web chat interfaces (though maybe a little old-school at this point). Searching github for WebChat returns 1056 repositories. I venture that web chat could be considered a compound word, like post office, or real estate (or compound word!).

I do think the package name should have a more explicit reference to the Bot Framework, so that it is evident in search results. The emulator’s repo is called botframework-emulator. Maybe call this one botframework-webchat?

https://www.github.com/Microsoft/botframework-webchat/

**Comment by billba** [comment]
Yes I agree that is a good, descriptive name for the repo. But in the context of npm and React I think it makes sense to have the package/component name be botchat/msbotchat. It is just a little weird but not remotely unheard of, to have the repo and package have pretty different names.

**Comment by eanders-MS** [comment]
Sounds good to me.
