### ISSUE TITLE
Suggestion: customizable header title via format options

### ISSUE THREAD

**Issue by shade33** [Microsoft/BotFramework-WebChat#754]
I can do it. What do you think?

**Comment by danmarshall** [comment]
Interesting idea. I think it can be solved a few different ways already: changing the resource strings in Strings.ts, or just hiding the header with CSS and implementing your own HTML header. So the question is, how are you hosting the WebChat? Because the way you host it may determine the way you solve it. What's your scenario?

**Comment by shade33** [comment]
We use our own build of the webchat code for some sites, so I want to have a way change header title outside the webchat code.

**Comment by danmarshall** [comment]
Since you have your own build, you can add a custom prop [here](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Chat.tsx#L17), and then consume it [here](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Chat.tsx#L185).

**Comment by shade33** [comment]
I've done it for myself this way. But I think it can be usefull for others and can be commited to the main branch.

**Comment by marcel-ernst** [comment]
+1 for `format options`

**Comment by compulim** [comment]
Fixed in #810.
