### ISSUE TITLE
Calendar for DataTime Field? in FormFlow

### ISSUE THREAD

**Issue by nnahmed** [Microsoft/BotFramework-WebChat#790]
Hi

How to show Calendar for DataTime Field? in FormFlow. 

https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-formflow#comments-container

**Comment by danmarshall** [comment]
Hi @nnahmed - I believe that FormFlow only comprises text-based prompts and inputs. You can use an Adaptive Card to show a [date picker](http://adaptivecards.io/visualizer/index.html?card=/payloads/Input.Date.json).

Since your question is more of a "how-to", would you please ask on [Stack Overflow](https://stackoverflow.com/search?q=botframework). Here in this repo, we are only tracking issues with Web Chat. 

> Questions can be posted at [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework) using the `BotFramework` tag. Please note that Stack Overflow has guidelines such as requiring a descriptive title, a complete and concise problem statement, and sufficient details to reproduce your issue. Feature requests or overly broad questions are off-topic; new users should visit the [Stack Overflow Help Center](https://stackoverflow.com/help/how-to-ask) for more details.

**Comment by nnahmed** [comment]
@danmarshall Thanks for the Reply, it is not related to Adaptive Card, It is related to FormFlow, If you declared a field as DateTime, i want to show it as  Calendar for more user friendly way to enter date.

See the link
http://aninteractive.ae/screen.jpg

Please check and give me your suggestion.

Thanks

**Comment by danmarshall** [comment]
Hi @nnahmed, FormFlow uses only text. It does not show UI pickers. If you want to file an issue with FormFlow, please visit https://github.com/microsoft/botbuilder
