### ISSUE TITLE
Unable to do npm install.

### ISSUE THREAD

**Issue by QiiLin** [Microsoft/BotFramework-WebChat#855]
It seems Like I am unable to do npm install, 
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-59_binding.node":
HTTP error 404 Not Found

the url is not working ... how to solve this?

**Comment by billba** [comment]
Please include as much relevant information about your config as possible. Versions of your OS, node, npm, etc. Off hand I would guess that you might need to update your node/npm.

**Comment by miteshpatekar** [comment]
I had a same issue. I started powershell in admin mode and command "npm install -g" worked for me

**Comment by compulim** [comment]
This is fixed in #873.

`node-sass` provide precompiled binary for most setup, otherwise, it will run node-gyp + Python + Visual C++ + Windows SDK to build `libsass` binary on your box.

Since Node.js 9 updated their interop, `node-sass@4.5.0` don't have precompiled binaries for Windows 64-bit + Node.js 9. Thus, if your box doesn't have the mentioned toolchain, it will fail.

We bumped `node-sass` to `4.7.2` and verified they download precompiled `libsass` library. So even you don't have the toolchain, it will just works on Node 9.6.1.

**Comment by QiiLin** [comment]
Thanks alot
