### ISSUE TITLE
Botchat.js getting expected identifier error in IE 11

### ISSUE THREAD

**Issue by Falansh** [Microsoft/BotFramework-WebChat#864]
Hi, I'm using directline API to attach my bot to our site. It is working fine in Chrome, Firefox ,Edge. But when I try the same in IE , I'm getting the following error while trying to debug :

**Expected identifier
File: botchat.js, Line: 1, Column: 573**
Because of which the botchat.js is not getting loaded and I'm getting the second error as well
**'BotChat' is undefined**

I am using the below botchat.js 
 **<script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>**

**Comment by Falansh** [comment]
One more thing we are hosting this page within SharePoint 2010.

**Comment by sakthiganeshTroy** [comment]
Hi, Is this issue resolved? I am facing the same issue when using IE-11. Thanks.

**Comment by Falansh** [comment]
Hi, I'm still getting error with IE 11 and sharepoint. It is working fine in all other browsers. For work around we created a different html page which will be given as hyperlink in the Sharepoint page and we will pass the user details from Sharepoint page to the redirected page.

**Comment by sakthiganeshTroy** [comment]
Falansh, Thank you for the response and workaround. I have this issue when embedding the ChatBot in a html page and loading it in WPF webbrowser control. Will find an alternative workaround to use within the WPF itself.

**Comment by shafi-mohammed** [comment]
@Falansh, That's great you have a work around. Btw, did you use the botchat.js in your new html? 
Thanks.

**Comment by Falansh** [comment]
@shafi-mohammed Yes we have used botchat.js

**Comment by compulim** [comment]
We have two `botchat.js` build right now. One is for IE11 (with ES5 polyfills), another is for modern browsers (without polyfills).

Since we just push the ES5 polyfill to CDN, we don't have a production version on CDN yet, the latest pre-release is https://cdn.botframework.com/botframework-webchat/0.13.1-master.248c723/botchat-es5.js.

When the next version is out, you will find both ES5-polyfill and non-polyfill at https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js.

**Comment by Ashish-Jovial** [comment]
I am facing same issue, i raise the issue at following link.
https://github.com/Microsoft/BotFramework-WebChat/issues/1749
