### ISSUE TITLE
Unable to load webchat in IE 11 after last release.

### ISSUE THREAD

**Issue by reshmamkumar** [Microsoft/BotFramework-WebChat#916]
Hi, 
After the release of BotFramework-WebChat on 21-03-2018, my bot stopped working in Internet Explorer-11. The error that I'm getting in console is attached below.

![image](https://user-images.githubusercontent.com/26716124/37810635-3165738e-2e90-11e8-958d-0257770dac1e.png)

My code always retrieves the latest version of botchat.js from the CDN.
Can anyone help me with this.

**Comment by compulim** [comment]
We splitted polyfills and build and forget to update the README.

Instead of using `botchat.js`, can you use the one with polyfills called `botchat-es5.js`? The difference between them is `botchat-es5.js` is `botchat.js` plus polyfills required for ES5 browsers (IE11).

**Comment by Troesler95** [comment]
Could you provide the URL at which the `botchat-es5.js` file is located? There doesn't seem to be anything located at [https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js](https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js)

**Comment by ankitbko** [comment]
@compulim Could you update the url for `botchat-e5`?

**Comment by compulim** [comment]
We just fixed our CI/CD to deploy ES5 builds to CDN. But since we just enabled that, only pre-release build is on CDN.

The latest pre-release (`master.248c723`) is at https://cdn.botframework.com/botframework-webchat/0.13.1-master.248c723/botchat.js. You can look up for versions at https://www.npmjs.com/package/botframework-webchat?activeTab=versions.

I have a bug #1019, after that one is fixed, you should able to get pre-release build much easier.

**Comment by compulim** [comment]
Since CI/CD is fixed, I am closing this for now.

**Comment by compulim** [comment]
Just got a fix in #1020. The latest pre-release can be downloaded from  https://cdn.botframework.com/botframework-webchat/master/botchat.js. No more commit tags in the URL. Please mind that the caching latency is 15 minutes.

**Comment by anandvardhandas** [comment]
Instead of using botchat.js, we can use botchat-es5.js for IE11. So similarly do we have a separate botchat.css version for IE11 compatibility because in IE11, Adaptive card contents are not loading in proper format and also in carousel adaptive card, left and right scroll is not working whereas all these things are working perfectly fine in Edge and chrome.

**Comment by wal88** [comment]
I'm also having problems with adaptive cards in IE 11. After downgrading to 1.0 adaptive cards it finally renders but AdaptiveTimeInput and AdaptiveDateInput don't work, they're just text inputs. I've tried directline with botchat-es5.js and also many different versions with iframe ("&v=0.14.0", also tried master, latest, 0.12.0, 0.13.0). I really need the time and date input to work as I don't want to redo the input handling just to support IE 11
