### ISSUE TITLE
Documentation about SuggestedAction & History

### ISSUE THREAD

**Issue by sammydeprez** [Microsoft/BotFramework-WebChat#940]
Is there any documentation about what the SuggestedActions & History object can do? And how to use it?

**Comment by dmvtech** [comment]
Hey Sammy. I apologize that this question wasn't addressed earlier. Hopefully you've got an answer before now.

To quickly answer:
"Suggested actions enable your bot to present buttons that the user can tap to provide input. Suggested actions appear close to the composer and enhance user experience by enabling the user to answer a question or make a selection with a simple tap of a button, rather than having to type a response with a keyboard. Unlike buttons that appear within rich cards (which remain visible and accessible to the user even after being tapped), buttons that appear within the suggested actions pane will disappear after the user makes a selection. This prevents the user from tapping stale buttons within a conversation and simplifies bot development (since you will not need to account for that scenario)."

You can find a sample here (this is a v4 sample):
https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/08.suggested-actions

Additionally, in the future; these types of "how to" questions are best addressed in [Stack Overflow](http://stackoverflow.com/search?q=%23botframework)
