### ISSUE TITLE
WebChat RoadMap -Query

### ISSUE THREAD

**Issue by telkomops** [Microsoft/BotFramework-WebChat#948]
Please let us know the road-map or planned releases.  We have latest v0.12.1 Tagged and Adaptive-Cards 1.0 branch. What is our plan moving ahead?

**Comment by compulim** [comment]
We are planning more customizability. Instead of forks, we have some cool ideas to let you customize without forking, and less painful to update to latest Web Chat even you have customized it a lot. And lots of samples to show how to customize Web Chat.

For customization, it is not only about color/themeing, but also something like adding new types of bubbles, replacing Markdown engine, replacing carousel with stack.

Not to mention we have a new UI design. We will try to keep both the old/new UI by a pluggable UI engine. You can even bring a headless UI (e.g. command-line interface). The backend engine will be isolated and runnable under pure JavaScript (e.g. NodeJS).

All the development work will be done public on GitHub so contributions are always welcome.

**Comment by compulim** [comment]
@telkomops please look at our GitHub [Projects](https://github.com/Microsoft/BotFramework-WebChat/projects) page, we are currently triaging issue that target IGNITE event.
