### ISSUE TITLE
URL origin webchat

### ISSUE THREAD

**Issue by eskivelevolution** [Microsoft/BotFramework-WebChat#958]
Hi,

Has a way to get the URL origin webchat (URL from browser that send and receive the messages). I need validate if the URL origin is the URL that instanced the BotFramework.

If I use for example (**origin**):

```
BotChat.App({
        directLine: { secret: '{directline_secret}' },
        user: { id: '{user_id}', origin : window.location.href},
        bot: { id: '{bot_id}' },
    }, document.getElementById('bot'));
```

It can be changed in browser, I need get it from header.

Thank you!

**Comment by alexvingg** [comment]
Could anyone help?

I need it too !!

**Comment by compulim** [comment]
There aren't any secure solution if you are passing it in JavaScript. Maybe you can post it in [BotBuilderSDK](https://github.com/Microsoft/BotBuilder/issues) and ask them for a better solution.

If you are using token (instead of secret, and is generated on the server-side), I think you can use CORS to secure your URL origin.
